### ISSUE TITLE
[admin] importazione di massa fallisce con comitato indicato in modo errato

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#101]
Come da oggetto, dovrebbe gestire l'errore e invece fallisce come documentato in allegato.
![screenshot - 24012016 - 16 01 18](https://cloud.githubusercontent.com/assets/3878935/12536960/dd5d404a-c2b3-11e5-9111-de89fe606347.png)

**Comment by AlfioEmanueleFresta** [comment]
Dovrebbe essere ora risolto (ti tornera' errore piuttosto che fallire).
