### ISSUE TITLE
[admin] Importazione di massa: stampa report non è a colori

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#102]
https://gaia.cri.it/admin/import/volontari/

Il testo dice:
"Per favore salva questa pagina in formato PDF a colori (Stampa) e inoltrala al richiedente tramite Kayako"

ma la stampa risulta in bianco e nero.

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra nella stampa solo i bordi dei box vengono colorati, questo e' intenzionale.

**Comment by alfiomusmarra** [comment]
Allego uno screenshot di come appare. Anche la parte oscurata è ovviamente
in bianco e nero.

2016-01-24 17:58 GMT+01:00 Alfio Emanuele <notifications@github.com>:

**Comment by AlfioEmanueleFresta** [comment]
Puoi allegare usando copia e incolla su github, gli allegati alle email
vengono buttati via.

**Comment by alfiomusmarra** [comment]
![mozilla](https://cloud.githubusercontent.com/assets/3878935/12537807/1d327f68-c2c9-11e5-9558-d98faf1b14f9.png)
Ri-allego screenshot

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra il documento e' correttamente colorato per ora, secondo lo stile bootstrap. Reputi necessario aggiungere colorazione?

**Comment by alfiomusmarra** [comment]
Se il risultato che vedi in allegato (che nel mio visualizzatore p in bianco e nero) è quello voluto, ritengo che almeno le righe di errore bloccante andrebbero evidenziate maggiormente con una colorazione rossa per tutta la lungezza.
