### ISSUE TITLE
[admin] Importazione di massa esige presenza email

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#103]
Come da oggetto, non viene effettuato l'import di righe di anagrafica senza email.

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra non mi risulta. Tieni presente che gli avvisi (punti esclamativi) non sono bloccanti. Che errore ti da?

**Comment by alfiomusmarra** [comment]
Allego screenshot

2016-01-24 17:58 GMT+01:00 Alfio Emanuele <notifications@github.com>:

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra la validazione dell'indirizzo e-mail viene effettuata solo se un indirizzo e-mail e' specificato.

Prova a verificare che il CSV non includa una stringa con uno spazio `" "` o simile.

![image](https://cloud.githubusercontent.com/assets/621062/12537834/7b34d7ee-c2c1-11e5-8a44-557197d2f574.png)

Altrimenti, riapri questo issue per favore.

**Comment by alfiomusmarra** [comment]
Confermo che c'erano degli invisibili spazi bianchi.

Non concordo però sull'esito "non inserisco la riga".
Se possibile, inserirei una azione del tipo "togli gli spazi bianchi" prima delle altre, in maniera di convogliare le righe "campi mail con spazi bianchi" da "non le importo" a "le importo ma non creo utenza"
