### ISSUE TITLE
corsi base: incongruenza tra contatori

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#106]
il contatore nella lista corsi e quello nel dettaglio sembrano non collimare (già discusso con alfio).

**Comment by AlfioEmanueleFresta** [comment]
Migliorato con 412a96d5713493b9abfe95e644f84f3429d4c106.

**Comment by matthewmazzoleni** [comment]
nella mascherina vedo 11 richieste in attesa di conferma e due negate, io non ho mai negato a nessuno, come prova oggi ad una degli 11 ho confermato la richiesta.
un candidato mi ha mandato ieri la richiesta, arrivatami via mail, non è pero inserito negli elenchi delle richieste, ma solo nei messaggi di posta e da li non riesco a confermare la richiesta.

**Comment by AlfioEmanueleFresta** [comment]
Il volontario si e’ ritirato – aggiustero’ le diciture e aggiungero’ mail di notifica 


Alfio Emanuele Fresta

Tel.: +44 (0) 746 0975 967
Email: alfio.emanuele.f@gmail.com
