### ISSUE TITLE
riserva: errore se data fine non valorizzata

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#107]
ho cercato di inserire una riserva per un volontario lasciando il campo di fine vuoto come suggerito per impostare la fine indeterminata.
Facendo in questo modo si ottiene però un errore che riporta la seguente dicitura: "La fine di una riserva non può avvenire prima del suo inizio".

**Comment by AngeloLupo** [comment]
Sia da US, sia da volontario GAIA non suggerisce piu' di lasciare il campo vuoto

**Comment by AlfioEmanueleFresta** [comment]
Corretto, ho rimosso tempo addietro la dicitura.
