### ISSUE TITLE
mail: allegati non scaricabili

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#109]
dal rilascio di Jorvik diversi utenti segnalano che gli allegati inviati (per ora mai comunicazioni singole ma sempre mass messaging) non risultano raggiungibili ovvero scaricabili.

**Comment by AlfioEmanueleFresta** [comment]
Stesso problema riguardante i Link nelle e-mail. Dalla posta in Gaia sono
scaricabili

Alfio Emanuele Fresta

**Comment by AlfioEmanueleFresta** [comment]
riconducibile a #93
