### ISSUE TITLE
aggiungi persona: errore integrità

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#110]
cercando di censire una persona un US ottiene:

IntegrityError at /us/aggiungi/
duplicate key value violates unique constraint "anagrafica_persona_codice_fiscale_key"
DETAIL: Key (codice_fiscale)=([CF_OSCURATO_DA_SUPPORTO]) already exists.
Request Method: POST
Request URL: https://gaia.cri.it/us/aggiungi/
Django Version: 1.8.7
Exception Type: IntegrityError
Exception Value: 
duplicate key value violates unique constraint "anagrafica_persona_codice_fiscale_key"
DETAIL: Key (codice_fiscale)=(CF_OSCURATO_DA_SUPPORTO) already exists.
Exception Location: /usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py in execute, line 64
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.4.3
Python Path: 
['.',
'',
'/usr/lib/python3.4',
'/usr/lib/python3.4/plat-x86_64-linux-gnu',
'/usr/lib/python3.4/lib-dynload',
'/usr/local/lib/python3.4/dist-packages',
'/usr/lib/python3/dist-packages']
Server time: Mar, 26 Gen 2016 14:08:12 +0100
Traceback Switch to copy-and-paste view

**Comment by AlfioEmanueleFresta** [comment]
Il problema e' che il valore veniva reso maiuscolo prima del salvataggio in database, solo che il controllo di esistenza veniva fatto in maniera case-sensitive. Quindi, erroneamente, non veniva bloccato come non esistente, ma l'indice di univocita' impediva l'inserimento in database.

Ho risolto forzando la resa in maiuscolo prima del controllo.
Fatto anche per il modulo di registrazione (`ModuloStepAnagrafica`).
