### ISSUE TITLE
titoli cri: impossibile modificare dati dello stesso

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#111]
segnalano l'impossibilità di modificare un titolo CRi inserito, ad esempio nelle date di termine.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni il problema e' che abbiamo due casi:
- Titoli con poche informazioni, che possono essere rapidamente cancellati e reinseriti,
- Titoli CRI o Patenti CRI che devono essere confermati dal Presidente. La modifica invaliderebbe la "garanzia" fornita dal presidente. Quindi anziche' permettere la modifica, e' necessario reinserire il titolo per una nuova approvazione.
