### ISSUE TITLE
richiesta riserva: anomalie varie

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#113]
verificato:

Oggi sono arrivate sulla e-mail del Presidente due comunicazioni che il volontario chiedeva riserva per motivi personali.
Accedendo come Ufficio Soci lo vedo nell'elenco dei Soci in riserva, ma non è stato autorizzato da me nè dalle due collaboratrici dell'US Provinciale
Accedendo poi come Presidente lo trovo come richiesta in attesa, peraltro con una dicitura anomala sull'appartenenza con la doppia dicitura comitato, che vi riporto qui sotto.

Pinco Pallino XXXXXXXXXXX Comitato Provinciale Di AAAAA, Comitato Provinciale Di AAAAA: Sede BBBBB

**Comment by AngeloLupo** [comment]
Fixato con 9f692560667b2d60a5a0536c66c8f4a2a8e7c2e7
Non sono riuscito a trovare la doppia dicitura ma l'errore era nell'elenco che includeva i volontari con richiesta di riserva, senza discriminare sulle autorizzazioni.
