### ISSUE TITLE
[admin] Importazione di anagrafiche senza nome e link ai dettagli

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#114]
Nel passaggio dei dati dalla vecchia gaia a gaia jorvik sono stati importati anche profili anagrafici parziali provvisti, ad esempio, di solo cf e data di nascita. In questo caso però, effettuando la ricerca per cf in "persona" il campo "nome" rimane vuoto senza il link che consentirebbe di accedere ai dettagli.

**Comment by AlfioEmanueleFresta** [comment]
Risolto.
