### ISSUE TITLE
estensione: permettere termine anticipato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#117]
viene richiesta la possibilità come in precedenza di terminare l'estensione anticipatamente (lato utente e ufficio soci)

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo non dovrebbe essere possibile?

**Comment by AngeloLupo** [comment]
Controllo

**Comment by AlfioEmanueleFresta** [comment]
Fatto?

**Comment by AngeloLupo** [comment]
ancora da testare

**Comment by matthewmazzoleni** [comment]
up
