### ISSUE TITLE
riserva: terminare anticipatamente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#118]
viene richiesta la possibilità di interrompere anticipatamente una riserva (lato utente e ufficio soci)

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo hai risolto? Ricorda di usare `Fix #no` nei messaggi di commit che vuoi che chiudano gli issue.

**Comment by AngeloLupo** [comment]
ancora da testare

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
up
