### ISSUE TITLE
schede: dipendenti anche volontari

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#119]
molte richieste riguardanti la possibilità di indicare come dipendente (con tutte le conseguenze del caso) un volontario.

**Comment by AlfioEmanueleFresta** [comment]
Assegno priorità bassa solo perché, come da discussione con @matthewmazzoleni, il trattenere questa informazione al momento attuale non giova alcun beneficio se non l'estrazione dei dipendenti.

**Comment by luca-dex** [comment]
Al momento le appartenenze da dipendente vengono aggiunte lato admin e funzionano correttamente
