### ISSUE TITLE
Stato di Nascita-Stato di Residenza: manca il Kosovo

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#122]
Come da oggetto, 

nella tabella degli stati che dà origine alle associazioni per stato di nascita e di residenza e in futuro forse anche per la nazionalità, sembra mancare il Kosovo.

Seppure è uno stato NON universalmente riconosciuto, tuttavia la Repubblica Italiana lo riconosce dal 21 febbraio 2008. Sarebbe quindi da inserire

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra utilizziamo un modulo di terze parti al fine di tenere la lista aggiornata senza necessita' di manutenzione da parte nostra. La domanda relativa al Kosovo e' stata piu' volte da loro affrontata (vedi https://github.com/SmileyChris/django-countries/issues/25).

Il Kosovo non fa parte degli stati riconosciuti dallo [standard ISO 3166](https://it.wikipedia.org/wiki/ISO_3166-1) e quindi non verra' incluso fino a che non verra' integrato in tale standard.

A meno che ci sia stata richiesta l'inclusione, non ho ragione di credere che ci sia motivo di andare a forzare l'inserimento (che romperebbe gli aggiornamenti futuri automatici da aISO 3166).

**Comment by alfiomusmarra** [comment]
La Repubblica Italiana riconosce i passaporti emessi dallo stato del Kosovo? E' questa la domanda. Se un quattordicenne è nato nel Kosovo che deve indicare? Mica possiamo aspettare i tempi dell'ONU che su questo non ha potere sulle decisioni di Roma.
Comunque, capisco la comodità di uno standard ISO e di una libreria già pronta. Riapriamo l'issue al primo volontario nato in Kosovo.
