### ISSUE TITLE
sedi: spostamento volontari

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#126]
viene richiesto, da parte di US, la possibilità di spostare un Volontario tra le sedi del Comitato.

**Comment by AlfioEmanueleFresta** [comment]
Mi sembra di capire da #70 (@AngeloLupo) che il trasferimento e' gia' possibile usando la normale procedura di trasferimento. Quando lo spostamento e' tra sedi dello stesso Comitato, non e' richiesto il protocollare la domanda (non viene effettuata "richiesta" ma viene attuata immediatamente).

**Comment by AngeloLupo** [comment]
Confermo che e' gia' possibile farlo e funziona come descritto da Alfio
