### ISSUE TITLE
supporto: disponibilità ambiente beta

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#127]
necessitiamo di un ambiente demo, con email attive, da utilizzare per verifiche/formazione/prove a livello di supporto. fatichiamo a fornire supporto, a tutti i livelli. dovendo anche organizzare la formazione necessitiamo di tale ambiente.
grazie

**Comment by AlfioEmanueleFresta** [comment]
Come da richiesta ho provveduto alla creazione di 5 ambienti di staging, per l'uso relativo alle necessita' di supporto, formazione, testing, sviluppo e staging. 

Continueremo in privato il perfezionamento di questo strumento.

**Comment by AlfioEmanueleFresta** [comment]
Aggiunte credenziali presidente con Comitato fittizzio.
