### ISSUE TITLE
aspiranti: funzionalità per revocare adesione ad un corso

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#130]
come da oggetto. lo permetterei fino all'accettazione fisica al corso da parte del direttore.

**Comment by AlfioEmanueleFresta** [comment]
Non e' come accade correntemente?

L'aspirante puo' ritirare la richiesta fino all'accettazione dell'aspirante al corso.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni riapri se necessario.
