### ISSUE TITLE
attività: modifica genera errore 500

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#131]
la modifica dell'attività "sportello sociale" del Comitato 3 genera errore 500

**Comment by AlfioEmanueleFresta** [comment]
Non mi risulta @matthewmazzoleni. Se il caso non si e' ripetuto, e' da considerarsi un errore causato dalla connessione interrotta durante un aggiornamento.

Riapri se accade di nuovo pls
