### ISSUE TITLE
Valle d'Aosta e "livelli" di comitato

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#134]
L'ufficio soci della Valle d'Aosta non vede il tasto "dimetti" di fianco ai suoi volontari. Dice di vederlo solo di fianco agli ex ordinari.

Da un controllo veloce sembra che le cariche della Val d'Aosta siano "regionali" id 1189, mentre i volontari siano della Val d'Aosta "provinciale" id 1190.

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra bisogna effettuare la doppia nomina in questo caso. La regionale continua a permettere di avere l'elenco soci su tutta la "regione", mentre quella locale da permessi piu' ampi (gestione soci) a livello di comitato.
