### ISSUE TITLE
[elenchi elettorali] Modalità di estrazione degli elettori

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#137]
Da GAIA:
"In questo elenco sono mostrati tutte le persone registrate a Gaia che soddisfano tutti i seguenti requisiti:

    Soci attivi (volontari) del Comitato alla data delle elezioni;
    Anzianità di 2 anni, calcolata con appartenenze di tipo Socio attivo o ordinario;
    Nessuna dimissione registrata negli ultimi 2 anni"

Un volontario viene dimesso per errore. Per rimediare, il presidente lo riassocia al comitato con la stessa data di inserimento ma, ovviamente, senza data di fine appartenenza.

Appartenenze:
da xx a yy comitato zz
da xx a "senza data" comitato zz

 Questo volontario NON verrà estratto dagli elenchi elettorali nonostante abbia una appartenenza da più di due anni in corso e confermata probabilmente perché il sistema rileva la "dimissione" errata.

Suggerimento: inserimento in elenco elettorale cambiando l'agoritmo in 
- controlla se c'è una appartenenza confermata nel comitato selezionato senza data di fine e con data di inizio precedente  al (oggi meno due anni).

Le riammissioni dopo aver ri-pagato la quota andrebbero segnate come nuove appartenenze.

**Comment by matthewmazzoleni** [comment]
Tecnicamente la riammissione è possibile non in senso "ho sbagliato", ma è la riammissione in associazione prevista dalla normativa nazionale. In questo caso, come indica la normativa, l'Anzianita è perduta. una dimissione errata va sistemata dal supporto, non può un presidente pensare di riammettere il socio e magicamente tutto torna ok.. È questo il caso?

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra, ci tengo a precisare che Gaia attualmente e' in grado di estrarre anche le anagrafiche con appartenenze "spezzate". Questo e' per esempio il caso dei volontari che si trasferiscono. Anche facendo 100 trasferimenti nello stesso anno, fino a che il volontario ha due anni di appartenenze, questo viene estratto.

La dimissione, come dice correttamente @matthewmazzoleni, "riavvia il contatore degli anni di anzianita'". Tecnicamente, la dimissione effettua tre azioni:
1. Termine anticipato dell'appartenenza (fine=ora)
2. Creazione pratica di dimissione
3. Imposta motivo terminazione appartenenza (terminazione=dimissione)

Al fine di ripristinare il funzionamento dell'elenco nel caso di dimissione accidentale, e' quindi necessario:
1. Togliere la fine all'appartenenza
2. Rimuovere la proprietà `terminazione=DIMISSIONE` dall'appartenenza
3. Rimuovere la pratica di dimissione

Nel tuo caso particolare, credo sia ancora necessario fare **(2)**.

**Comment by alfiomusmarra** [comment]
@matthewmazzoleni : sì, so che la dimissione "ho sbagliato" non dovrebbe esistere (e infatti ho già segnalato l'errore procedurale rispondendo al ticket). Volevo solo indicare un sistema per evitare che questi errori, che non dovrebbero esistere eppure esistono, inficino la creazione degli elenchi. In questo caso sarebbe utile avere un controllo su "appartenenze sovrapposte" che impedisca di crearne una nuova se si sovrappone ad una attuale o passata, costringendo il presidente a correggere dati errati piuttosto che chiudere a casaccio e riaprirne una nuova.

@AlfioEmanueleFresta: benissimo la gestione delle appartenenze spezzate, quello che volevo dire è che la presenza di una appartenenza aperta, confermata e superiore a due anni dovrebbe essere controllata prima della presenza di dimissioni, evitando così quel tipo di errore.

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra il sistema attuale e' studiato a puntino partendo dalla base dati che abbiamo e permette di generare l'elenco elettorato "unendo" le varie appartenenze anche ove ci sia un baco di qualche giorno. In sede di progettazione, questa mi sembrava l'unica alternativa per fare tutti i controlli in una singola query SQL. Quanto scrivi non mi sembra altrettanto fattibile, e promuoverebbe il mantenimento di una banca dati sporca (una dimissione "errata" va annullata, non va fatta la riammissione).

**Comment by alfiomusmarra** [comment]
@AlfioEmanueleFresta mi permetto di non essere daccordo. 

Per quanto riguarda la questione "banca dati sporca": al momento in fase di scrittura, nessuno impedisce al presidente di scrivere corbellerie. Il sistema non controlla prima di scrivere se l'appartenenza si sovrappone in parte o in tutto a una appartenenza esistente, aperta o chiusa. Questo, e non una normativa, impedirebbe fattivamente al presidente pigro di aprire una nuova appartenenza anziché richiedere l'annullamento di una dimissione errata. 
Riassumento, già adesso il db può essere sporcato, io proponevo solo un diverso ordine di lettura che lascia il db come è, né migliore né peggiore.

Per quanto riguarda la questione "gestione delle anzianità, dei buchi e dei trasferimenti", avrei una mia opinione che però ha due difetti: 
a) esula dalla questione di questo issue
b) forse richiede più sforzo ad essere implementata dei benefici che porterebbe in materia di gestione dei dati.
