### ISSUE TITLE
Volontario assente in rubrica

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#138]
Volontario id 59090, associato all'unità territoriale 765 del comitato 764, non compare in rubrica del suo presidente nonostante in privacy sia segnato "mostra ai responsabili del comitato"

**Comment by alfiomusmarra** [comment]
Credo che la scelta della privacy "mostra ai membri/responsabili" della mia Sede CRI vada inteso almeno nel senso del comitato, e non dell'unità territoriale. 

Inoltre detta limitazione semplicemente non dovrebbe esistere per presidente e u.s. che dovrebbero vedere una rubrica completa di comitato a prescindere dalla scelta privacy personale.

**Comment by AlfioEmanueleFresta** [comment]
La rubrica e' uno strumento per i volontari, e fa parte della sezione "Volontario".

Dal pannello "Soci" invece, presidente e US possono vedere tutti i volontari e tutti i contatti, indipendentemente dalle impostazioni della privacy dei volontari.
