### ISSUE TITLE
[Trasferimento] Traferimento negato dal sistema

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#139]
Il volontario #7783 con appartenenza attuale al comitato #525 tenta trasferimento a comitato #543 che gli viene negato dal sistema con messaggio:

"Appartieni già a quella sede"

N.B. - Il comitato #525 è un ex proviciale
N.B. 2 - Il volontario ha una estensione conclusa verso il comitato #543

**Comment by yakky** [comment]
@alfiomusmarra @PaoloGiustiniani ho provato a riprodurlo con dei dati che rispettano i criteri indicati senza successo. E' ancora valido o è risolto?

**Comment by yakky** [comment]
@CroceRossaItaliana/supporto direi che è lo stesso problema di #217

**Comment by PaoloGiustiniani** [comment]
Confermo. Chiudo.
