### ISSUE TITLE
[estensione] Controllo su estensione già in atto

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#140]
Come da oggetto, il sistema non impedisce di aprire una estensione mentre ce n'è una identica già in atto (vedi allegato per l'effetto sull'elenco appartenenze)

Inoltre, a quanto pare vedendo la situazione del volontario #43084, mentre l'estensione attivata dal volontario ha come orario di termine un minuto dopo l'orario di avvio, quando l'estensione viene attivata dal presidente ha come termine le ore 00.00 del giorno finale. (Anche qui, vedi allegato)
![screenshot - 07022016 - 14 27 56](https://cloud.githubusercontent.com/assets/3878935/12872586/3f3a8108-cda7-11e5-9d38-bcb4d6d140e0.png)

![screenshot - 07022016 - 14 17 23](https://cloud.githubusercontent.com/assets/3878935/12872549/56f3d8fe-cda6-11e5-91fa-888cd12a9ba7.png)

**Comment by matthewmazzoleni** [comment]
up

**Comment by AngeloLupo** [comment]
Ho controllato questo caso e anche il caso riportato nell'issue #164 ed entrambe sembrano risolte, probabilmente in seguito ai cambiamenti al modo in cui gaia prende le estensioni attuali dei volontari.
