### ISSUE TITLE
[corsi base] mittente e-mail di attivazione

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#141]
Mi sono reso conto che le e-mail di attivazione dei corsi hanno un alto numero di risposte, che finiscono ad aprire ticket al supporto.

Mi chiedo se sia piu' opportuno impostare un "rispondi a" al direttore del corso che effettua l'attivazione. Attualmente questo non e' fattibile semplicemente perche' il mittente si vedrebbe centinaia, se non migliaia di messaggi nella posta in uscita, quindi e' da implementare prima la possibilita' di avere un solo `Reply-to`.

RFC @CroceRossaItaliana/supporto

**Comment by AlfioEmanueleFresta** [comment]
(Mi correggo, il mittente non si troverebbe un milione di messaggi ma solo uno con piu' destinatari, il fatto e' che il direttore del corso non ha il diritto di accesso ai dati degli aspiranti in zona fino a che questi non chiedono informazioni -rispondendo- o fanno richiesta).

Questo potrebbe inoltre aumentare significativamente in turnaround di aspiranti.

**Comment by alfiomusmarra** [comment]
Il reply-to alla mail del direttore del corso è la soluzione ideale a mio avviso. Chi scrive volontariamente dà implicita autorizzazione.

In ogni caso, è da evitare che ogni click di risposta apra un ticket.
