### ISSUE TITLE
Procedura di auto-sospensione utenti

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#142]
Bisognerebbe sviluppare una funzionalità che consenta di rimuovere le casella email inesistenti associate a determinati utenti.

La richiesta nasce dal fatto di prevenire eventuali inserimenti in blacklist dei server smtp.

La procedura dovrà compiere le seguenti operazioni:
1) Operatore inserisce la lista delle caselle
2) Gaia rimuovere la casella email dal profilo dell'utente 
3) Gaia registra nei log (data ed ora) che la casella è stata rimossa per il motivo di cui sopra
4) Gaia invia una mail all'ufficio soci / presidente informandoli dell'accaduto
5) Nel profilo dell'utente (visionabile dall'ufficio soci) stampiamo quanto al punto tre

Attualmente superiamo i 550 utenti (ultime 24 ore).

**Comment by PaoloGiustiniani** [comment]
@CroceRossaItaliana/sviluppo Bisognerebbe rivedere con urgenza la priorità di questa issue, in quanto, quotidianamente veniamo listati per problemi di questo tipo.

**Comment by AlfioEmanueleFresta** [comment]
Ho fatto un po' di progresso su questo strumento. Alcune note:

* Nel caso l'e-mail sia associata a una utenza (credenziali di accesso), elimina l'utenza. Istruzioni inviate all'US su come abilitare nuovamente credenziali.
* Nel caso l'e-mail sia solo un indirizzo di contatto, questo viene cancellato dalla scheda. L'US viene notificato dell'operazione.
* In entrambi i casi, viene annotata l'operazione nel campo note. 
* Viene inoltre registrata la modifica nel Log di sistema.

**Comment by PaoloGiustiniani** [comment]
Ottimo

**Comment by PaoloGiustiniani** [comment]
Quando puoi mandarla in produzione?

**Comment by PaoloGiustiniani** [comment]
Il tool funziona bene.

Vista l'enorme quantità di email inoltrate verso alcuni comitati aventi moltissimi volontari con email sbagliate, da più punti è giunta la richiesta di inoltrare un report giornaliero.

Ovvero l'attuale procedura inoltra tutto in una coda ed un cron giornaliero invia la notifiche (in un mail unica) nel caso in cui vi siano occorrenze.

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani - mi sembra di capire che hai gia' effettuato la pulizia sugli indirizzi segnalati fino ad ora.

Sicche' tale strumento richiede parecchie risorse di sviluppo, e che la quantita' di nuovi indirizzi errati non crescera' piu' rapidamente del numero di nuovi utenti al giorno, a tuo giudizio ne vale la pena?

**Comment by PaoloGiustiniani** [comment]
@AlfioEmanueleFresta concordo con te, convolgo @galamarco per un ulteriore parere.

Premesso che sono sicuramente a favore di una coda che consenta l'inoltro di una sola mail giornaliera d'altro canto non vorrei sottrarre tempo allo sviluppo di nuove funzionalità.

Sicuramente la prima "ondata" ha visto numerose sospensioni, in quanto non erano mai state fatte prima.

Ieri abbiamo superato le 2000 notifiche, oggi 70.

Diciamo che il "grosso" è passato.

**Comment by galamarco** [comment]
Noi abbiamo avvisato (ieri) i DTR Sviluppo e i Comitati Regionali dell'operazione in corso, di certo però ricevere 50 mail distinte non fa percepire GAIA in maniera amichevole ai Presidenti (che domani cambiano con i loro uffici soci) e non mi sorprendono le lamentele a riguardo...

**Comment by PaoloGiustiniani** [comment]
Parlando con @galamarco abbiamo analizzato la casistica.

E' bene istituire una coda di invio email (con report giornaliero, differente per ogni topologia) che possa includere eventuali azioni intraprese.

Questo anche in vista della formazione che vedrà numerose richieste di partecipazione.

Il tutto corredato da #206 migliorerà il tutto.

**Comment by galamarco** [comment]
@AlfioEmanueleFresta, parlando con @PaoloGiustiniani  credo che il concetto di "accorpare le mail" sia utile in futuro.
Immagina quando ogni dieci minuti un volontario si iscrive ad un corso, o a un evento disponibile: non possiamo mandare una mail al presidente ogni dieci minuti, meglio una a fine giornata riepilogativa.
Non mi sembra urgente questa cosa, ma pro futuro è comunque da concepire perchè servirà in altri contesti, anche per ottimizzare le mail inviate.

**Comment by AlfioEmanueleFresta** [comment]
Ne prendo atto. Sarebbe praticabile specie considerando che abbiamo il nuovo sistema unico di gestione delle autorizzazioni, accorpare quindi le autorizzazioni/richieste per lo stesso oggetto (es. richieste di partecipazione attivita, richieste corsi base, ecc.). Mandare anche dei report giornalieri ai presidenti che decidono cosi', es. "Hai 15 richieste in attesa".

Per ora chiudo in quanto non negli obiettivi a breve termine.
