### ISSUE TITLE
attività: turni duplicati in calendario

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#143]
All'interno del calendario stanno iniziando a comparire turni duplicati. es: ID turno 65040 compare due volte, come da immagine allegata.

![screenshot-122](https://cloud.githubusercontent.com/assets/3315913/12893114/a52004a0-ce8f-11e5-90d1-9f42c2f623ca.png)

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex ho verificato il tuo caso specifico e sono due turni separati, con ID diversi.
