### ISSUE TITLE
[data inizio appartenenza] mancato controllo

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#145]
L'ufficio soci, al momento della dimissione di un volontario, giunge ad una schermata in cui può ancora modificare la data di inizio appartenenza. In questo contesto, è possibile modificare la data di inzio con una data successiva a quella di fine.

**Comment by yakky** [comment]
@alfiomusmarra non mi risulta più possibile impostare una data per le dimnissioni

**Comment by luca-dex** [comment]
@yakky confermo e chiudo

**Comment by AlfioEmanueleFresta** [comment]
Indipendentemente dal problema relativo alla dimissione, e' comunque ancora vero quanto segnalato sulle date, come in #413.

**Comment by yakky** [comment]
@AlfioEmanueleFresta terrei aperto #413 visto che questo fa esplicito riferimento alla dimisione
