### ISSUE TITLE
Visualizzazione Attività Calendario

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaItaliana/jorvik#146]
Nel calendario vengono visualizzate le attività del comitato che ha come vecchio ID, l'attuale del comitato genitore

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta non ho capito, puoi riformulare?

**Comment by biagiosaitta** [comment]
@AlfioEmanueleFresta  ti faccio un esempio pratico, nel comitato di fiumefreddo vedo un attività del comitato jonico, che è aperta solo ai volontari del comitato jonico. Credo che il problema sia il campo "vecchioid" del comitato jonico, ma non ne sono certo

**Comment by AlfioEmanueleFresta** [comment]
@biagiosaitta probabilmente si tratta di una attivita' creata precedentemente all'introduzione di Jorvik, e l'attivita' era stata aperta a tutta la regione. Trovi nelle attivita' il campo "estensione" che e' l'ID di una Sede, solo che se in quel caso si tratta di una sede provinciale, viene attualmente vista in tutta la provincia.

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta un utente Ligure vede un'attività del Trentino alto Adige. l'attività a cui mi riferisco è aperta esclusivamente ad una unità territoriale di un comitato locale. YXE-499-38990

**Comment by AlfioEmanueleFresta** [comment]
Rientra in #166.
