### ISSUE TITLE
iscrizione: segnalazione errore 

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#149]
giungono diverse segnalazioni di aspiranti che, durante l'iscrizione a GAIA, ottengono errore dopo aver compilato i dati

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni credo che il problema sia stato risolto con una modifica di tempo fa, non trovo negli ultimi 7 giorni nessun errore, ma il numero di aspiranti e' alto.

Se accade nuovamente, per favore riapri.
