### ISSUE TITLE
Cancellare attività

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#150]
Alcuni utenti chiedono l'attivazione della funzionalità "cancella attività", almeno nel caso in cui non ci siano occorrenze di turni e di iscritti.

**Comment by biagiosaitta** [comment]
aggiungerei anche la possibilità di cancellare un turno

**Comment by AlfioEmanueleFresta** [comment]
Ora possibile entrambi.
