### ISSUE TITLE
quote: generazione elenco genera errore 500

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#153]
91211 genera elenco quote e riceve errore 500. testato in produzione.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni non riesco a riprodurre. Ci sono dei doppioni negli elenchi (altro issue), ma riesco a generare tutto correttamente.

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta altro esempio, provato anch'esso dal sottoscritto in produzione: ERC-870-25903

**Comment by AlfioEmanueleFresta** [comment]
OK grazie - il problema riguarda quindi la generazione degli excel. Indago.
