### ISSUE TITLE
quote: problemi con ricevute

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#155]
5033 segnala che:

1) la scritta cri del comitato e il logo cri sono uno sopra all'altro
2) In fondo alla ricevuta, dove sono riportati i dati del comitato non viene riportato il Codice Fiscale.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo questa e' ad alta priorita', riesci a sistemarlo in giornata? Per favore, se non puoi, dai feedback.
