### ISSUE TITLE
[admin] Ricerca per id

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#156]
Attualmente non è possibile effettuare un filtro per ID ANAGRAFICA nei pannelli di amministrazione di persone, utenze, deleghe.

**Comment by AlfioEmanueleFresta** [comment]
Idealmente puoi ottenere la persona `123` aggiungendo `123/` alla pagina di ricerca persone. Ad esempio:

`admin/anagrafica/persona/` = elenco persone
`admin/anagrafica/persona/123/` = persona 123

Il motivo principale per cui non e' abilitata la ricerca per ID persona negli altri campi, e' che si dovrebbe comunque passare dalla ricerca persona per conoscere il codice fiscale della persona. Infatti, conoscendo solo l'ID della persona `123`, e cercando `123` in utenze, si avrebbero due risultati: persona con ID 123 e persona *con utenza* con ID 123.

Per permettere di poter accedere alle entita' correlate con facilita' quindi, e' possibile avere gli `Inline`. Ad esempio questo e' come sono visibili ora nel pannello di amministrazione sia le appartenneze, che le deleghe, che le utenze per ogni persona, direttamente nella pagina di modifica della persona.

Se in @CroceRossaItaliana/supporto ritenete opportuno aggiungere alla scheda persona altre entita' correlate, vi prego di aprire un issue come nuova feature e provvederemo ASAP!

**Comment by alfiomusmarra** [comment]
Sì, lo ritengo opportuno e ne chiedo l'implementazione. Grazie

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra cosa? Puoi accedere alle deleghe di una persona, nonché le appartenenze, documenti e utenza direttamente dal pannello di modifica della persona, senza bisogno di ricercare in ognuno dei relativi pannelli. Alla scheda puoi accedere con id come sopra

**Comment by alfiomusmarra** [comment]
Sono stato poco chiaro perché avevo letto di fretta la tua risposta. Preferisco che la ricerca sia attiva sia sull'id persona e id utenza (al massimo due risultati) piuttosto che inserire manualmente nell'url l'id.
