### ISSUE TITLE
[aggiungi persona] campi obbligatori

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#158]
Attualmente quando un admin si trova ad aggiungere una persona il sistema richiede obbligatoriamente campi come indirizzo, comune, provincia e cap di residenza. Sarebbe il caso di rimuovere il vincolo.

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra abbiamo deciso di avere questi campi come obbligatori nel caso di inserimento da US, e anche nel caso di import di massa. 

In quale scenario vogliamo permettere l'inserimento da admin di una scheda anagrafica incompleta?

**Comment by alfiomusmarra** [comment]
Era il caso di un neo nominato presidente non ancora iscritto su gaia appartenente a un comitato non ancora inserito su gaia. Nei dati che chiediamo "di default" per la nomina non sono presenti quelli relativi alla residenza. Caso sempre più raro, si spera, ma ancora presente.

**Comment by AlfioEmanueleFresta** [comment]
@CroceRossaItaliana/sviluppo possiamo aggiungere i dati di residenza al modello di richiesta?

Perche' la vedo difficile che, una volta inserita la persona, l'ufficio soci o il presidente vada a modificare immediatamente la propria anagrafica.
