### ISSUE TITLE
Dimissioni: Socio Deceduto

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#16]
segnalo l'impossibilità di dimettere un socio deceduto, in quanto risulta obbligatorio flaggare la voce "trasforma in socio sostenitore", cosa non fattibile per un volontario deceduto.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo chiuso?

**Comment by AngeloLupo** [comment]
Si.
fix #16
