### ISSUE TITLE
[mobile] Visualizzazione nascosta per "mostra navigazione"

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#160]
Ci segnalano che con chrome su lg g3, nella scheda richieste una doppia riga grigia impedisce di "tappare" la voce "mostra navigazione" che quindi non può essere attivata. Non ho modo di verificare con quel particolare dispositivo.

**Comment by AlfioEmanueleFresta** [comment]
Thanks. Duplicato #23.

**Comment by alfiomusmarra** [comment]
Sicuramente il problema a monte è lo stesso, ma qui non si parla di "difficilmente utilizzabile", ma proprio impossibile da cliccare. Comunque, linko l'issue #23 all'utente.

**Comment by AlfioEmanueleFresta** [comment]
Si, ho aggiornato l'issue di conseguenza.
