### ISSUE TITLE
estensioni: impossibile estendere volontario per estensione già attiva

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#164]
risulta che 15415 non sia estendibile. Il Presidente che lo vuole estendere riceve errore "Il volontario ha già una richiesta di estensione a questa sede". il Volontario non ha attualmente alcuna estensione, quindi non è comprensibile la motivazione dell'errore.

ticket: DVW-287-25915

**Comment by AngeloLupo** [comment]
Ho controllato questo caso e anche il caso riportato nell'issue #140 ed entrambe sembrano risolte, probabilmente in seguito ai cambiamenti al modo in cui gaia prende le estensioni attuali dei volontari.

**Comment by matthewmazzoleni** [comment]
il problema non è risolto

rif: DVW-287-25915

**Comment by matthewmazzoleni** [comment]
in caso si serva abbiamo un caso qui: persona/6821/ verso Vicenza
