### ISSUE TITLE
aspiranti: riassociazione a corso genera errore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#169]
quando un'aspirante viene negato ad un corso e vi si riassocia lato comitato la sua accettazione genera errore 404

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni l'errore 404 viene lanciato quando si cerca di accettare una richiesta che e' stata gia' processata. Non riesco a riprodurre errore sopra.
