### ISSUE TITLE
quote: problematiche quote pagate

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#170]
- delegato US di sede territoriale può registrare quota ma se apre la ricevuta riceve accesso negato
- il medesimo delegato US, interrogando la vista "elenco ricevute", riceve "nessuna ricevuta per.." nonostante siano presenti ricevute relative alla sede di competenza (le ha registrate lui)

**Comment by AlfioEmanueleFresta** [comment]
@CroceRossaItaliana/supporto risolto, ack
