### ISSUE TITLE
admin: errore server 500

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#171]
aprendo la pagina admin/anagrafica/trasferimento/?q=XXXXXXXXX ottengo server error 500

**Comment by AngeloLupo** [comment]
Dovresti togliere il "?q=". Se l'errore e' generato dopo aver cliccato su un link mi sai dire da quale pagina lo hai aperto?

**Comment by matthewmazzoleni** [comment]
apri https://gaia.cri.it/admin/anagrafica/trasferimento/
inserisci la stringa di ricerca
premi cerca
