### ISSUE TITLE
feature: nomina rapida presidente per elezioni 2016

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#172]
come da accordi è necessario implementare quanto in oggetto secondo gli accordi intercorsi.

**Comment by AlfioEmanueleFresta** [comment]
Lo strumento e' pronto. Come da indicazione di @matthewmazzoleni, aspettiamo il testo da @galamarco per l'e-mail da inviare ai nuovi presidenti, invece che l'attuale e-mail standard di nomina:

![image](https://cloud.githubusercontent.com/assets/621062/13374396/a9f2ad0c-dd7b-11e5-9e32-6a59981772e9.png)

**Comment by AlfioEmanueleFresta** [comment]
Anteprima dello strumento.

![image](https://cloud.githubusercontent.com/assets/621062/13374405/dc2695ae-dd7b-11e5-9c61-7c864588f049.png)

**Comment by AlfioEmanueleFresta** [comment]
**E-mail check-list nuovo Presidente**

<img width="596" alt="screen shot 2016-02-27 at 21 24 16" src="https://cloud.githubusercontent.com/assets/621062/13375546/98371b2e-dd9a-11e5-8dd0-3308b02a7b2d.png">

--

**Check-list nuovo Presidente**

<img width="876" alt="screen shot 2016-02-27 at 21 27 18" src="https://cloud.githubusercontent.com/assets/621062/13375552/aad6216c-dd9a-11e5-9e1f-92175a78b7f6.png">

--

**Avviso check-list nuovo Presidente**

<img width="791" alt="screen shot 2016-02-27 at 21 31 08" src="https://cloud.githubusercontent.com/assets/621062/13375554/b3690498-dd9a-11e5-8ef4-b676312498cb.png">

--

**Check-list in pagina Sedi**
<img width="879" alt="screen shot 2016-02-27 at 21 33 50" src="https://cloud.githubusercontent.com/assets/621062/13375557/c25328f8-dd9a-11e5-89a0-3f7e58a13b4f.png">

**Comment by AlfioEmanueleFresta** [comment]
@galamarco richiede l'inserimento in check-list del dover completare tutti i dati del Comitato.

**Comment by AlfioEmanueleFresta** [comment]
@galamarco @CroceRossaItaliana/supporto 

<img width="1071" alt="screen shot 2016-02-28 at 12 41 40" src="https://cloud.githubusercontent.com/assets/621062/13379254/a996d598-de18-11e5-98f2-fbdf151cb6f6.png">

<img width="874" alt="screen shot 2016-02-28 at 12 41 19" src="https://cloud.githubusercontent.com/assets/621062/13379255/adb5a8d4-de18-11e5-9f5f-b40c3b459edf.png">

<img width="872" alt="screen shot 2016-02-28 at 12 40 48" src="https://cloud.githubusercontent.com/assets/621062/13379257/b35f0cb2-de18-11e5-9970-188dd082e245.png">

**Comment by galamarco** [comment]
@AlfioEmanueleFresta assicurati che i dati richiesti al presidente permettano poi di esportare questo excel con tutti i campi richiesti, a occhio mi pare manchi qualcosa ma probabilmente la schermata prosegue oltre al print
[Matrice_Comitati_23_02_16.xlsx](https://github.com/CroceRossaItaliana/jorvik/files/150098/Matrice_Comitati_23_02_16.xlsx)

**Comment by AlfioEmanueleFresta** [comment]
@galamarco grazie per la risposta,
- Tutte le componenti dell'indirizzo vengono ottenute dalla locazione geografica, quindi le abbiamo;
- Del resto mi sembra mancare solo l'URL del sito web, che aggiungo (opzionale) entro sta sera, grazie per avermelo fatto notare,
- Tutte le nuove nomine saranno Presidente, quindi estrarremo con denominazione "Presidente CRI" (brrrrrr "C.R.I."),
- Assumo che `testoextra` e `titoloextra` siamo rimasugli di qualche vecchia esportazione, quindi li ignoro.

**Comment by AlfioEmanueleFresta** [comment]
@galamarco confermo l'aggiunta del sito web tra i cambi richiesti, con validazione del formato corretto per l'URL.

**Comment by galamarco** [comment]
Non sono rimasugli ma i campi che generano l'elenco delle unità territoriali collegate al comitato. (suppongo che siano dati già esistenti)
Ad esempio in questo caso: http://www.cri.it/sicilia/dovetrovarci/catania

**Comment by AlfioEmanueleFresta** [comment]
Azz, office per mac mi mostrava solo la prima riga, mi sembrava solo un rimasuglio di HTML. 

Noto pero' che il formato di visualizzazione e' inconsistente, vedi http://www.cri.it/flex/FixedPages/IT/DoveTrovarciGenerale.php/L/IT/ID/3/STP/3/IDC1/7/IDC2/11, dove non sono visualizzate per niente le sedi territoriali distaccate. Lo generiamo per tutte le sedi territoriali, comunque? Anche, ad esempio, per quelle senza indirizzo e-mail.

**Comment by AlfioEmanueleFresta** [comment]
@galamarco aggiungo, va bene sostituire `le nostre sedi locali` con `le nostre unità territoriali`?

**Comment by galamarco** [comment]
Attenzione @AlfioEmanueleFresta non ti basare sul "dove trovarci" di cri.it ma su quello di cri.it/sicilia (simile ma non uguale), si sta rifacendo tutto e quello dell'imminente versione è come quello di cri.it/sicilia
Detto ciò, entrambe ("le nostre sedi locali" e "le nostre unità territoriali") non esistono e prima o poi saranno da rimuovere ovunque, quindi scrivilo come preferisci, per me non fa differenza
