### ISSUE TITLE
quote: visibile ricevuta di un volontario di altra sede

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#173]
US Della Spezia vede nell'elenco quote la persona 58414, avente:

![image](https://cloud.githubusercontent.com/assets/5826472/13302203/058a6766-db49-11e5-953f-3e7a84eb9dd4.png)

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni l'elenco quote pagate 2014 mostra i volontari:
1. Appartenenti al Comitato nel 2014, quindi passibili al pagamento di quota socio durante l'anno,
2. Che non sono classificati non-paganti, ovvero che hanno pagato la quota associativa dell'anno.

Questo funzionamento permette la corretta classificazione delle persone che, ad esempio, sono trasferitesi in un Comitato durante la seconda parte dell'anno, ma avevano pagato la quota nel Comitato di provenienza. Essendo la quota associativa gia' pagata, non dovranno comparire tra i non paganti.

Il permesso sulla quota associativa deriva dal fatto che il Comitato attuale ha accesso alla "cartella personale del Volontario", che la contiene.
