### ISSUE TITLE
trasferimenti: ripristinare funzionalita' trasferimenti

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#177]
Come concordato, le funzionalita' dei trasferimenti devono essere correttamente ripristinate in seguito alle elezioni.

**Comment by alfiomusmarra** [comment]
Non tutte le elezioni sono finite.

2016-03-01 13:45 GMT+01:00 Alfio Emanuele <notifications@github.com>:

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra hai ragione, intendo predisporre il software per l'attivazione, piuttosto che attivare. Non mi risulta che ci sia ancora del codice pronto da mandare in produzione a breve per i trasferimenti.

**Comment by AngeloLupo** [comment]
https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/viste.py#L637

Bisogna togliere il true da questo if

**Comment by AlfioEmanueleFresta** [comment]
In realta' bisognerebbe togliere del tutto la condizione.

Idealmente, come per l'apertura e la chiusura dei trasferimenti, questo dovrebbe essere effettuabile da amministratore senza necessita' di modificare il codice. Magari con l'inserimento di una entita' "Elezione" con inizio e fine (`ConStorico`) dalla quale diventa facile determinare l'esistenza di elezioni in corso (`if Elezione.objects.query_attuale().exists()` o qualcosa del genere)?

Inoltre ora c'e' il problema che i Comitati non vanno ad elezione nello stesso giorno (con gli ex-provinciali ritardati di una settimana), ma anche un sistema semplice globale andrebbe bene.

**Comment by alfiomusmarra** [comment]
Inoltre, a regime, saranno sempre possibili elezioni sfalsate (morte,
dimissioni di presidenti o fine commissariamenti). Se leggo bene il
regolamento, non è il trasferimento ad essere bloccato, ma viene freezata
la lista degli aventi diritto al voto. Questa condizione dunque, appartiene
più a "produci lista elettorato" che a "trasferimenti".
Il 01/mar/2016 14:07, "Alfio Emanuele" <notifications@github.com> ha
scritto:

**Comment by AlfioEmanueleFresta** [comment]
@alfiomusmarra grazie per l'analisi del regolamento che hai fatto e il suggerimento. Concordo con te, sul dover spostare il paradigma e introdurre questa modifica negli elenchi elettorali.

Allo stesso tempo pero' non vedo questo fattibile nel breve termine, ed e' fuori dallo scopo di questo issue, quindi ti chiedo di aprire un nuovo issue come richiesta di implementazione.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo **dobbiamo** testare e riattivare questa funzionalita' lunedi'.
