### ISSUE TITLE
Scheda: mancata visualizzazione campo email direttamente in scheda

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#18]
come da oggetto, mostrare campo email

**Comment by AlfioEmanueleFresta** [comment]
Il campo e' in "credenziali", ma:
- [ ] preparero' uno script di aggiornamento che clona l'indirizzo e-mail di accesso nel campo "e-mail di contatto",
- [ ] all'iscrizione il campo verra' automaticamente popolato
