### ISSUE TITLE
Automatismo accettazione trasferimenti

### ISSUE THREAD

**Issue by Desiosoci** [CroceRossaItaliana/jorvik#181]
Buongiorno,  mi trovo con alcuni volontari che hanno chiesto il trasferimento ad altre sedi senza che l-ufficio abbia potuto vedere nulla, mentre al volontario risulta gia tutto confermato (mi ha inviato screen della conferma).
Possibile un errore?

**Comment by AlfioEmanueleFresta** [comment]
Ciao @Desiosoci, per favore passa dal canale di supporto per le segnalazioni (https://gaia.cri.it/supporto/). Il personale sara' in grado di analizzare la tua richiesta e verificare la situazione, controllare quali autorizzazioni sono state concesse per il trasferimento ed, eventualmente, aprire una segnalazione di bug per te qui (raccogliendo tutti i dati necessari a noi sviluppatori del caso). 

Questo strumento e' inteso solamente per il personale di sviluppo e di supporto.

**Comment by Desiosoci** [comment]
Non vorrei essere insistente ma a me è stato dato il ink del sito proprio dal supporto di cui vi allego la risposta.________________________________________________________________________________________________


-----Original Message-----
From: Progetto GAIA - Informazioni <info@gaia.cri.it>
To: cl.desio.sociale@lombardia.cri.it
Date: Tue, 23 Feb 2016 09:30:00 +0100
Subject: [#YTQ-352-20801]: (LIV3) dati errati

Gentile Elena,
può seguire qui l'iter di sistemazione della problematica.

La informo inoltre che ha inserito erroneamente la sua mail, ha scritto @lombardis.cri.it

https://github.com/CroceRossaItaliana/jorvik/issues/85 

Saluti,

Matthew Mazzoleni
Centro di Supporto - Progetto G.A.I.A
3° livello 

Cronologia TicketElena Mascheroni (Cliente) Pubblicato Il: 19 febbraio 2016 08:17
la presente per segnalarVi alcune anomalie riscontrate su Gaia: 1) Volontaria Savarese Cristina appartenente al Comitato Locale di Desio, già estesa al Comitato Locale di Trento Dimaro, chiede anche Estensione al Comitato Locale di Monza e la Richiesta fatta su Gaia risulta intestata al Comitato di Trento Dimaro, anzichè al nostro Comitato di Desio. 2) Volontario Pinto Marco appartenente al Comitato Locale di Desio, già esteso al Comitato Provinciale di Milano chiede anche Estensione al Comitato Locale di Nova MIlanese e la Richiesta fatta su Gaia risulta intestata al Comitato Provinciale di Milano , anzichè al nostro Comitato di Desio. 3) Volontaria Rasà Emma chiede su Gaia interruzione del Ruolo di Riserva.. a noi non perviene nulla, ma a lei risulta da noi confermato. Attendo un Vostro gradito e sollecito riscontro in merito.Informazioni tecniche associate:
ID=7729
Nome=Elena Mascheroni
Admin={Persona, Utenza} Deleghe (7) = - Delegato Centrale Operativa per Comitato Locale Di Desio - Delegato Centrale Operativa per Comitato Locale Di Desio - Presidente per Comitato Locale Di Desio - Delegato d'Area per Comitato Locale Di Desio, Ob. 2: Generale - Delegato d'Area per Comitato Locale Di Desio, Ob. 5: Giovani - Referente Attività per DISTRIBUZIONE VIVERI AGEA - Referente Gruppo per Gruppo DISTRIBUZIONE VIVERI AGEAClicca qui per entrare su Gaia — https://gaia.cri.it
Se hai bisogno di aiuto, sentiti libero di rispondere a questa email.
Segui il progetto Gaia su Facebook per conoscere sempre le ultime novità!

Rispetta l'ambiente, non stampare questa email se non è necessario.

Informativa sulla Privacy - come previsto dal D. Lgs n. 196/2003
Si precisa che le informazioni contenute in questo messaggio sono riservate e ad uso esclusivo del destinatario.
Qualora questo messaggio Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione.
Grazie per la collaborazione.

Croce Rossa Italiana. Un'Italia che aiuta. 
 Dettagli Ticket
ID Ticket: YTQ-352-20801
Dipartimento: Gaia - 2° livello
Tipo: Richiesta
Stato: Chiuso
Priorità: Bassa

Helpdesk: https://helpdesk.cri.it/index.php?/Gaia
_____________________________________________________________________________________
Ufficio Soci 
Croce Rossa Italiana
Comitato Locale di Desio

Da: "Alfio Emanuele" notifications@github.com
A: "CroceRossaItaliana/jorvik" jorvik@noreply.github.com
Cc: "Desiosoci" soci@cridesio.it
Data: Wed, 02 Mar 2016 03:27:24 -0800
Oggetto: Re: [jorvik] Automatismo accettazione trasferimenti (#181)


Ciao @Desiosoci, per favore passa dal canale di supporto per le segnalazioni (https://gaia.cri.it/supporto/). Il personale sara' in grado di analizzare la tua richiesta e verificare la situazione, controllare quali autorizzazioni sono state concesse per il trasferimento ed, eventualmente, aprire una segnalazione di bug per te qui (raccogliendo tutti i dati necessari a noi sviluppatori del caso). 

Questo strumento e' inteso solamente per il personale di sviluppo e di supporto.

**Comment by AlfioEmanueleFresta** [comment]
@Desiosoci, il link e' relativo ad una segnalazione gia' aperta da un membro del supporto ed in carico ad uno sviluppatore, non c'e' quindi motivo di aprire una nuova segnalazione tecnica.

Per favore abbi pazienza, ti assicuro che lavoriamo alle segnalazioni in carico per risolverle nel minor tempo possibile, alla luce della loro priorita'.

Buona giornata
