### ISSUE TITLE
aspiranti: iscrizione senza essere sostenitore

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#193]
è necessario prevedere che Direttore Corso / Formazione possano iscrivere una generica persona ad un corso.

**Comment by AlfioEmanueleFresta** [comment]
## Problema

Come vogliamo affrontare la cosa? La mia preoccupazione principale riguarda il mantenere il seguente principio, che attualmente e' presente in Gaia:

> **Per ogni persona censita in Gaia, è sempre vera almeno una delle seguenti:
> a) La persona ha delle credenziali per accedere a Gaia, es. attraverso iscrizione autonoma come aspirante, o
> b) La persona ha una appartenenza come socio o sostenitore presso un Comitato, che ne puo' gestire la scheda anagrafica e attivarne le credenziali.**

Violare questo principio apre un enorme numero di situazioni che non abbiamo affrontato e che sicuramente non vogliamo affrontare. Ad esempio, la presenza di schede che non sono ne' modificabili dall'US ne' accessibili dall'utente. Questo, a sua volta, ha altre brutte conseguenze, come il rendere il personale di supporto l'unico amministratore e responsabile per la modifica dei dati del soggetto.

Il problema relativo agli aspiranti e' che, secondo nuove norme, questi non sono soggetti appartenenti al Comitato fino a che non finiscono il corso. Quindi non sono ne' sostenitori ne' soci, che sono i rapporti che rendono legittima la gestione della scheda anagrafica da parte del Comitato.

In un mondo ideale, dove ognuno ha accesso a internet e gli iscritti non si registrano in ritardo, potremmo risolvere il tutto semplicemente incoraggiando i Comitati a fare iscrivere gli aspiranti su Gaia in autonomia, o assisterli in Comitato per i meno capaci.

Il problema e' che questo ha, nella vita reale, i seguenti problemi:

1. C'e' un numero di persone che non e' in grado di registrarsi su Gaia, perche' poco istruita, istruita quando l'informatica non era nella scuola dell'obbligo, oppure senza accesso a internet per mancanza di un dispositivo o di una connessione (internet come diritto umano in Italia arrivera' sempre troppo tardi),

2. A corso iniziato non e' piu' possibile iscriversi in autonomia per gli aspiranti, ma nell'ottica ove l'iscrizione e' cartacea e viene meramente riportata sul gestionale informatico, non e' permesso alcun "ritardo di trascrizione".

## Possibili soluzioni

**Vedo tre possibili soluzioni, in ordine di mia personale preferenza:**

1. Mitigare gli effetti dei problemi (1) e (2), ad esempio permettendo all'ufficio soci di iscrivere al corso un aspirante iscrittosi in autonomia, anche dopo l'inizio dello stesso (es. "Reclama un Corsista") e suggerendo ai Comitati di portare un dispositivo per permettere l'iscrizione autonoma degli aspiranti,

2. Creare una nuova appartenenza come non-socio (es. "Corsista"), permettere la creazione della scheda all'US, assicurarsi la legittimita' legale della cosa, permettere l'associazione dei "Corsisti" ai corsi base, prevedere dei processi di passaggio della scheda tra i Comitati, prevedere dei processi di terminazione della appartenenza (es. alla fine del corso). Si apre la domanda: la appartenenza dovrebbe rimanere per sempre nel caso di esame fallito o corso abbandonato? Se no, non potendo rimuovere la scheda anagrafica, che ne si fa e la si da in amministrazione al personale di supporto?

3. Violare "il principio". Elaborare un elenco esaustivo di tutte le conseguenze e le rispettive diramazioni di tale violazione, nonche' progettare un numero adeguato di soluzioni e implementarle, per poi lavorare per permettere la registrazione di persone da ufficio che non hanno utenza ne' associazione al Comitato.


--------


@CroceRossaItaliana/supporto @CroceRossaItaliana/sviluppo @CroceRossaItaliana/testing @CroceRossaItaliana/infrastruttura potete cortesemente darmi la vostra opinione in merito alle soluzioni esposte e/o proporne di nuove?

**Comment by biagiosaitta** [comment]
Io sono per la soluzione n. 1, al momento della consegna "a mano" della domanda di iscrizione, l'ufficio soci registra la persona e lo assegna al corso base.

**Comment by luca-dex** [comment]
Secondo quanto previsto dall'attuale statuto della Croce Rossa, al titolo III (soci), articolo 11, comma 5 viene definito che: 

I Soci sostenitori sono persone fisiche o giuridiche che versano un contributo economico a  sostegno dell’azione associativa. Essi entrano a far parte dell’Associazione con il versamento del contributo, stabilito a livello nazionale. **Fanno altresì parte della categoria dei Soci sostenitori anche coloro i quali frequentano il corso di formazione per diventare Soci volontari, le allieve Infermiere Volontarie della C.R.I. e/o chi dona il sangue a favore della Croce Rossa Italiana.**

Questo vuol dire che si dovrebbero andare a configurare tre possibili scenari:

1. Una persona si è registrata come aspirante a gaia e si è iscritta al corso base richiesto
2. Una persona si è registrata come aspirante ma non si è iscritta al corso e si presenta alla prima lezione, alla serta di presentazione o comunque presso la sede del comitato.
3. Una persona ha saputo del corso ma non si è registrata a gaia e quindi non esiste nessuna sua scheda anagrafica.

Le situazioni 1 e 3 si risolvono molto semplicemente:

1. Alla partenza del corso l'ufficio soci registra la quota come sostenitore della persona in questione che assume lo stato di sostenitore del Comitato nel quale sta svolgendo il corso

3. Alla partenza del corso l'ufficio soci registra la quota come sostenitore della persone, inserendo i suoi dati e generando la scheda anagrafica della persona, alla quale verranno fornite le credenziali di accesso.

Per due credo che la soluzione "reclama un corsista" possa essere la migliore. Magari inserendo il codice fiscale si può recuperare un'anagrafica di una persona registrata a gaia ma che non si è iscritta al corso in questione.

Al momento quello che succede quando si iscrive un aspirante è che compare un alert in cui verificare la condizione in cui si trova la persona:

![screenshot at 2016-05-05 19 00 56](https://cloud.githubusercontent.com/assets/3315913/15050411/ef7864fe-12f3-11e6-95df-4de6611ca3c9.png)

e dopo aver confermato quanto richiesto lo stato della persona rimane comunque quello di "non ha un ruolo":

![screenshot at 2016-05-05 19 01 51](https://cloud.githubusercontent.com/assets/3315913/15050422/fd826d88-12f3-11e6-8ebd-621e115c2169.png)

Quindi credo sia importante avere un meccanismo che permetta di registrare la quota da socio sostenitore per la persone che si è iscritta come aspirante.

Oltre a ciò il passaggio da sostenitore a volontario, al superamento del corso, al momento non è gestito in maniera del tutto corretta, in particolare la situazione che si configura è quella in cui le persone che risultano sostenitori del comitato acquisiscono sia lo stato di sostenitore, sia quello di volontario (cosa che non dovrebbe succedere). 

Ci sono poi situazioni, probabilmente dovute a bug della procedura che fanno si che si vengano a verificare cose di questo tipo (volontario ID: 209714)

![screenshot at 2016-05-04 19 01 09](https://cloud.githubusercontent.com/assets/3315913/15050511/91ef36ae-12f4-11e6-9828-93dc0f64eed4.png)

Posso fornire più dettagli in caso servisse.

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta dovremmo gestire questa cosa, abbiamo moltissime richieste e problematiche correlate alla non possibilità di censimento delle persone nei corsi (anche a corso appena iniziato)

**Comment by yakky** [comment]
@matthewmazzoleni  Questo sarebbe risolto con quanto emerso in #384, giusto?

**Comment by matthewmazzoleni** [comment]
@yakky riferito al mio commento direi di sì, lascio a @luca-dex e @AlfioEmanueleFresta eventuali considerazioni aggiuntive

**Comment by luca-dex** [comment]
Sì, confermo
