### ISSUE TITLE
reclamare persona, situazioni da verificare

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#194]
reclamo di persona 46617 come Volontario o Sostenitore:

- non ha terminato appartenenza precedente come Socio Ordinario al CR
- ha permesso di inserire data inizio appartenenza con anno 2014 (creando nel medesimo periodo di tempo due tipi di appartenenze attivi).

**Comment by AlfioEmanueleFresta** [comment]
- Non piu' possibile reclamare ordinari come appartenenti da prima dell'inizio della prima app.
- Chiude appartenenza come ordinario

@CroceRossaItaliana/supporto risolto, pregresso corretto.
