### ISSUE TITLE
[anagrafiche] formattazione 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#211]
La formattazione delle anagrafiche non sta più avvenendo come in passato, gli utenti sono liberi di scegliere tra maiuscole e minuscole e questo causa problemi nella visualizzazione e nella successiva stampa dei tesserini (esempio anagrafica 209169).

Le vecchie regole erano prima lettera maiuscola e le successive minuscole.

Bisognerebbe correggere il passato.

Inoltre, in caso di cognomi "non standard" alcune anagrafiche dopo l'apostrofo possono volere una lettera maiuscola o minuscola.

**Comment by yakky** [comment]
@AlfioEmanueleFresta il commit linkato sopra non è mai stato mergiato. E' necessaria una review?

**Comment by yakky** [comment]
@AlfioEmanueleFresta bump :)

**Comment by yakky** [comment]
@AlfioEmanueleFresta ri-bump

**Comment by PaoloGiustiniani** [comment]
@AlfioEmanueleFresta 👎

**Comment by AlfioEmanueleFresta** [comment]
Si. Chiaramente e' necessario riportare la migrazione su un nuovo script. Non ho idea del perche' non fosse stata mergiata. Credo che il fatto che la migrazione necessiti di anni (deve leggere e risalvare ogni singolo record) sia una delle ragioni. Il fatto che non so se TitleField gestisca bene il cognome apostrofato (D'Angelo) potrebbe essere un altro.

Idealmente si potrebbe modificare la migrazione usando una query SQL che apra e risalvi tutti i valori in anagrafica, ma solo dove `nome <> initcap(lower(nome)) OR cognome <> initcap(lower(cognome))`.

Chiaramente questo includera' dei casi che non devono essere modificati (es. prima lettera dopo apostrofo in maiuscolo) ma almeno potrebbe ridurre drasticamente il tempo necessario.

**Comment by yakky** [comment]
@AlfioEmanueleFresta @PaoloGiustiniani in realtà il problema era parzialmente risolto da #233. Ho aperto una PR per migliorare la gestione dei nomi con apostrofo

**Comment by yakky** [comment]
PR deployata su luke

**Comment by PaoloGiustiniani** [comment]
http://pr-550.sviluppo-gaia.ovh/
