### ISSUE TITLE
[anagrafica] email istituzioni associate ad anagrafiche 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#212]
In fase di nomina dei nuovi presidenti ho notato che molte anagrafiche hanno come casella di posta:

cl.*@cri.it
cp.*@cri.it
cr.*@cri.it

Questo è errato in quanto la casella è del comitato e non della singola persona.

Bisognerebbe:
1) Bloccare lato Gaia l'inserimento di future caselle con questa sintassi
2) Estrarre dal DB la lista di queste caselle per far si che il supporto possa contattarli e richiederne la modifica (magari una vista lato admin sarebbe più agevole)
3) Non attuare alcuna sospensione automatica.

**Comment by AlfioEmanueleFresta** [comment]
Grazie @PaoloGiustiniani.

1. Commit 3711102, appena i test automatici passano lo mando in produzione,
2. @CroceRossaItaliana/supporto puo' usare una ricerca con `cl. @cri.it` come https://gaia.cri.it/admin/anagrafica/persona/?q=cl.+%40cri.it che fa quanto chiedi
3. OK

**Comment by PaoloGiustiniani** [comment]
Provvedo ad occuparmi di notificare l'utilizzo anomalo di queste caselle.
