### ISSUE TITLE
[sicurezza] pannello admin

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#213]
Per il pannello "admin" bisognerebbe implementare la doppia autenticazione con OTP impostando la scadenza della sessione a 120 minuti di inattività, dopo tale periodo sarà necessario re-inserire OTP.

Dopo il login in Gaia, qualora un utente abbia privilegi di accesso amministrativi, sarà richiesto l'OTP per operare all'interno del pannello admin.

Solo un super-admin può configurare OTP per gli amministratori sottostanti.

Google authenticator?

**Comment by PaoloGiustiniani** [comment]
Possiamo girarla a Nephila?

**Comment by PaoloGiustiniani** [comment]
Up

**Comment by AlfioEmanueleFresta** [comment]
@yakky commenti di fattibilita'?

**Comment by yakky** [comment]
@AlfioEmanueleFresta mai affrontato l'integrazione con google authenticator, faccio un po' di ricerche e riporto qui

**Comment by PaoloGiustiniani** [comment]
Abbiamo informazioni a riguardo?

Aumentano gli operatori lato admin e abbiamo necessità di innalzare gli standard di sicurezza.

Come opzione temporanea possiamo filtrare l'accesso all'area admin per IP?

Questa restrizione si deve applicare solo a specifici utenti, quindi campo custom se abilitato si applica questa restrizione.

**Comment by PaoloGiustiniani** [comment]
Mi permetto di:

https://github.com/Bouke/django-two-factor-auth
https://github.com/mtigas/django-twofactor

**Comment by PaoloGiustiniani** [comment]
Abbiamo informazioni a riguardo?

**Comment by yakky** [comment]
@PaoloGiustiniani scusa, non era nella milestone e mi era sfuggita

**Comment by yakky** [comment]
@PaoloGiustiniani quale prirità ha?

**Comment by PaoloGiustiniani** [comment]
mi confronto un po'

**Comment by PaoloGiustiniani** [comment]
Riusciamo entro fine mese @yakky ?

**Comment by PaoloGiustiniani** [comment]
@yakky confrontandomi con @luca-dex è emerso che le due app sopra citate non sono idonee con l'applicazione di google authenticator.

L'intento è quello di generare OTP direttamente dall'APP di Google

**Comment by yakky** [comment]
@PaoloGiustiniani sì, è in lavorazione

**Comment by PaoloGiustiniani** [comment]
@astagi useremo l'app di Google authenticator, giusto?

**Comment by PaoloGiustiniani** [comment]
@astagi ho avuto modo di leggere il codice scritto, pare che stiate integrando twilio per l'invio dell'sms contenente il token.

L'OTP dev'essere generato da un app mobile come Google Auth.

**Comment by luca-dex** [comment]
Leggendo la documentazione di [django-two-factor-auth](https://github.com/Bouke/django-two-factor-auth) mi sembra che la parte essenziale per inserire la 2FA sfruttando [google-authenticator](https://github.com/google/google-authenticator) sia quella descritta qui: http://django-two-factor-auth.readthedocs.io/en/stable/configuration.html#general-settings, e in particolare il settaggio corretto dei parametri: `TWO_FACTOR_QR_FACTORY` e `TWO_FACTOR_TOTP_DIGITS`.

Questo permette di creare il QR code da decodificare tramite l'app di google-authenticator installata sullo smartphone che genera il codice di 6 digit da inserire per la verifica dell'accesso.

Di fanno non servono integrazioni nè con Twilio, nè con Yubikey.

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani  quello di cui ha fatto il push andrea è solo un WiP. Abbiamo implementato Twilio solo come riferimento, perché è quello più documentato.
Seguirà implementazione con google authenticator

**Comment by AlfioEmanueleFresta** [comment]
C'è possibilità di supporto YubiKey?

Alfio

**Comment by yakky** [comment]
@AlfioEmanueleFresta sì, c'è il plugin anche per yubikey
Nei prossimi giorni comunque implementeremo la versione per google authenticator e la metteremo su luke

**Comment by AlfioEmanueleFresta** [comment]
> Di fanno non servono integrazioni nè con Twilio, nè con Yubikey.

In realta' YubiKey sarebbe molto utile considerando che ne abbiamo prese un paio tempo addietro quando decidemmo di passare a 2FA per GitHub. Direi che se non e' complesso e basta installare un pacchetto e poco piu'[1], e' il caso di aggiungere il supporto in questa fase, magari mi occupo io di aggiungere le chiavi API necessarie in admin.

[1] http://django-two-factor-auth.readthedocs.io/en/stable/installation.html#yubikey-setup

**Comment by yakky** [comment]
@AlfioEmanueleFresta sì, dovrebbe essere molto semplice. L'unico problema è che attualmente non abbiamo yubikey a disposizione, quindi possiamo fare la configurazione ma non ci sarà possibile fare test

**Comment by AlfioEmanueleFresta** [comment]
OK, ci penso io a far test, nessun problema!

**Comment by luca-dex** [comment]
Sto iniziando a riscontrare dei problemi con 2FA. In particolare se a seguito di scadenza della sessione mi viene richiesto il token e io, invece che inserire il token punto una pagina valida di gaia, ad esempio https://gaia.cri.it/utente/ la richiesta del token viene bypassata e mi trovo loggato su gaia.

La situazione è stata riscontrata anche da @PaoloGiustiniani con il suo account, tuttavia non capita sempre. A volte si viene sempre rediretti alla pagine di reinserimento  del token, qualsiasi cosa si faccia, altre volte puntando l'url valido si accede a gaia senza inserire il token.

**Comment by yakky** [comment]
@luca-dex potresti aprire una segnalazione differente?
Rende più semplice l'analisi dei problemi senza dover analizzare lo storico dell'implementazione iniziale

**Comment by PaoloGiustiniani** [comment]
Nel modulo sviluppato è presente un BUG.

Quando la sessione di un admin scade viene correttamente visualizzato il messaggio che invita l'utente ad effettuare il login, richiamando semplicemente l'url https://gaia.cri.it/utente/ la sessione viene auto-rinnovata senza richiedere alcun codice otp.

**Comment by yakky** [comment]
@PaoloGiustiniani tracciamo questa cosa solo in #460 chiudo questo così abbiamo una sola segnalazioe per questo problema
