### ISSUE TITLE
[supporto] apertura richieste

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#214]
In fase di apertura delle richieste sarebbe opportuno poter riabilitare la selezione del volontario per il quale si richiede assistenza.

Grazie.

**Comment by yakky** [comment]
@PaoloGiustiniani potresti specificare meglio le azioni da compiere e il risultato atteso?

**Comment by luca-dex** [comment]
Nella precedente versione di gaia, quando un utente con privilegi di US richiedeva assistenza, poteva farlo anche per uno specifico volontario. 

In particolare era presente un selettore (il classico selettore dei volontari) per selezionare la persona per cui si chiedeva assistenza (es: il volontario x è stato trasferito per errore). Questo per permettere al supporto di avere il dettaglio e le informazioni relative alla persona per cui si chiede assistenza, evitando di dover specificare nome, cognome, codice fiscale, ed evitando che il supporto debba andare a verificare se quella persone è afferente o meno al dato comitato.

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani quindi, per esplicitare: Nella pagina ``/supporto/`` deve essere presente il selettore del volontario (con selezione tramite codice fiscale) per US e Presidente che viene poi inserito nell'email.
nel testo dell'email prevediamo qualche altra informazione oltre al CF?

**Comment by luca-dex** [comment]
Le stesse info inserite per la persona che apre la richiesta, info su
appartenenze, deleghe, ecc.

**Comment by PaoloGiustiniani** [comment]
Va bene anche per persone multiple, inserire una nota sopra ogni persona dove viene specificato di fare riferimento a questa persona nel dettaglio del ticket o in alternativa, sotto ogni persona selezionata inseriamo un campo note?

Che dici @luca-dex @CroceRossaItaliana/supporto

**Comment by yakky** [comment]
@PaoloGiustiniani penso che mettere una nota dicendo di dettagliare le problematiche di ogni persona nel ticket sia sufficiente. La selezione multiple l'ho pensata sopratutto per gestire casi in cui più persone abbiano la stessa problematica. Se c'è il rischio che siano aperte segnalazione omnibus per 10 persone con 10 problemi diversi, allora meglio lasciare la selezione singola!

**Comment by PaoloGiustiniani** [comment]
Segnalazione singola, perfetto.

Specifichiamo nel ticket che nel caso in cui la problematica impattasse più persone è necessario aprire un caso di supporto per ogni problematica / persona.

**Comment by luca-dex** [comment]
Concordo sull'opzione di ticket per ogni persona, un ticket per persona mi sembra la soluzione più sensata. Per problemi molto grossi si andrà a strutturare l'intervento del supporto in maniera congrua.

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani bene, allora la modifica è pronta per il test su luke

**Comment by PaoloGiustiniani** [comment]
@yakky non vedo la modifica su luke.

**Comment by yakky** [comment]
@PaoloGiustiniani hai i privilegi giusti? E' disponibile solo per US / Presidenti
