### ISSUE TITLE
[tesserino] non possibile richiedere duplicato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#215]
come da oggetto non sembra possibile richiedere il duplicato del tesserino.

**Comment by fmarco** [comment]
@matthewmazzoleni Si tratta quindi di una nuova funzionalità, giusto?

**Comment by AlfioEmanueleFresta** [comment]
Sì

**Comment by AlfioEmanueleFresta** [comment]
@fmarco ho già discusso in parte la cosa a @yakky se può essere utile.

**Comment by yakky** [comment]
@fmarco sì, ho un utilissimo schema tracciato a mano. sono sicuro di essermi perso metà dei passaggi ...

**Comment by AlfioEmanueleFresta** [comment]
Attualmente questo accade per il rilascio di un tesserino Volontario,
1. Il Volontario carica la propria fototessera da Volontario > Fotografia, in autonomia. Alternativamente, l'US del Volontario carica la fototessera per lui dalla scheda del Volontario (e si va al passo (3)).
2. Questa deve essere accettata dall'US del Comitato del Volontario (dal pannello Richieste),
3. L'US del Comitato del Volontario puo' quindi, avendo una fototessera accettata per il Volontario, inoltrare richiesta di stampa del tesserino al Comitato Regionale di competenza (Soci > Elenchi > Tesserini > Da richiedere). Questo vuol dire creare un oggetto `Tesserino` (leggasi Richiesta di tesserino)
4. Questa viene processata dall'US del Comitato Regionale (Soci > Tesserini > Emissione) e, se accettata, puo' essere stampato il tesserino (e spedito al Comitato Locale del Volontario, che lo consegnera').

L'oggetto `Tesserino` ha gia' una proprieta' che permette di distinguere se la richiesta e' una prima emissione o un duplicato. Questo deve essere esteso includendo le pagine per la richiesta di un duplicato.

Ad esempio, per il Comitato Locale, nelle schede "Da Richiedere", "Richieste" e "Senza Fototessera", alla voce "Richieste" dovrebbe essere presente un link per singolo Volontario per fare una nuova richiesta di duplicato. 

Alla richiesta deve essere immediatamente reso invalido il tesserino precedente (chiedo conferma a @matthewmazzoleni, @ico88) e creato un secondo oggetto `Tesserino` che deve subire esattamente lo stesso processo di una prima emissione, oltre al semplice fatto che deve chiaramente essere indicato come Duplicato in tutte le viste.

Dei test dovrebbero verificare funzionalmente il processo di richiesta di un duplicato, nonche' l'effettiva invalidazione del vecchio tesserino.

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta PR aperta. Facciamo il deployment da qualche parte per i test "manuali"?

**Comment by yakky** [comment]
@matthewmazzoleni puoi fare la verifica di questo task? E' caricato su http://luke.staging.sviluppo-gaia.ovh/
