### ISSUE TITLE
[trasferimento] impossibile trasferirsi verso comitato di estensione

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#217]
Il controllo del "sei gia' presente in questo comitato" deve essere effettuato solo sui comitati ove il socio e' presente come volontario, non come esteso.

Ticket: GNL-828-36082

> Buongiorno sono un volontario del comitato provinciale di padova con estensione di servizio presso il comitato locale di selvazzano dentro ed effettuando servizio prevalentemente a selvazzano vorrei trasferirmi di comitato.
> Gaia mi dice che sono già presente a selvazzano e non mi fa fare il trasferimento.

**Comment by yakky** [comment]
@AlfioEmanueleFresta @CroceRossaItaliana/supporto  è corretto limitare il controllo alla sola appartenenza come volontario, anziché escludere le estensioni (cioè: l'appartenenza come sostenitore o altre figure è comunque soggetta agl istessi vincoli del volontario?)

**Comment by PaoloGiustiniani** [comment]
@luca-dex

**Comment by luca-dex** [comment]
Un Volontario può trasferirsi in tutti i comitati di cui non è volontario, indipendentemente da estensioni, appartenenze come sostenitore o come dipendente. Al momento del trasferimento vengono interrotte:
- la sua precedente appartenenza come volontario
- tutte le estensioni attive

Il trasferimento non influisce sulle appartenenze come sostenitore o dipendente.

**Comment by yakky** [comment]
@luca-dex allora la modifica nella #481 dovrebbe essere a posto

**Comment by luca-dex** [comment]
@yakky mi aggiusti luke? :heart:
