### ISSUE TITLE
[posta] Invio massivo volontari che non hanno rinnovato la quota

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaItaliana/jorvik#218]
Generando l'elenco dei volontari che non hanno pagato la quota se si prova ad inviare un messaggio multiplo si viene rimandati al form per l'invio di un messaggio tradizionale, senza destinatari assegnati.

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo il problema si presenta quando la generazione impiega più di 10 secondi (il timeout impostato per recuperare i dati dalla sessione) https://github.com/CroceRossaItaliana/jorvik/blob/master/posta/viste.py#L96
volendo si può aumentare il timeout, aggiungendo un flag nell'url che permette di sapere quando si vuole davvero recuperare l'elenco e quando invece si sta scrivendo un nuovo messaggio dopo aver visitato un elenco

**Comment by yakky** [comment]
@AlfioEmanueleFresta cosa ne dici del mio commento soprA?

**Comment by yakky** [comment]
Ping @AlfioEmanueleFresta

**Comment by luca-dex** [comment]
Ping @AlfioEmanueleFresta :dango:

**Comment by AlfioEmanueleFresta** [comment]
@yakky LGTM
@luca-dex 🏓
