### ISSUE TITLE
[attività] Tasto "vai ad oggi"

### ISSUE THREAD

**Issue by biagiosaitta** [CroceRossaItaliana/jorvik#219]
nella scheda dei turni premendo il tasto "vai ad oggi" non si sposta nella pagina odierna ma a turni precedenti

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo in realtà è la dicitura "Vai a oggi" che non ha molto senso, perché compare in una pagina che mostra un elenco di turni in ordine di data, non un calendario. Al massimo può portare ad una pagina che mostra i turni che comprendano anche  quelli da oggi in poi, a meno di non ristrutturare quella lista perché sia filtrabile per data

**Comment by PaoloGiustiniani** [comment]
@CroceRossaItaliana/supporto @luca-dex

**Comment by luca-dex** [comment]
@PaoloGiustiniani non ho capito cosa vogliamo fare con questa cosa. Sicuramente è scomodo il fatto che quando si aprano dei turni si vedano sempre anche turni passati (di molto tempo prima). Onestamente non ho molte idee sul miglioramento del tasto, concordo con @yakky

**Comment by AlfioEmanueleFresta** [comment]
Non vorrei ricordare male, ma la cosa era gestita in questo modo: il pulsante riporta ad una pagina speciale che calcola a quale pagina ci siano i turni di oggi, con un fragment. Un pizzico di javascript individua quindi il fragment e evidenzi il primo turno della giornata attuale, nonche' vi ci scrolla con animazione (usando lo `scrollTo` di jQuery).

**Comment by AlfioEmanueleFresta** [comment]
Caso speciale dove oggi non vi sono turni: Porta alla pagina che includa l'ultimo turno prima di oggi. Se non vi sono turni, vuol dire che non vi e' alcun turno, e il pulsante dovrebbe essere grigio. Visto che non vi dovrebbe mai essere una pagina senza turni nella paginazione, a meno che non vi sia alcun turno per l'attivita', va bene testare la variabile che contiene la lista turni della pagina.

**Comment by yakky** [comment]
@AlfioEmanueleFresta controllo allora che la logica funzioni come da tuoi commenti

**Comment by yakky** [comment]
@AlfioEmanueleFresta secondo me c'è un errore nella logica di calcolo della pagina. Dovrebbe prendere il "ceil" non il "floor" della divisione, perché se un turno è alla pagina 3.4 vuol dire che devi visualizzare la quarta pagina perché sia visibile nella pagina stessa

**Comment by AlfioEmanueleFresta** [comment]
> @AlfioEmanueleFresta secondo me c'è un errore nella logica di calcolo della pagina. Dovrebbe prendere il "ceil" non il "floor" della divisione, perché se un turno è alla pagina 3.4 vuol dire che devi visualizzare la quarta pagina perché sia visibile nella pagina stessa

👏

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta aperta PR e caricata su luke
