### ISSUE TITLE
[donatore][typo]Fanotipo / fenotipo

### ISSUE THREAD

**Issue by alfiomusmarra** [CroceRossaItaliana/jorvik#220]
Credo che ci sia un errore di battitura nella sezione "donazione", 
https://gaia.cri.it/utente/donazioni/profilo/

la voce "fanotipo" non dovrebbe essere "fenotipo"?

**Comment by AlfioEmanueleFresta** [comment]
Grazie @alfiomusmarra per aver spottato l'errore.
