### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by ico88** [CroceRossaItaliana/jorvik#224]
Durante la modifica di alcune anagrafiche come ad esempio la modifica del CF di ID 82854 all'atto di salvare la pagina restituisce 500 Internal Server Error rendendo impossibile la modifica

**Comment by ico88** [comment]
Effettuando un'ulteriore analisi mi sono accorto che provavo a modificare il cf in un altro che già esiste sul sistema, non sarebbe opportuno che tale informazione venga esplicitata ?

**Comment by AlfioEmanueleFresta** [comment]
Credo che questo accada attualmente solo inserendo il codice fiscale in
maiuscolo, è un drawback legato all'uso di UpperCaseCharField che
utilizziamo per memorizzare lo stesso. Credo che la validazione del form
venga effettuata prima della conversione in maiuscolo, passi, e l'errore di
integrità quindi non venga catchato causando quell'errore 500.

Alfio Emanuele Fresta
