### ISSUE TITLE
Supervisione

### ISSUE THREAD

**Issue by ico88** [CroceRossaItaliana/jorvik#226]
Alcuni utenti ci chiedono il ripristino della funzione supervisione presente nel vecchio gaia.

Ticket es: NUM-486-71728

**Comment by AlfioEmanueleFresta** [comment]
Che roba e' la supervisione?

Comunque feedback -- Vedi #228

**Comment by ico88** [comment]
Era la funzione che ti permetteva di conoscere chi in un dato mese non
aveva fatto turni nel proprio comitato.
Quindi permetteva di attuare le eventuali perdite di qualifica con
semplicità
