### ISSUE TITLE
Filtro ricerca tesserini

### ISSUE THREAD

**Issue by ico88** [CroceRossaItaliana/jorvik#228]
Ci chiedono se era possible attivare un filtro di ricerca per Comitato di Appartenenza nell'elenco tesserini,  in modo da poter gestire meglio la stampa dei tesserini
Ticket: VHV-311-99834
ZPL-626-96537

**Comment by AlfioEmanueleFresta** [comment]
@ico88 questo genere di richieste vanno girate al dipartimento di feedback su Kayako. Da li' ripescate e rese issue solo al momento in cui viene deciso di renderlo feature.
