### ISSUE TITLE
Miglioramenti di estensioni, trasferimenti, riserve e delghe

### ISSUE THREAD

**Issue by ico88** [CroceRossaItaliana/jorvik#229]
Ticket IHG-562-44392
Quando un Volontario chiede estensione di servizio, trasferimento e riserva e gli viene approvata riceve una e-mail di comunicazione. Le sedi di appartenenza e destinazione però non ricevono nulla. Inoltre la e-mail inviata in automatico ha il testo standard non modificabile.
All' atto pratico ciò comporta che l'ufficio Soci provinciale, quando protocolla e autorizza la richiesta, deve poi mandare una ulteriore e-mail a Volontario, sede di appartenenza (e destinazione se estensione o trasferimento) per informare della avvenuta autorizzazione, informare di regole interne come l'uso di mezzi e nel caso del trasferimento per la gestione del fascicolo personale.
Vi chiedo quindi di implementare, per estensioni, trasferimenti e riserve, la possibilità di inserire ulteriori destinatari della comunicazione di gaia oltre al destinatario (meglio se in campo libero, gli indirizzi e-mail di segreteria sono specifici), e di aggiungere una parte di testo libero alla comunicazione.
Quando poi da altro Comitato avviene una estensione (e credo anche trasferimento) in ingresso non viene notificato in alcun modo, appare solo nell' elenco Soci. 
Dovrebbe almeno comparire una notifica all' Ufficio Soci, del tipo sotto alle richieste in attesa un campo estensioni in ingresso e trasferimenti in ingresso da registrare ed assegnare un protocollo. Meglio se anche da autorizzare, dato che potrebbe esse attiva una procedura elettorale.
Mentre per la riserva è possibile definire l'arco temporale, per le estensioni no. Può solo essere terminata. Se fosse possibile sarebbe utile implementare l'arco temporale anche in questo caso.
Ad oggi l'ufficio Soci può essere delegato dal presidente ad autorizzare i trasferimenti, ma non riserva ed estensione o partecipazione ad attività extra Comitato.
Questa limitazione non è possibile, per più motivi. Il presidente di un Comitato da 1500 Soci difficilmente ha tempo di operare direttamente su gaia, se delega il responsabile dell' ufficio Soci a procedere questi deve operare con l'account del presidente e non è corretto, inoltre trasferimenti ed estensione sono nello stesso articolo di regolamento ma solo il trasferimento,  con cui si "perde " il Volontario quindi è di livello "superiore" all' estensione, è delegabile all' ufficio Soci.
Vi chiedo quindi di estendere, al pari di quanto avviene per il trasferimento, anche per estensione, riserva e autorizzazione attività la facoltà di delega da pare del presidente all' ufficio Soci. Questo passo è particolarmente importante per una buona gestione di gaia.
Ultima cosa, l'attivazione dei corsi base, per gli stessi motivi, dovrebbe essere il presidente a decidere se farla personalmente o delegarla al responsabile della formazione.
Tutto ciò Vi scrivo, ovviamente, sentito il Presidente del Comitato. Di fatto dovrebbe avere la possibilità di dare in gestione ad altri tutte le attività del proprio account che ritiene utile, senza limitazioni, di fatto delegando l'account ad altra persona che possa operare con le proprie credenziali. Ad esempio l'attivazione del corso base, una volta che il presidente firma l'ordinanza, è autorizzata e la parte informatica potrebbe gestirla qualcun'altro per lui, anche l'attivazione, e così tutto il resto.

**Comment by PaoloGiustiniani** [comment]
In caso di termine riserva o chiusura anticipata riserva NON viene recapitata alcuna email al presidente / ufficio soci.

**Comment by yakky** [comment]
Ho aperto le segnalazioni sui messaggi. La parte sulle deleghe ha bisogno di chiarimenti aggiuntivi a livello di regolamento, ma US attualmente mi risulta poter gestire approvazine di trasferimenti, estensioni e riserver.
La gestione delle date delle estensioni è in #400 (vedi https://github.com/CroceRossaItaliana/jorvik/issues/400#issuecomment-279639718)
I corsi sono invece delegabili al direttore di corso

@PaoloGiustiniani @luca-dex @AlfioEmanueleFresta confermate?

**Comment by luca-dex** [comment]
@yakky per le estensioni fa fede quello che è dettagliato in #400 

Dimmi cos'altro ti serve sapere.

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani direi che c'è da capire se #558, #559, #400  possono "riassumere" le richiesta di questa issue, considerado che alcune cose (vedi la delega dei corsi, ma anche la delega di altre funzioni) è già possibile

**Comment by luca-dex** [comment]
Chiudo questa perchè tutto ciò che manca da fare è in #400 e #559
