### ISSUE TITLE
visione mobile: ottimizzazione menù

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#23]
richiesta ottimizzazione menù in quanto difficilmente usabile.

**Comment by AlfioEmanueleFresta** [comment]
Come esposto da @alfiomusmarra in #160, alcuni dispositivi hanno problemi di visualizzazione dello stesso pulsante. Quindi il problema sale da problema estetico a problema funzionale che affligge un basso numero di utenti - scalo la priorita' di conseguenza.
