### ISSUE TITLE
cron posta.smaltisci KO

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#235]
Il cron in oggetto è KO.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django_cron/management/commands/runcrons.py", line 62, in run_cron_with_cache_check
    manager.run(force)
  File "/usr/local/lib/python3.4/dist-packages/django_cron/**init**.py", line 214, in run
    self.msg = self.cron_job.do()
  File "/home/gaia/jorvik/posta/cron.py", line 14, in do
    Messaggio.smaltisci_coda(dimensione_massima=1500)
  File "/home/gaia/jorvik/posta/models.py", line 284, in smaltisci_coda
    messaggio.invia(connection)
  File "/home/gaia/jorvik/posta/models.py", line 173, in invia
    to=[d.persona.email],
AttributeError: 'NoneType' object has no attribute 'email'

**Comment by yakky** [comment]
Per ora abbiamo fatto il catch dell'eccezione (#236). Potrà essere utile capire il motivo per cui ci sono destinatari senza persone

**Comment by AlfioEmanueleFresta** [comment]
Grazie @yakky

**Comment by PaoloGiustiniani** [comment]
Scusate se riapro, potreste fornirmi maggiori informazioni circa la durata eccessiva del cron?

Ci sono alcune condizioni in cui la durata impiega 7 minuti.

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta non avendo accesso all'ambiente live non riesco a dare molte indicazioni al momento

**Comment by PaoloGiustiniani** [comment]
Ci stiamo organizzando per consentirvi l'accesso "spot" al backend di Gaia, è propedeutico terminare #213 

Nel mentre, @AlfioEmanueleFresta potrà supportarvi per fornirvi le informazioni di vostro interesse.

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta io chiuderei questo che comunque dovrebbe essere stato risolto da #415 (in attesa di capire i motivi di #345)

**Comment by PaoloGiustiniani** [comment]
Confermo, attualmente il cron non ha problemi.
