### ISSUE TITLE
[estensioni] mancata auto approvazione

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#237]
Le estensioni non vengono auto approvate dopo 30 giorni.

**Comment by AlfioEmanueleFresta** [comment]
@yakky 

E' necessario progettare una estensione al sistema di autorizzazioni di Gaia. Attualmente le funzionalita' sono fornite dal Mixin `ConAutorizzazioni` che fa uso del modello `Autorizzazione`. Il sistema si occupa di fornire una interfaccia comune per la comunicazione tramite e-mail a chi necessario, renderizzare in modo simile (fornendo `/autorizzazioni/`) e giocare con i moduli di consenso o dissenso.

Diverse entita' fanno uso delle "richieste di autorizzazioni", fra queste compaiono `anagrafica.Estensione` (richiesta di estensione), `anagrafica.Trasferimento` (richiesta di trasferimento), `attivita.Partecipazione` (richiesta di partecipazione ad una attivita'), ecc. Ognuna di queste personalizza il comportamento del mixin sovrascrivendo delle proprieta' e dei metodi (es. callback `autorizzazione_concessa`).

Ogni classe definisce inoltre un eventuale `Form` per l'accettazione e uno per la negazione, che vengono presentati al responsabile che rispettivamente accetta o nega una richiesta. Il modulo completato e valido viene quindi passato come oggetto al metodo callback sovrascritto in ogni modello, che lo memorizza a modo suo.

Le seguenti problematiche sono apparse:
- Alcune autorizzazioni devono, da regolamento CRI, essere approvate automaticamente dopo un certo periodo di tempo, se non manualmente fatto, vedi le richieste di estensione,
- Alcune autorizzazioni dovrebbero, se ignorate, essere rifiutate automaticamente dopo un certo periodo di tempo, vedi le richieste di partecipazione ad una attivita'.

Requisiti:
Una soluzione potrebbe essere quella di
1. estendere il sistema e permettere la configurazione (drop-in) di una accettazione automatica dopo un periodo di tempo anch'esso configurabile (`timedelta`),
2. estendere il sistema e permettere la configurazione (drop-in) di un rifiuto automatico dopo un periodo di tempo anch'esso configurabile (`timedelta`),
3. in ognuno dei casi sopra un cronjob dovrebbe processare le richieste sulle quali attuare ogni X ore e dovrebbe essere mandata una e-mail sia al richiedente che al destinatario che ha ignorato la richiesta, es.: `la tua richiesta e' rimasta in attesa per 30 giorni e come da policy e' stata accettata automaticamente dal sistema [...] una conferma e' stata inoltre inviata a Mario Rossi", oppure la tua richiesta e' rimasta in attesa per 30 giorni e come da policy e' stata rifiutata automaticamente dal sistema",
4. questo issue non richiede l'implementazione di questa soluzione sui modelli ma solo l'estensione del sistema attuale,
5. test non funzionali da includere per favore, che testino l'interfaccia ed il comportamento di `ConAutorizzazioni` in varie configurazioni in dei modelli di test.

**Comment by yakky** [comment]
@AlfioEmanueleFresta i model espongono ``autorizzazione_concessa`` / ``autorizzazione_negata`` per effettuare le operazioni per concedere / negare, a cui si passa un modulo (o meglio dei suoi valori); in generale ho visto che sono estratti i dati di protocollo, che però in caso di attività automatica non esistono.
Come gestire questo caso?

**Comment by fmarco** [comment]
@AlfioEmanueleFresta ^^^

**Comment by AlfioEmanueleFresta** [comment]
@fmarco @yakky direi di passare come parametri `modulo=None` e `auto=False` rispettivamente, dove almeno una dei due e' vera/definita.
```python
assert (modulo and not auto) or (auto and not modulo)
```

Sara' cura delle implementazioni del callback gestire la cosa, al di fuori dell'inviare la comunicazione e memorizzare lo stato. Bisogna inoltre che comunque ogni oggetto `ConAutorizzazioni` abbia accesso ad una property es. `.autorizzazione_automatica` che permetta di verificare se l'autorizzazione e' stata concessa automaticamente o meno (anche al di fuori del corpo del callback, in vero)

**Comment by PaoloGiustiniani** [comment]
Il pregresso è stato gestito?

**Comment by AlfioEmanueleFresta** [comment]
Buona idea @PaoloGiustiniani, magari come nuova PR a se' stante basata su #315, potrebbe essere utile fare una migrazione automatica che imposti i corretti parametri sulle autorizzazioni pendenti da tempo, in modo tale che vengano processate la prima notte dopo il merge.

**Comment by yakky** [comment]
@PaoloGiustiniani no, il pregresso non è gestito anche perché attualmente l'implementazione per le attività è inteso solo come "implementazione di riferimento".
Può essere gestita a parte (ad es tramite datamigration) l'impostazione dei parametri corretti per le richieste pendenti

**Comment by AlfioEmanueleFresta** [comment]
@yakky per favore gestiamo questa cosa con una migrazione successiva.

**Comment by yakky** [comment]
@AlfioEmanueleFresta certamente

**Comment by yakky** [comment]
Aperta #316 per tracciare l'attività

**Comment by matthewmazzoleni** [comment]
riceviamo molte richieste in merito

**Comment by yakky** [comment]
@matthewmazzoleni sono stati fatti i test sul server di test per la pull request collegata? https://github.com/CroceRossaItaliana/jorvik/pull/315 Chiedi pure se hai bisogno di ulteriori informazioni.

**Comment by PaoloGiustiniani** [comment]
@yakky ingloba anche la parte di trasferimenti o solo estensioni?

**Comment by yakky** [comment]
@PaoloGiustiniani quella PR gestisce attualmente esclusivamente le attività, come implementazione di riferimento.
Per l'implementazione della funzionalità sulle altre richieste devono essere fatte PR specifiche
