### ISSUE TITLE
[permessi] notifica estensioni 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#238]
La mail di notifica "Notifica di estensione" contiene al suo interno un link per accedere alla richeista di estensione in questione, purtroppo gli utenti ricevono errore di permessi.

**Comment by yakky** [comment]
@PaoloGiustiniani intendi la notifica al delegato ufficio soci che deve approvare la richiesta?

**Comment by AlfioEmanueleFresta** [comment]
E' possibile che il problema sia relativo a un link che e' scaduto -- ovvero facente riferimento a una richiesta gia' approvata o negata. Se non ricordo male nel passato, non vi era un errore esplicativo (i.e. "La richiesta e' gia' stata processata") ma un semplice errore di permessi.

Vale la pena controllare la storia su Git per la pagina permessi ed eventualmente discardare questo issue.

**Comment by yakky** [comment]
Attualmente il caso descritto da Alfio ritorna "Richiesta non trovata" e non vedo modifiche successive a febbraio 2016 https://github.com/CroceRossaItaliana/jorvik/blame/master/base/viste.py#L360

**Comment by PaoloGiustiniani** [comment]
@yakky il caso segnalato è differente: quando un utente effettua una nuova richiesta di estensione viene notificato (da quanto ricordo) US e Presidente, il link ricevuto nella loro casella di posta, una volta aperto, mostra un errore di permessi su Gaia. Vedo se trovo qualcosa.

**Comment by yakky** [comment]
@PaoloGiustiniani grazie

**Comment by yakky** [comment]
@PaoloGiustiniani ho verificato. Attualmente i permessi di US (e per estensione quelli di presidente) danno accesso solo alle richieste (quindi trasferimenti, estensioni) **in uscita**, non **in entrata**.
Cosa facciamo, estendiamo i permessi in lettura per poter vedere anche quelli in entrata?

**Comment by yakky** [comment]
PR deployata su luke
