### ISSUE TITLE
tesserini: richiesta implementazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#24]
- [x] possibilità di caricare fototessera (utente/us/p)
- [x] funzionalità di gestione tesserini

**Comment by AlfioEmanueleFresta** [comment]
* e195e1781f0dba1ab7440c337278fce6aa3c8d87 permette di caricare una fototessera dalla scheda del Volontario,
* 461c4b34def46e0a4a0b768e079af4bf7abf632d permette di
  * vedere un elenco dei volontari senza fototessera caricata,
  * vedere un elenco dei volontari per i quali e' possibile richiedere un tesserino,
    * fare richiesta di tesserino,
  * vedere un elenco dei volontari per i quali e' stato richiesto un tesserino.

**Comment by AlfioEmanueleFresta** [comment]
Completato.
