### ISSUE TITLE
Inserimento in homepage ricerca profilo

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#241]
E' necessario inserire in homepage, post login, in modo ben visibile il seguente annuncio di lavoro:

"Vuoi lavorare nel team di GAIA come Operatore Helpdesk? Clicca qui per ulteriori informazioni"
http://www.criroma.it/20160428265/lavora-con-noi/operatore-help-desk.html

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani online.
