### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#245]
Bisogna ripristinare l'informativa sui cookie

**Comment by AlfioEmanueleFresta** [comment]
Questo include l'analisi e l'assicurarsi che non vengano rilasciati cookie senza il consenso dell'utente come da orrenda normativa del garante della privacy in Italia. Anche se credo che Django di perse' non lo faccia in merito all'autenticazione, ma abbiamo Analytics.

**Comment by yakky** [comment]
@AlfioEmanueleFresta confermo che django di per sé non setta cookie. Per analytics è diverso. C'è già del codice specifico (la descrizione parla di "ripristinare")? L'idea è quella di mostrare il banner: se l'utente chiude o accetta viene settato un cookie che fa sì che il codice di analytics venga renderizzato, corretto?

**Comment by yakky** [comment]
Vecchia pagina di informazioni sui cookie: https://github.com/CroceRossaCatania/gaia/blob/master/inc/public.cookie.php
