### ISSUE TITLE
[geo] posizioni con coordinate 0,0

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#247]
Il sistema di posizionamento (utilizzato tramite un template tag) permette di scegliere delle locazioni da associare per tutte le entita' con mixin `ConLocazione`. Questo utilizza dentro `Locazione` le Geoconding APIs di Google Maps per cercare quanto inserito dall'utente, creare un oggetto Locazione se non esistente, ed associarlo infine al modello desiderato.

Ci sono tre problemi da risolvere:

- [x] In alcuni casi gli indirizzi non ritornano coordinate. In questo caso non dovremmo permettere l'associazione alla posizione trovata su google e fornire piuttosto un messaggio che spiega che nessuna posizione e' stata trovata. Questo e' il problema che ha causato piu' volte la locazione di oggetti Sede nel Golfo di Guinea (ad esempio oggi ci stanno le Isole Eolie https://gaia.cri.it/informazioni/sedi/)
- [x] Nella pagina pubblica di informazioni sulla sede (`informazioni_sede` credo), se nessuna posizione e' associata, la mappa non dovrebbe essere mostrata piuttosto che aprirsi nel mezzo dell'oceano (vedi Carbognano https://gaia.cri.it/informazioni/sedi/italia-lazio-viterbo-carbognano/)
- [x] Un problema con la lettura del parametro `GET` (`?embed=False`) porta alla visione di tutte le pagine senza header o footer. Credo che derivi dal fatto che per Python, giustamente, `"False" == True`.

/cc @galamarco

**Comment by yakky** [comment]
@AlfioEmanueleFresta questa è da lavorare con priorità immediata, giusto?

**Comment by AlfioEmanueleFresta** [comment]
@yakky alta priorita' nell'essere pescato dalla pila di lavori in attesa, ma non urgente nel senso da giustificare l'interruzione di lavoro in corso, se chiedi a me.

**Comment by yakky** [comment]
Sì, sì. Ma per l'appunto dovevamo comunque cominciare attività nuove.

**Comment by yakky** [comment]
La Pr linkata integrerà via via tutti i fix

**Comment by yakky** [comment]
@AlfioEmanueleFresta hai qualche esempio di indirizzo che non ritorni delle coordinate valide?

**Comment by AlfioEmanueleFresta** [comment]
@yakky prova con `Via Vittorio Emanuele, 42, Stromboli, ME`

**Comment by yakky** [comment]
Per il caso 1 una soluzione del genere sarebbe in linea? Il bottone non è selezionabile e dentro ilbottone viene spiegato il motivo. altrimenti si inserisce sotto ma graficamente potrebbe non essere granché

![esempio](https://cloud.githubusercontent.com/assets/714711/15081286/890e9e7a-13c2-11e6-8d4f-79e4ec547054.png)

**Comment by AlfioEmanueleFresta** [comment]
Si, magari scriviamo qualcosa come 
```html
<i class="fa fa-fw fa-warning"></i> Google Maps non conosce le coordinate per questo indirizzo.
```

**Comment by yakky** [comment]
O sennò così 
![button1](https://cloud.githubusercontent.com/assets/714711/15081421/3b4749e8-13c3-11e6-9758-af50cc096234.png)

**Comment by yakky** [comment]
Con il testo che suggerisci tu

NB: Quei tre indirizzi ritornano comunque coordinate corrette, bisognerà implementare dei controlli un po' alla cieca facendo dei mock nei test per poter riprodurre il caso

**Comment by AlfioEmanueleFresta** [comment]
@yakky per quel che ne so potrebbe esserci una altra ragione oscura per quel problema... diciamo che un indirizzo senza coordinate non deve esistere. Comunque la seconda va bene, col testo modificato

**Comment by yakky** [comment]
@AlfioEmanueleFresta :+1: Preparo un test che ci assicuri una corretta gestione del caso di coordinate non valide

**Comment by AlfioEmanueleFresta** [comment]
Ho riaperto perche' abbiamo sedi in Africa

**Comment by yakky** [comment]
@AlfioEmanueleFresta gli indirizzi africati mi risultano funzionanti. Ho anche esteso il test geografico esistente per testare dei punti a cavallo dell'equatore senza problemi

**Comment by yakky** [comment]
@AlfioEmanueleFresta quindi la posso considerare chiusa con il test sugli indirizzi africani?
