### ISSUE TITLE
aspiranti: raggio e domanda formativa

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#25]
va verificata la gestione degli aspiranti-raggio-comitati perché due sedi dello stesso comitato, distanti tra loro 10 km, hanno rispettivamente 504 aspiranti e 0 aspiranti.

**Comment by AlfioEmanueleFresta** [comment]
Hm, @matthewmazzoleni  la sede con 0 aspiranti ha una posizione impostata? (Sedi > Modifica > Posizione)
