### ISSUE TITLE
Flag doppio invio email utenza / contatto

### ISSUE THREAD

**Issue by yakky** [CroceRossaItaliana/jorvik#251]
L'oggetto Messagio attualmente invia di preferenza all'email di contatto anziché a quella di utenza.
Bisogna introdurre un flag che permetta di inviare lo stesso messaggio a entrambi gli indirizzi.
Attualmente da impostare solo x email recupero password e per email di invio credenziali da parte dell'ufficio soci

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani come da discussione con te.

**Comment by PaoloGiustiniani** [comment]
:+1:

**Comment by fmarco** [comment]
@AlfioEmanueleFresta di quale funzione si tratta "email di invio credenziali da parte dell'ufficio soci"

**Comment by AlfioEmanueleFresta** [comment]
Ufficio Soci > Elenco qualunque > Scheda > Credenziali > Attiva
