### ISSUE TITLE
Validazione indirizzo email

### ISSUE THREAD

**Issue by yakky** [CroceRossaItaliana/jorvik#258]
E' necessario validare l'indiizzo email in fase di registrazione e di cambio email

Per la registrazione:

 * spostare lo step ``STEP_CREDENZIALI`` prima di ``STEP_ANAGRAFICA``
 * al termine dello ``STEP_CREDENZIALI`` inviare email con link alla vista ``STEP_ANAGRAFICA``
 * disattivare modo per procedere da  ``STEP_CREDENZIALI`` a  ``STEP_ANAGRAFICA`` senza passare dal link

Per il cambio email

* inviare link a vista che marca l'email come "valida"
* finché non è convalidata la nuova email usare la vecchia per tutte le comunicazioni

**Comment by yakky** [comment]
@AlfioEmanueleFresta il processo del cambio email deve valere sia per l'email di contatto della persona che quello di registrazione dell'utenza, è corretto?

**Comment by astagi** [comment]
@AlfioEmanueleFresta siamo in attesa di chiarimenti sulla questione cambio mail (vedi commento precedente di @yakky )

😄

**Comment by AlfioEmanueleFresta** [comment]
@astagi @yakky si
