### ISSUE TITLE
ufficio soci: abilitazione/disabilitazione approvazioni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#26]
segnalano la mancanza della funzionalità (prima attiva di default) che impedisce a US di effettuare approvazioni in delega dal presidente. richiedono che venga reintrodotta

**Comment by foresta86** [comment]
Salve, vorrei sapere se ci sono novità in merito: infatti, anche se ci sono richieste in sospeso, non ricevo alcuna email di notifica per avvertirmi di ciò.
Grazie.

**Comment by luca-dex** [comment]
Mi sembra che la gente ora viva bene con il fatto che ogni azione fatta venga notificata a tutti gli interessati
