### ISSUE TITLE
[documenti] mancanza estensione file crea problemi

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#271]
Nella nuova applicazione per la gestione dei documenti sono presenti documenti senza estensione, che non possono essere correttamente aperti lato utente. Di per se il problema non è evidentemente di gaia, ma di chi ha caricato i file, la problematica però si avrà poi sugli utenti che non riusciranno ad aprirli.

Sarebbe utile permettere a chi carica documenti di poter modificare il nome del documento caricato, obbligandolo comunque a mantenere un'estensione per il documento.

Esempio del problema: Area Sviluppo -> carta intestata -> entrambi i file

**Comment by yakky** [comment]
@AlfioEmanueleFresta @luca-dex come vogliamo gestire questa? E' possibile aggiungere il controllo che obbliga ad aggiungere un'estensione, ma è piuttosto fragile ...

**Comment by AlfioEmanueleFresta** [comment]
Il file viene servito tramite stream http, se forniamo un hint al browser a
riguardo del mime type, il problema non dovrebbe verificarsi.

Possiamo aggiungere una colonna che dica in che formato è il file,
piuttosto che aggiungere l'estensione? Possiamo usare l'estensione del
formato originale, ove presente, o se esiste qualche libreria che fornisce
una descrizione human readable a partire dal mime possiamo usare quello

Alfio Emanuele Fresta

**Comment by yakky** [comment]
@AlfioEmanueleFresta sì, in alternativa si può anche gestire con il mimetype

**Comment by AlfioEmanueleFresta** [comment]
Upload: Scan-12345.pdf
Nome file: Regolamento Volontari CRI

... diventa ...

Nome: Regolamento Volontari CRI
Formato: PDF

----

In generale:

Upload: nomefile.xyz
Nome: ABC

... diventa ...

Nome: ABC
Formato: XYZ

----

Credo si tratti solo di 

* Suggerire un mime type via header http (`Content-Type`?)
* Aggiungere una property al documento che prenda l'estensione del file caricato, se presente e la renda in maiuscolo (con caso estensione non presente -- None?)
* Visualizzare tale property come colonna accanto al nome del file

**Comment by luca-dex** [comment]
Quando un utente fa poi il download viene poi rimontato il nome file nella modalità "download" + <formato>, oltre all'aggiunta del mime type?
Ci sono controlli che limitano le tipologie di file che è possibile caricare?

**Comment by yakky** [comment]
@AlfioEmanueleFresta puoi vedere se #272 è una soluzione

**Comment by yakky** [comment]
Fixed in #272
