### ISSUE TITLE
[tesserino] Errore emissione tesserini

### ISSUE THREAD

**Issue by fmarco** [CroceRossaItaliana/jorvik#279]
Sotto Soci -> Tesserini -> Emissione, se la tabella dei risultati è vuota, qualsiasi action sotto "Processa Selezionati" restituisce un KeyError.

**Comment by AlfioEmanueleFresta** [comment]
Grazie per la segnalazione.

**Comment by astagi** [comment]
Non più riproducibile, forse è stato già fixato? cc @fmarco

**Comment by luca-dex** [comment]
Al momento questo errore non è riproducibile
