### ISSUE TITLE
[admin] Aggiunta permesso "visualizzazione"

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#290]
Vi chiederei, qualora fosse possibile, un nuovo permesso oltre quelli già presenti (change, delete, add) che consenta la sola visualizzazione senza la possibilità di apportare alcuna modifica.

Grazie.

**Comment by PaoloGiustiniani** [comment]
Vista l'imminente necessità, da parte della Sala Operativa Nazionale, di mobilitare il personale verso le zone colpite dal terremoto, tale issue assume carattere prioritario.

Gli operatori della SON hanno necessità di consultare le anagrafiche per esigenze di servizio.

**Comment by yakky** [comment]
@PaoloGiustiniani quali sono i model che devono essere interessati dalla modifica?

**Comment by PaoloGiustiniani** [comment]
Su tutti, cortesemente.

**Comment by yakky** [comment]
@PaoloGiustiniani tutti quelli dell'anagrafica o tutti in generale?

**Comment by yakky** [comment]
@romolox d'accordo con @PaoloGiustiniani facciamo una piccola modifica: il nome del gruppo usiamolo come wildcard: ovvero facciamo scattare il meccanismo su *_readonly anziché anagrafica_readonly, cosìcché possano gestire in modo più flessibile le suddivisioni in gruppi

**Comment by PaoloGiustiniani** [comment]
Grazie a tutti.

**Comment by PaoloGiustiniani** [comment]
Novità a riguardo?

**Comment by yakky** [comment]
chiuso da #355

**Comment by PaoloGiustiniani** [comment]
Scusate se riapro

anagrafica | provvedimento disciplinare
articoli | segmento
auth | gruppo
auth | permesso
patenti | elemento
patenti | patente

Non è presente la view, forse per patenti è voluto.

**Comment by yakky** [comment]
@PaoloGiustiniani potresti aggiungere romolox al progetto così da potergli assegnare le segnalazioni'

**Comment by PaoloGiustiniani** [comment]
@yakky fatto
