### ISSUE TITLE
[mail] Invio massimo

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#294]
Il presidente Nazionale / Regionale / area Metropolitana (ex provinciale) / locale deve poter inviare comunicazioni destinate a ruoli specifici:

- Presidente
- Ufficio Soci
- Delegato d'area 1 
- etc

**Comment by yakky** [comment]
Al di là dei filtri il.meccanismo di invio dei messaggi è corretto?

On 10 June 2016 16:08:58 CEST, Paolo Giustiniani <notifications@github.com> wrote:
>Il presidente Nazionale / Regionale / area Metropolitana (ex
>provinciale) / locale deve poter inviare comunicazioni destinate a
>ruoli specifici:
>
>- Presidente
>- Ufficio Soci
>- Delegato d'area 1 
>- etc
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CroceRossaItaliana/jorvik/issues/294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yakky** [comment]
@PaoloGiustiniani questo è sostanzialmente uguale a #242 giusto?

**Comment by luca-dex** [comment]
Sì, possiamo  chiudere questa e tenere #242

**Comment by yakky** [comment]
@luca-dex tks
