### ISSUE TITLE
[visualizzazione] sedi sottostanti 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#295]
I presidenti regionali, nell'elenco sedi, non vedono più i comitati sotto di loro competenza. Idem nazionale.

**Comment by yakky** [comment]
@PaoloGiustiniani intendi all'ndirizzo ``/presidente/`` e nella selezione delle sedi degli elenchi?

**Comment by luca-dex** [comment]
@PaoloGiustiniani con che regionale hai verificato? Perchè ovviamente la lombardia non fuziona avendo tutta l'alberatura scombinata, invece, ad esempio per la liguria, vedo questo: 

![screenshot at 2017-01-16 09-19-06](https://cloud.githubusercontent.com/assets/3315913/21975424/dd0318da-dbcc-11e6-82bf-d4600f3ff1a8.png)

Però a questo punto non so se ciò che vedo è corretto ed è quello che dovrei vedere.

**Comment by PaoloGiustiniani** [comment]
@luca-dex piemonte?

**Comment by luca-dex** [comment]
Quello che noto, ad esempio, è che non vede tutta la regione ma solo quei particolari Comitati, ma non tutta l'alberatura della regione. Quale dovrebbe essere la situazione corretta @AlfioEmanueleFresta ? Onestamente io non lo ricordo.

**Comment by AlfioEmanueleFresta** [comment]
Perche' il Presidente regionale dovrebbe essere in grado di modificare i dettagli anagrafici dei Comitati?

**Comment by PaoloGiustiniani** [comment]
Dev'essere in grado di poterli vedere, in sola lettura, come organo di verifica

**Comment by AlfioEmanueleFresta** [comment]
Puo' farlo dall'elenco pubblico. Magari mettiamo un link che suggerisca come accedere all'elenco pubblico. Modificare la pagina per averla con opzioni in sola lettura sarebbe veramente complesso: L'elenco di questa pagina viene scaricata direttamente dal sistema che fa la risoluzione dei permessi..., che e' intrecciatissimo.

**Comment by luca-dex** [comment]
Quindi nel mio esempio della liguria la situazione è così perchè quei 4 comitati sono gestiti dal presidente regionale? è realmente così o non ho capito io

**Comment by AlfioEmanueleFresta** [comment]
Si, Maurizio Biancaterra

**Comment by luca-dex** [comment]
Allora @PaoloGiustiniani questa si può chiudere, a meno che non vogliamo mettere un link per dove guardare le informazioni dei comitati

**Comment by yakky** [comment]
@PaoloGiustiniani @luca-dex @AlfioEmanueleFresta chiudiamo o aggiungiamo il testo?

**Comment by PaoloGiustiniani** [comment]
Sì chiudiamo e aggiungiamo il test con link su dove guardare le informazioni dei comitati.

**Comment by yakky** [comment]
@PaoloGiustiniani quindi in ``/presidente/`` aggiungiamo una cosa del tipo "Per informazioni sugli altri comitati, compresi quelli sottostanti, puoi accedere `qui`" (dove `qui` è il link al proprio comitato sulla pagina pubblica, così da vedere i propri "discendenti")

**Comment by PaoloGiustiniani** [comment]
sì per i presidenti regionali

**Comment by luca-dex** [comment]
Non solo per i regionali. Per tutti quelli che hanno comitato sottostanti
(roma, ecc)

**Comment by yakky** [comment]
Fatto il deploy su luke. Non ho potuto testarte specificamente roma, ma la logica è quella indicata da luca

**Comment by luca-dex** [comment]
Ok, poi verifico, grazie
