### ISSUE TITLE
[anagrafica] Indirizzo sede comitato 

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#296]
Nel "cerca indirizzo" (di una sede) lo Stato può essere solo "Italia" e non tutti gli stati del mondo, prevediamo l'inserimento accidentale di altri stati.

**Comment by yakky** [comment]
@PaoloGiustiniani cosa intendi con "prevediamo l'inserimento accidentale di altri stati"? Che anche se inserisco "Zimbabwe" lui comunque mi ricerca l'indirizzo in Italia? Altrove però si segnalava che potrebbero esserci sedi fuori dal territorio italiano (https://github.com/CroceRossaItaliana/jorvik/issues/247#issuecomment-234329494)

**Comment by PaoloGiustiniani** [comment]
@yakky nella pagina /presidente/sedi/XXX c'è un dropdown con i vari Stati, rendiamo disponibile solo "Italia" idem per /aspirante/corso-base/xxx/modifica/.

@luca-dex hai idea di altri menù simili?

**Comment by luca-dex** [comment]
@PaoloGiustiniani localizzazione delle attività?

**Comment by PaoloGiustiniani** [comment]
Ok, aggiungiamo. 

La pagina?

**Comment by luca-dex** [comment]
A pensarci bene lascerei perdere rispetto a quello che ho detto. Le attività possono essere fuori dal territorio nazionale, quindi per me a posto così.

**Comment by PaoloGiustiniani** [comment]
@yakki possiamo procedere

**Comment by yakky** [comment]
@PaoloGiustiniani @luca-dex è su luke per i test

**Comment by Yakki** [comment]
@PaoloGiustiniani please stop tagging me.

**Comment by PaoloGiustiniani** [comment]
I've tagged yakki and NOT Yakki (lower case). Please contact Github for more information or block me (https://help.github.com/articles/blocking-a-user-from-your-organization/).
