### ISSUE TITLE
[permessi] aspiranti e dipendenti

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#297]
I dipendenti e gli aspiranti vedono il menù del volontario, questo non deve avvenire, così come le funzioni dedicate al volontario non devono essere abilitate.

**Comment by yakky** [comment]
Collegato a #404

**Comment by yakky** [comment]
@PaoloGiustiniani 
Abbiamo bloccato le voci dettagliate nelle varie issue, ma alcune specifiche erano un po' generiche, potete verificare su luke?

**Comment by PaoloGiustiniani** [comment]
Non mi risultano bloccate tali funzionalità, ad esempio: "/utente/curriculum/TC/" è correttamente accessibile e richiamata da browser
