### ISSUE TITLE
[delegato giovani] verifica controllo età

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#298]
Nella fase di nomina del delegato area 5 la persona deve avere un'età minore di 33 anni (quindi fino a 32 e 364 giorni) al raggiungimento dell'età (delega in atto) bisogna prevedere l'auto terminazione delle delega (loggando il perchè).

**Comment by galamarco** [comment]
@AlfioEmanueleFresta  quanto già richiesto da @PaoloGiustiniani si aggiunge la necessità di aggiornare il pannello "statistiche" (che riporta come giovani tutti gli under 36 mentre dovrebbe essere under 33) e i segmenti dei moduli notizie e documenti che riportano anche loro under 36 anzichè under 33.

**Comment by yakky** [comment]
@galamarco @PaoloGiustiniani logghiamo o mandiamo anche una notifica per email?

**Comment by PaoloGiustiniani** [comment]
@yakki va benissimo mandare una mail.

Il log di cui parliamo sarebbe stile quello laterale di Django ma da riportare in una sezione apposita dedicata agli admin.

Spesso il supporto è oggetto di contestazione e servirebbe iniziare a registrare le azioni fatte su un utente, anche dal cron.

Hai idee che non ti complichino la vita?

**Comment by yakky** [comment]
@PaoloGiustiniani c'è già a disposizione un model Log (attualmente non accessibile dall'admin) ma che possiamo facilmente visualizzare in questo modo

![schermata3](https://cloud.githubusercontent.com/assets/714711/21974642/37e883fc-dbc8-11e6-99fa-eb80ffbfb4f1.png)

Per quanto riguarda la notifica, sulla terminazione viene già inviata una notifica generica. E' necessario prevederne una specifica, invece?

**Comment by PaoloGiustiniani** [comment]
@yakky perfetto, aggiungiamo l'azione del CRON in questo log e rendiamo disponibile questa pagina in sola lettura ai superadmin (non admin).

**Comment by yakky** [comment]
@PaoloGiustiniani come notifica email lasciamo quella generica o ne inviamo una specifica che dice che la delega è stata terminata per raggiunti limiti di età?

**Comment by PaoloGiustiniani** [comment]
@yakky specifica, almeno evitiamo stati di panico generale.

**Comment by yakky** [comment]
Fixed by #490
