### ISSUE TITLE
[report] sedi giornaliero

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#299]
File xls inviato ogni mattina con i dati dei comitati, modificare le colonne aggiungendo: data ultima modifica scheda comitato e contatto PEC (serve per revisione dati al dipartimento di protezione civile).

**Comment by PaoloGiustiniani** [comment]
@yakky per semplicità ti indico che c'è già un report che fa tutto questo, bisogna solo aggiungere i due campi

**Comment by yakky** [comment]
@PaoloGiustiniani just as your are at it, quale priorità?

**Comment by PaoloGiustiniani** [comment]
@galamarco indicami entro quanto ti serve (se ti serve ancora)

**Comment by yakky** [comment]
questo era marcato per errore tra quelli da verificare. 
Ho aperto la PR, faccilo il merge direttamente su master perché i test su luke si fanno male visto che non partono le email
