### ISSUE TITLE
[provvedimenti] provvedimento da conteggiare in elettorato

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#301]
Verificare che il provvedimento disciplinare venga considerato nella generazione degli elenchi elettorali

**Comment by yakky** [comment]
Non mi risulta sia usato nei filtri (mi riferisco qui https://github.com/CroceRossaItaliana/jorvik/blob/master/ufficio_soci/elenchi.py#L471) 
@AlfioEmanueleFresta ti risulta?

**Comment by luca-dex** [comment]
La schermata di registrazione di un provvedimento è la seguente:

![nuovo provvedimento disciplinare il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/22551990/5583ba66-e957-11e6-882d-6848758c92f7.png)

In linea di massima le date di sospensione le abbiamo a disposizione, quindi non ci sono problemi per aggiungere un filtro relativo a questa situazione. Ricordo che la sospensione è l'unica situazione in cui ha senso parlare di periodo.

Aggiungo, ma meriterebbe una issue a parte, che quella schermata a una serie di problemi:

1. A cosa serve la scelta del comitato
2. Su ammonizione ed espulsione non ha nessun senso il parlare di data di inizio e fine
3. La terminologia non è aggiornata con quella attuale
4. Manca la sospensione cautelativa preventiva alla radiazione

**Comment by yakky** [comment]
@luca-dex sì, concordo. Chiedevo ad alfio solo se mi ero perso qualche pezzo per cui i provvedimenti erano già tenuti in considerazione.
E comunque abbiamo bisogno di sapere come trattarli.
Ovvero come considerare ciascuna tipologia di provvedimento ai fini elettorali

**Comment by luca-dex** [comment]
L'unico provvedimento da considerare è la sospensione

**Comment by yakky** [comment]
PR deployata su luke
