### ISSUE TITLE
[encoding] simbolo € ricevute

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#302]
Nei pdf delle ricevute risulta il simbolo € non codificato.

**Comment by yakky** [comment]
@AlfioEmanueleFresta c'è modo di provare la generazione PDF in locale?

**Comment by yakky** [comment]
@PaoloGiustiniani potete riverificare? Dal sistema di sviluppo (ma con la generazione fatta dal convertiore "vero") il simbolo viene riprodotto correttamente

**Comment by PaoloGiustiniani** [comment]
ora è ok.
