### ISSUE TITLE
[bug] Estensioni/trasferimenti in entrata

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#324]
Gaia comunica al presidente la presenza di un' estensione o un trasferimento in attesa non permette di vedere il documento (PDF) fino a quando il comitato uscente non protocolla la richiesta comunicando un errore di permessi.

**Comment by PaoloGiustiniani** [comment]
CFR DHC-446-54257

**Comment by yakky** [comment]
@PaoloGiustiniani per chiarezza: in questo caso parliamo del presidente del comitato di ingresso, giusto?

**Comment by PaoloGiustiniani** [comment]
@yakky in questo caso il presidente del comitato "in uscita" sta cercando di scaricare il PDF ottenendo un errore di permessi.

La pagina della richiesta è la seguente /anagrafica/trasferimento/9108/ viene scaricato un file in HTML con il classico errore di permessi.

**Comment by yakky** [comment]
@PaoloGiustiniani altri PDF funzionano? Perché gaia non farebbe scaricare il file HTML ma mostra solo la pagina di errore. Potrebbe essere un problema con il service di generazione dei PDF?

**Comment by PaoloGiustiniani** [comment]
@yakky yes, funzionano.

**Comment by AlfioEmanueleFresta** [comment]
@yakky il comportamento dello scaricamento e' giustificato dal tag HTML5 `download` presente nei link di scaricamento, che serve a evitare che la richiesta PDF venga aperta in-browser, e chiede al browser di comportarsi come se la risposta sia stata servita con header HTTP da 'attachment'.
