### ISSUE TITLE
[attivita] zero turni

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#325]
Funzionalita' che permetta al Presidente del Comitato e all'ufficio soci di vedere un elenco dei volontari che non hanno alcuna partecipazione confermata ad una attivita' in un determinato periodo. 

Deve essere accessibile da Soci, implementato con la struttura di tutti gli altri elenchi. Il modulo pre-generazione deve permettere l'inserimento del periodo da ricercare, di default corrispondente agli ultimi 365 giorni (ottieni tutti i volontari del comitati che non hanno fatto servizio tra il X e il Y).

**Comment by yakky** [comment]
PR Caricata su luke
