### ISSUE TITLE
[admin] errore 500

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#327]
> se vai qui https://gaia.cri.it/admin/gestione_file/immagine/124/change/
> imposti come permesso "Tutti i presidenti" e salvi, ti da errore 500.

via @galamarco

**Comment by yakky** [comment]
@AlfioEmanueleFresta non riusciamo a riprodurlo in staging con un file analogo

**Comment by yakky** [comment]
Closed by https://github.com/CroceRossaItaliana/jorvik/pull/373
