### ISSUE TITLE
[admin] importazione flusso volontari down

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#329]
caricando un csv e premendo il pulsante di avvio importazione (solo validazione) il server risponde "server error 500"

**Comment by matthewmazzoleni** [comment]
la problematica sta bloccando l'evasione di molti ticket

**Comment by romolox** [comment]
Sarebbe possibile avere un scv di esempio da provare nell'importazione? Creando un csv di prova non ho riscontrato nessun errore in locale.

**Comment by PaoloGiustiniani** [comment]
@matthewmazzoleni per te.

**Comment by matthewmazzoleni** [comment]
@romolox recupero un file e te lo mando per email

**Comment by romolox** [comment]
Ciao @matthewmazzoleni non ho ricevuto la mail.

**Comment by PaoloGiustiniani** [comment]
@

**Comment by PaoloGiustiniani** [comment]
per ora si chiude.
