### ISSUE TITLE
elenchi: persone estratte più volte

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#33]
utente 1843 è estratto due volte nell'elenco generato da CR di appartenenza. il volontario ha un'appartenenza e un'estensione

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni che elenco esattamente?

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta riscontrato in elenco volontari, ricercando il volontario per cognome. screen in NRQ-112-52356

**Comment by AlfioEmanueleFresta** [comment]
Risolto
