### ISSUE TITLE
[non-soci] blocco operazioni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#330]
risulta possibile per i "soci ordinari" attualmente associati ai CR fare richieste di estensione/trasferimento/etc.. verso altri comitati. serve sistemare la situazione e verificare che i "non soci" abbiano precluse le funzionalità peculiari dei volontari.

**Comment by yakky** [comment]
Collegato a #404

**Comment by yakky** [comment]
@matthewmazzoleni 
Abbiamo bloccato le voci dettagliate nelle varie issue, ma alcune specifiche erano un po' generiche, potete verificare su luke?
