### ISSUE TITLE
[trasferimento] sede di appartenenza errata in pdf

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#331]
sul pdf della richiesta di trasferimento il comitato di appartenenza non è corretto, un volontario ha riscontrato un comitato diverso sia dal suo attuale che da quello di destinazione. controllare contestualmente anche gli altri pdf generati per estensioni, etc...

**Comment by matthewmazzoleni** [comment]
il problema è riscontrato spesso e porta al ritiro delle richieste in quanto considerate errate dai volontari che le effettuano. anche oggi, su richiesta di trasferimento verso una sede, un volontario trova nel pdf come comitato di destinazione quello su cui è esteso attualmente e non quello verso cui ha effettuato richiesta di trasferimento.

**Comment by yakky** [comment]
@matthewmazzoleni il problema si presenta solo nei PDF o anche nelle notifiche?
@AlfioEmanueleFresta anche qui abbiamo il problema che apparentemente la generazione dei PDF non è testabile da locale o su luke

**Comment by matthewmazzoleni** [comment]
@yakky ti direi solo nei pdf

**Comment by AlfioEmanueleFresta** [comment]
@yakky i PDF sono semplicemente dei modelli che vengono renderizzati in HTML. Viene poi fatta una semplice richiesta HTTP POST a un URL (il server di rendering PDF), con un parametro che include tutto il corpo in HTML del documento. La richiesta restituisce un file, che viene scaricato. 

Puoi vedere il tutto qui: https://github.com/CroceRossaItaliana/jorvik/blob/master/base/files.py#L108

Dompdf (il nostro renderer) e' abbastanza tollerante, ma fallisce la generazione del file se l'HTML passato e' particolarmente rotto. Mi preoccuperei di validare che l'HTML passato sia funzionante.

Tieni presente che l'endpoint del server di render e' un URL che fa parte della configurazione di Gaia. Se ti interessa vedere cosa Gaia invia a quell'URL, ti basta cambiare l'URL in locale con qualcosa come un URL generato con Request Bin, https://requestb.in/, che ti logga tutte le richieste.

Se l'HTML e' valido e ben formato, allora mi occupero' di indagare il funzionamento di Dompdf.

**Comment by fmarco** [comment]
@AlfioEmanueleFresta abbiamo un problema, dai nostri ip non riusciamo ad effettuare il rendering

**Comment by fmarco** [comment]
@AlfioEmanueleFresta ci sono aggiornamenti :)? Purtroppo al momento  continuiamo a non poter accedere con successo alla generazione del pdf (accediamo all'endpoint ma l'interfaccia ritorna sempre errore)

**Comment by yakky** [comment]
@matthewmazzoleni hai un codice specifico su cui fare la prova sull'ambiente di test? Provo un cambiamento allineando i trasferimenti a estensioni e riserve per quanto riguarda il recupero della sede di provenienza. Comunque ci va la sede o il comitato?

**Comment by Ele81** [comment]
Un ID che ha avuto questo problema è 90029. Trasferimento di Martedì 21 Febbraio 2017 17:02.

**Comment by Ele81** [comment]
Ho notato che il PDF viene generato male se c'è un estensione attiva.

**Comment by matthewmazzoleni** [comment]
@yakky leggi le considerazioni di @Ele81

**Comment by yakky** [comment]
@Ele81 @matthewmazzoleni anche dopo il deployment della PR collegata?

**Comment by yakky** [comment]
@Ele81 @matthewmazzoleni comunque mi torna che un'estensione potesse generare il problema, che però dovrebbe essere risolto nel codice appena deployato

**Comment by PaoloGiustiniani** [comment]
@yakky django logga qualcosa in fase di generazione pdf o è dompdf che impazzisce? (penso la seconda)

**Comment by yakky** [comment]
@PaoloGiustiniani no, non logga nulla. qui in realtà il PDF non c'entra, era solo la logica nel template sbagliata
