### ISSUE TITLE
[requirements] browser supportati

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#336]
Ciao,
abbiamo necessità ai fini di supporto di avere un elenco dei browser attualmente supportati e relative versioni così da poter dare indicazioni agli utenti.

**Comment by yakky** [comment]
La risposta sensata potrebbe essere: qualunque cosa sufficientemente moderna :D

Volendo dare un dettaglio:
* Internet Explorer 11
* Chrome 50+
* Firefox 45+
* Safari 6+
* Android 4.0
* iOS 8.0

@AlfioEmanueleFresta ti tornano?

**Comment by AlfioEmanueleFresta** [comment]
Manca Edge. Qualunque versione rilasciata va bene. E credo che di fatto supportiamo IE 8+, ma in realta' quello non credo sia comunque supportato piu' da [mammona](https://it.wikipedia.org/wiki/Il_Libro_di_Mozilla) e non ho modo di provarlo.

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta  li mettiamo su una pagina del sito o bastano come informazione qui?

**Comment by yakky** [comment]
ping @matthewmazzoleni @AlfioEmanueleFresta

**Comment by PaoloGiustiniani** [comment]
Direi che possiamo pubblicarli su Gaia @yakky 

Possiamo linkarla all'interno della pagina https://gaia.cri.it/informazioni/ con una pagina dedicata.

E' possibile inserire un alert all'utente qualora la versione utilizzata non sia conforme e rimandarlo per ulteriori informazioni alla pagina dei browser?

**Comment by yakky** [comment]
@PaoloGiustiniani visto che gaia non ha specifiche richieste di browser (l'elenco sopra è solo una lista di browser decenemente moderni che chiunque non voglia essere affogato dagli 0day dovrebbe usare), l'idea del popup mi sembra una noia eccessiva per gli utenti, oltre alle note difficoltà di fare browser sniffing in modo corretto e pulito

**Comment by PaoloGiustiniani** [comment]
Ok allora basterebbe solo la pagina.
