### ISSUE TITLE
[validazioni] evitare lowercase backend

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#337]
in taluni campi, ad esempio nome e cognome, il backend sostituisce i case in modo indiscriminato impedendo la gestione di cognomi come D'Angelo.

**Comment by AlfioEmanueleFresta** [comment]
Direi piuttosto di prevedere l'eccezione dell'apostrofo. Il metodo @alfiomusmarra mi sembra prevedesse una cosa tipo `.replace("'", "' ").title().replace("' ", "'")`.

**Comment by yakky** [comment]
@AlfioEmanueleFresta @matthewmazzoleni aperta PR per correggere il problema, non risolto completamente dalla #233

**Comment by yakky** [comment]
PR deployata su luke

**Comment by yakky** [comment]
@PaoloGiustiniani idem qui, va ricreato l'ambiente

**Comment by PaoloGiustiniani** [comment]
bulding in corso

**Comment by PaoloGiustiniani** [comment]
@luca-dex http://pr-550.sviluppo-gaia.ovh/
