### ISSUE TITLE
[struttura] revisione struttura comitati

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#338]
è necessario preparare una query che, tenuto conto delle situazioni di eccezione indicate dallo statuto, riassoci correttamente i Comitati ai rispettivi Comitati Regionali (campo Padre).

Eventuali Comitati Ex-Provinciali rimangono associati (a questo punto senza figli) al Regionale, quindi non subiscono modifiche.

questo genera (ad esempio) situazioni tipo in cui i comitati mostrati sono quelli a livello provinciale tranne quelli per cui è stata richiesta esplicitamente la modifica a seguito della trasformazione del provinciale:

![img_7409](https://cloud.githubusercontent.com/assets/5826472/16562719/a0513538-41fe-11e6-8744-b7c3cc7f4c0a.JPG)

NB: Tenere conto dei casi particolari dello statuto: Area Metropolitana di Roma, Trento, Aosta..

**La query potrà essere lanciata solo dopo aver bonificato la chiusura degli eventuali comitati provinciali aboliti e non più attivi**

**Comment by matthewmazzoleni** [comment]
serve pianificare quanto prima un incontro per la gestione della situazione

**Comment by galamarco** [comment]
> @matthewmazzoleni  Eventuali Comitati Ex-Provinciali rimangono associati (a questo punto senza figli) al Regionale, quindi non subiscono modifiche.

Salvo però sedi sotto di loro che restano figli legittimi a differenza dei Comitati sotto di loro che passano sotto il regionale

**Comment by luca-dex** [comment]
Anche la situazione di Pavia è estremamente problematica.

![whatsapp image 2016-11-25 at 17 33 31](https://cloud.githubusercontent.com/assets/3315913/20631158/8fe8d3e2-b335-11e6-8032-7c42318cd5c4.jpeg)

**Comment by luca-dex** [comment]
@galamarco la situazione dell'alberatura dei Comitati è sempre più critica https://gaia.cri.it/informazioni/sedi/ e il problema non è risolvibile da pannello admin.

Oltre a ciò viene segnalato che i comitato flaggati come nascosti (ex provinciali) tornano visibili lato utente diverse persone si stanno trasferendo / estendendo su comitato fantasma.

La situazione sta diventando critica, pareri da @matthewmazzoleni @AlfioEmanueleFresta @PaoloGiustiniani @yakky

**Comment by luca-dex** [comment]
Come segnalato da Ilaria e verificato da @PaoloGiustiniani, anche provando a correggere da pannello admin la gerarchia dei comitati, impostando correttamente i padri, le modifiche non vengono salvate e la situazione torna sempre la stessa.

**Comment by galamarco** [comment]
I contratti sono alla firma, ma non ancora firmati. Ho sollecitato venerdì scorso il Segretario Generale segnalandogli le implicazioni che l'attuale situazione ha. Ne è consapevole ed ha indirizzato il tutto verso l'amministrazione e relativi responsabili per concretizzare le procedure.
Oggi ancora ho rinnovato la richiesta mettendomi a disposizione per ulteriori, ma per il momento non ho riscontri di alcun tipo.
Temo che non resti che attendere con tutte le implicazioni del caso.

**Comment by yakky** [comment]
Provo a riassumere:
Tutti i comitati (locali, quindi **non** le unità territoriali) devono essere modificati in modo che siano associati al regionale del proprio provinciale, anziché al provinciale stesso.
Le unità territoriali invece rimangono come sono

E' corretto @AlfioEmanueleFresta ?

**Comment by matthewmazzoleni** [comment]
corretto @yakky: gli attuali "Comitato Locali" devono essere direttamente dipendenti dal proprio regionale. a parte l'automatismo ti direi di tenere in considerazione il problema di impossibilità al salvataggio segnalato da @luca-dex e eventualmente prevedere che alcuni comitati non vengano migrati (magari facciamo un elenco con @galamarco )

**Comment by galamarco** [comment]
Per non incorrere in errori ricordiamoci dei tre casi particolari ovvero:

- comitato della provincia automa di Trento
- comitato della provincia automa di Bolzano
- comitato dell'area metropolitana di Roma Capitale

Mentre i primi due sono da considerarsi regioni, Roma deve essere una provincia (dentro il Comitato Regionale del Lazio) con sotto i suoi comitati territoriali (Roma 1, Roma 2, Roma 3 ecc...) ed eventuali unità territoriali dipendenti direttamente dal Comitato dell'Area Metropolitana e agganciati invece ai Comitati 1,2,3.
In caso di dubbi su questo sentiamoci.

**Comment by yakky** [comment]
@galamarco forse meglio. Ho bisogno di sapere il nome esatto dei comitati comunque perché non avendo i dati devo fare le cose un po' alla "cieca".

**Comment by luca-dex** [comment]
@yakky a livello prettamente informatico, considera solo la struttura ad albero. La cosa importante è che ogni nodo dell'albero abbia il giusto padre, indipendentemente da chi sia il padre. A volte i Comitati sono figli di un Regionale, a volte del Nazionale e a volte sono figli di un altro Comitato. 

Per risolvere i problemi relativi alla struttura dei comitati deve essere possibile effettuare anche altre operazioni:
* situazione in cui un'unità territoriale va spostata da un Comitato all'altro (che corrisponde a quella situazione in cui un'unità territoriale viene elevata a livello di comitato)
* situazione in cui va fatto un merge degli elenchi dei volontari di due comitato (ad esempio in questo momento ci sono Comitato con lo stesso nome e a seguito di trasferimenti ci sono persone che si sono distribuite su entrambi i comitati, questo ha comportato a situazione in cui alcuni volontari si sono persi del tutto)

**Comment by yakky** [comment]
@galamarco @luca-dex per questo è meglio sentirci perché probabilmente è più complesso di come sviluppato inizialmente e ho bisogno di capire cosa serva effettivamente

**Comment by galamarco** [comment]
il mio numero è sempre 3346519290 se avete bisogno chiamatemi pure

**Comment by luca-dex** [comment]
Stiamo facendo un po' di test per capire la problematica perché non è
banale. Ci stiamo lavorando tutti quanti, appena ci saranno sviluppi
riporteremo qua la situazione.

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex 

> @yakky a livello prettamente informatico, considera solo la struttura ad albero. La cosa importante è che ogni nodo dell'albero abbia il giusto padre, indipendentemente da chi sia il padre. A volte i Comitati sono figli di un Regionale, a volte del Nazionale e a volte sono figli di un altro Comitato.

Intendi *Sede* figlia di un altro Comitato, giusto? O mi sono perso qualcosa di fondamentale?

**Comment by luca-dex** [comment]
Area metropolitana di Roma capitale: comitati territoriali (municipi) con
sedi, figli di un comitato (comitato area metropolitana) a sua volta figlio
del regionale (lazio).

Unica anomalia nella gerarchia.

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo ho caricato una PR con un comando per eseguire il rebuild, che è già stato eseguito su luke. Controllate se la gerarchia torna e gli spostamenti si possono eseguire correttamente?

**Comment by luca-dex** [comment]
La gerarchia torna. Non riesco a fare prove sugli spostamenti perchè non sono admin @PaoloGiustiniani dammi supporto o verifica tu.

**Comment by PaoloGiustiniani** [comment]
io ho fatto alcune prove spostando i comitati e pare che funzioni

**Comment by yakky** [comment]
Ok, quindi direi che si può fare il merge di quel comando e lanciarlo in produzione
