### ISSUE TITLE
US (e altre): conseguenze fusione della sede principale con comitato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#34]
a seguito dell'accorpamento dell'unità principale del comitato nel comitato stesso i delegati di singole unità territoriali hanno ora permesso di visualizzazione su intero comitato.

**Comment by AlfioEmanueleFresta** [comment]
Io voto per tenere i permessi in questo modo, perche':
- Evita la necessita' della sede territoriale fittizia
- La delega data dal presidente dovrebbe avere stessa estensione della delega di presidenza stessa
- Si possono comunque tenere delegati territoriali, ma i delegati del CL gestiscono tutto il CL

Si potrebbe pensare a sviluppare, per i casi in cui i CL preferiscono, la possibilita' di avere l'unita' territoriale fittizia

**Comment by matthewmazzoleni** [comment]
prima era possibile dare delega su tutto il comitato o solo su singola sede, il problema principale non è la possibilità di creare deleghe granulati, bensì l'aver allargato l'accesso (in particolare di US) a soci il cui presidente aveva volutamente limitato a singola US. (i ticket aperti sono in tal senso, infatti). la funzionalità di per se è secondaria come problema, perché comunque prima presente e ora no. ps: esistono i delegati anche nelle unità territoriali, e quello dell'unità principale non ha competenza sulle unità territoriali. ogni sede, anche la principale, per le deleghe di area vale singolarmente.

**Comment by matthewmazzoleni** [comment]
aggiungo le considerazioni estratte da LPN-700-50619:

- sede del comitato e sede dei volontari possono non collimare (come prima)
- è necessario che le sedi abbiano la possibilità di avere proprio US (come prima)

**Comment by AlfioEmanueleFresta** [comment]
Tutte le deleghe sono state portate a `UFFICIO_SOCI` o la nuova `UFFICIO_SOCI_TERRITORIALE` sulla base della precedente struttura dei Comitati.
