### ISSUE TITLE
[Centrale Operativa] Escalation permessi utente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#343]
Al volontario basta creare una attività impostando "attività di centrale operativa" su "Automatica", creare un turno e registrarsi nello stesso. Durante la validità del turno avrà accesso alle funzioni di CO, anche se non è stato delegato a tale funzione.

**Comment by AlfioEmanueleFresta** [comment]
E' necessario fare in modo che, se l'utente non ha permessi di centrale operativa, non gli sia possibile modificare la proprieta' nella modifica di una attivita'.

**Comment by romolox** [comment]
@AlfioEmanueleFresta il controllo sulla delega centrale operativa va fatto solo sulla sede dell'attività o anche sugli ancestors selezionabili nel menù? Immagino che fare il controllo sulla sede sia quello più restrittivo.

**Comment by PaoloGiustiniani** [comment]
@yakky puoi dare priorita` a questa issue?
