### ISSUE TITLE
[quote] impossibile pagare quota per volontario iscritto dopo il 30 aprile

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#344]
ai volontari inseriti nel sistema dopo il 30 aprile (o convertiti dal sistema a seguito di passaggio da corso di accesso) non è possibile registrare la quota. se un volontario entra in cri dopo la chiusura del periodo di registrazione quote deve comunque essere possibile emettere una quota.

**Comment by yakky** [comment]
@AlfioEmanueleFresta questo come si "concilia" con la richiesta in #269 (che è l'origine di questa segnalazione)

**Comment by luca-dex** [comment]
@yakky ci sono due distinte situazioni:
* le persone che già sono volontari della croce rossa devono rinnovare la quota entro la data fissata come fine tesseramento (de dovrebbero poterlo fare solo fino a che il tesseramento è aperto). Questo è ciò che avviene in maniera corretta (a quanto mi risulta).
* i *nuovi volontari*, devono poter pagare la quota in qualsiasi momento successivo alla data in cui sono diventati volontari (e quindi soci ordinari).

Quando dico *nuovi volontari* intendo quelli che diventano volontari dopo aver terminato con esito positivo un corso base e che prima erano aspiranti o sostenitori.

@AlfioEmanueleFresta potrei fare confusione con gli attuali attributi delle persone, quindi correggi quello che dico se ho fatto confusione.

**Comment by yakky** [comment]
@luca-dex grazie della precisazione. Va allora inserita una logica che permetta di bypassare il controllo nel caso 2)

**Comment by yakky** [comment]
@luca-dex vedi #395 
Ne faccio un deployment su luke così puoi fare dei test reali

**Comment by luca-dex** [comment]
@yakky perfetto, fammi sapere quando posso fare qualche prova, così entro sera ti fornisco un riscontro

**Comment by yakky** [comment]
@luca-dex deployment su luke fatto. puoi fare i test

**Comment by PaoloGiustiniani** [comment]
@luca-dex up 👍

**Comment by luca-dex** [comment]
Vedi la pull request relativa. I test sono fatti e gli esiti sono lì
