### ISSUE TITLE
Sedi CRI: mancata visualizzazione unità territoriali

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#35]
il presidente 12936 visualizza nel suo pannello sedi solo una delle unità territoriali del suo comitato. non pare vi siano differenze tra le sedi, aprendone il dettaglio lato admin

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni 12936 non mi risulta essere presidente

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta 14038 
PIJ-716-58749

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni e' presidente di un regionale, piuttosto che provinciale/locale, quindi le sedi sotto non sono unita' territoriali sulle quali ha permessi, bisogna spostare le deleghe a livello provinciale/locale

**Comment by matthewmazzoleni** [comment]
ok, ad ogni modo vede nell'elenco una sede territoriale locale, quindi è errato che la veda

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni il presidente e' anche presidente di Trento.
