### ISSUE TITLE
[permessi] login as user

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#350]
Ciao @yakky ,
come concordato telefonicamente in aggiunta a #290 abbiamo la necessità che il permesso sopra indicato sia delegabile e non gestibile unicamente assegnando il privilegio di super amministratore.

Grazie.

**Comment by yakky** [comment]
Questo si può gestire configurando opportunamente loginas https://github.com/stochastic-technologies/django-loginas#configuring

**Comment by romolox** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta @yakky  Ecco qua la merge request:
https://github.com/CroceRossaItaliana/jorvik/pull/354

**Comment by yakky** [comment]
Chiuso da #354
