### ISSUE TITLE
[aspiranti] notifiche post superamento corso

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#356]
Gli aspiranti che hanno correttamente superato il corso base continuano a ricevere comunicazioni di nuovi corsi.

Ho verificato che non viene cancellato l'oggetto nella sezione aspiranti, post superamento corso.

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani Hai ID di casi?

**Comment by PaoloGiustiniani** [comment]
Ciao, si abbiamo numerose casistiche a riguardo.

es. IEF-822-11520

**Comment by PaoloGiustiniani** [comment]
@yakky l'utente che ha segnalato la problematica è presente nella pagina /formazione/aspirante/ nello specifico il suo ID è 36381

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo  qualcuno può controllare qual è lo stato dell'utente riguardo ad appartenenze, stato aspirante e partecipazioni corso base? Potrebbe essere registrato come aspirante ma poi inserito come volontario con procedura manuale?

**Comment by PaoloGiustiniani** [comment]
@yakky ha un' appartenenza da volontario.

Presumo sia stato reclamato.

Come vogliamo procedere?

**Comment by luca-dex** [comment]
Forse deriva dal reclama persona che permette di reclamare anche sostenitori e aspiranti che è stato aggiunto qualche giorno fa..

**Comment by yakky** [comment]
@luca-dex questa issue è di settembre, quindi credo derivi da un reclama fatto prima di allora (gli aspiranti erano reclamabili anche prima)

Se vi va bene prepareremmo una modifica che:
* Esclude gli aspiranti che sono anche volontari dalle notifiche
* Aggiunge un comando che cancella il profilo aspirante per tutti coloro che sono anche volontari

**Comment by PaoloGiustiniani** [comment]
@luca-dex presumo che la prima sia per il passato

**Comment by yakky** [comment]
diciamo che un doppio livello. Il comando può essere messo nel cron ma è forse un po' "delicato", quindi la prima ci mette al riparo negli intervalli di esecuzione del comando

**Comment by yakky** [comment]
Visto anche il collegamento con #571 facciamo un supplemento di analisi che cosa succeda all'atto del reclamo di un aspirante e poi facciamo il push di un fix per entrambe le issue

**Comment by romolox** [comment]
@PaoloGiustiniani @luca-dex abbiamo pronta una pull request per questo problema:
https://github.com/CroceRossaItaliana/jorvik/pull/588

**Comment by PaoloGiustiniani** [comment]
Riapro come da https://github.com/CroceRossaItaliana/jorvik/pull/588#issuecomment-307549998

**Comment by yakky** [comment]
@PaoloGiustiniani riesci a verificare se quelle occorrenze avevano completato o meno il corso base? Perché i test (automatici e manuali) dicono che al passaggio di corso l'oggetto aspirante viene effettivamente cancellato.
Potrebbero essere persone che si sono registrate come aspiranti e che poi sono state reclamate senza passare dal corso?

**Comment by luca-dex** [comment]
Onestamente io ricordo che nei test fatti alle persone reclamate veniva cancellata l'appartenenza da aspirante. Magari è stato modificato qualcosa e questo non avviene più, però mi pare strano.

**Comment by yakky** [comment]
La PR collegata non modifica questo aspetto, e il codice fa la cosa giusta:
* https://github.com/CroceRossaItaliana/jorvik/blob/master/formazione/models.py#L346
* https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/models.py#L646

Per questo secondo me bisogna verificare se i casi cancellati sopra sono reclamati anziché essere passati per il corso
La PR comunque impedisce l'invio delle notifiche, quindi aprirei una segnalazione separata

**Comment by PaoloGiustiniani** [comment]
Per ora limitiamoci a wrappare il cron.

**Comment by yakky** [comment]
@PaoloGiustiniani vedi #624

**Comment by yakky** [comment]
Chiusa con #624
