### ISSUE TITLE
[documenti] segnalazione errata menù attivo

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#359]
quando è aperta la sezione "documenti" come vedete nello screen associato viene erroneamente segnalato attivo il menù sinistro laterale "documenti" che però identifica altra cosa (i documenti personali del volontario)

![image](https://cloud.githubusercontent.com/assets/5826472/18353971/38fb1812-75e4-11e6-8f74-c5e2a3ba405f.png)

**Comment by yakky** [comment]
@matthewmazzoleni @luca-dex il fix è disponibile su luke
