### ISSUE TITLE
[email] email massiva da quote non pagate richiede utenti

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#360]
cercando di inviare una mail massiva il sistema informa l'utente che il messaggio cumulativo verrà inviato a X persone. nella maschera successiva, contrariamente a quanto ci si aspetta, viene richiesto l'inserimento dei destinatari.

![image](https://cloud.githubusercontent.com/assets/5826472/18356311/83185e20-75ec-11e6-905e-30c6303e7547.png)

**Comment by yakky** [comment]
Confermato. E' un problema di salvataggio dei dati in sessione

**Comment by yakky** [comment]
Corretto da #567
