### ISSUE TITLE
[tesserini] vari problemi segnalati

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#361]
segnalano vari problemi da vari comitati:
- sparizione di elenchi di persone per cui è stato richiesto il tesserino, essi sono negli elenchi di chi ancora non l'ha richiesto. in caso venga chiesto nuovamente parte email che indica la richiesta di ristampa anche a fronte della non stampa iniziale.
- l'elenco dei volontari per cui richiedere il tesserino è vuoto

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni puoi raccogliere degli ID da qualche caso, cosi' da poterci costruire dei test sopra?

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta 170653 è stato richiesto ma ricompare in quelli da emettere. non ho id precisi perché la cosa non interessa utenti specifici ma interi comitati e quindi non ci viene detto l'id della persona.

per il punto "l'elenco dei volontari per cui richiedere il tesserino è vuoto" non posso chiedere id

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta senza l'accesso ai dati reali non riusciamo a fare un'analisi di questo problema

**Comment by Paxmu77** [comment]
@yakky se vuoi puoi entrare nella mia pagina Paolo mussino cl valli di lanzo, vedrai nella sezione soci\tesserini che parecchi nomi sono nella sezione "da richiedere" ma non e possibile farlo

**Comment by AlfioEmanueleFresta** [comment]
@Paxmu77 sono spiacente per la problematica riscontrata, ma questo strumento e' riservato agli sviluppatori -- per favore fai riferimento al servizio di supporto per ottenere assistenza, descrivendo se possibile cosa intendi per 'non e possibile farlo', inclusi i messaggi di errore completi che ottieni, se applicabile.

**Comment by yakky** [comment]
@AlfioEmanueleFresta per il punto 1) c'era un flag errato nel filtro, che causava sia la scomparsa da quelli richiesti che la permanenza in quelli da richiedere (perché sono uno il reciproco dell'altro)
Non riesco invece a riprodurre il secondo

**Comment by yakky** [comment]
@AlfioEmanueleFresta @luca-dex aperta PR e caricato su luke

**Comment by yakky** [comment]
Risolto da #568 come da https://github.com/CroceRossaItaliana/jorvik/pull/568#issuecomment-280936275
