### ISSUE TITLE
[form] modifica all'interazione utente con i form

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#362]
è necessario bloccare l'effetto dello scroll sui campi data, in quanto è molto comune che scrollando con il mouse la pagina esso, passando su tali campi, modifichi la data senza che l'utente se ne accorga. abbiamo moltissimi casi, visionati anche personalmente. 

questo di fatto crea errori nei dati e gli utenti non ne sono consapevoli

**Comment by yakky** [comment]
Corretto da #393
