### ISSUE TITLE
[tesserini - elenchi] generazione per singolo foglio non funziona correttamente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#363]
nella pagina https://gaia.cri.it/us/tesserini/senza-fototessera/ la generazione di file excel "per singola sede" produce in realtà un foglio unico cumulativo.

**Comment by AlfioEmanueleFresta** [comment]
Questo era il caso con tutti e tre gli elenchi relativi ai tesserini (Da richiedere, senza fototessera, richiesta effettuata)
