### ISSUE TITLE
[stampa tesserini] assistenza configurazione stampante

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#364]
ciao
viene segnalato che, a fronte della stampante presente nell'ordinanza relativa ai tesserini, non risulta possibile impostarla in modo da ottenere risultati rispecchianti la qualità aspettata dei tesserini. diversi comitati regionali richiedono supporto a riguardo.

riferimento: YIR-696-58857

**Comment by yakky** [comment]
@matthewmazzoleni che supporto possiamo dare? @AlfioEmanueleFresta ti invoco per consiglio!

**Comment by matthewmazzoleni** [comment]
non saprei @yakky vedrei se @AlfioEmanueleFresta ha suggerimenti a riguardo

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni abbiamo affrontato da tempo questa questione. Siamo ai limiti del fattibile. Noi semplicemente prendiamo l'immagine di sfondo (8-bit PNG) e ne generiamo un PDF, con del testo vettoriale di sopra. Facciamo di tutto per fare in modo che il PDF non venga rasterizzato, ma c'e' un limite. 

Non vi e' nulla di nascosto nella tecnica di generazione del tesserino -- il problema ottenuto dal tesserino generato con Gaia e' lo stesso problema che si ottiene stampando lo sfondo del tesserino direttamente come immagine (nostro formato di origine) sul supporto plastico.

Credo che per migliorare la qualita' del tesserino, bisogna andare a lavorare sulla immagine di sfondo (profondita' colore, e colori piu' adatti alla stampa su plastica lucida, che il rosso semitrasparente pare non essere). Questo e' fuori dalla nostra portata. Riguarda l'associazione e, quindi, @galamarco :)

Bisogna fare una chiamata di giudizio: se la qualita' ottenuta *tweak-ando* le impostazioni della stampante e' buona abbastanza, o se vale la pena spendere per fare commissionare un nuovo design.

**Comment by luca-dex** [comment]
Potrebbe aver senso separare lo sfondo dai dati? Magari acquistando i tesserini con lo sfondo prestampato e andando a generare un pdf che contiene solo i testi e il barcode, questa cosa si risolverebbe. Quello che vedo spesso in giro è che si utilizzano tesserini con lo sfondo già fatto e che chi stampa, stampa solamente i dati.

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex questo e' un problema separato, che crea vantaggi in *alcuni* casi (non nei casi delle stampanti economiche che non sono preparate a fare questa doppia passata, pero'). 

Come scrivevo sopra, stampare lo sfondo a se stante nel formato che ci e' stato fornito, produce un tesserino di stessa qualita'.

**Comment by AlfioEmanueleFresta** [comment]
> andando a generare un pdf che contiene solo i testi e il barcode

Ti stai scordando che il tesserino CRI ha la fotografia del volontario in fronte...

**Comment by luca-dex** [comment]
Il senso era: compriamo dei tesserini con lo sfondo già stampato (le aziende lo fanno e ti garantiscono la qualità dello sfondo), e noi ci mettiamo foto (che continuerà ad essere un po' brutta, ma anche su patente / ci / tessere universitarie e similari è brutta), dati e barcode.

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex non credo che la fattibilita' di quanto hai scritto sia mai stata messa in dubbio. A questo punto, considerando pure che tutte le spese sono state fatte, e' una scelta dell'organizzazione e non tecnica.

**Comment by luca-dex** [comment]
Sì s', sono d'accordo. Questa proposta permetterebbe di risolvere il problema dello sfondo senza praticamente modifiche a gaia (solo avere la possibilità di avere anche una stampa senza sfondo) e senza variazioni nelle stampanti in possesso dei comitati, perchè si tratterebbe solo di variare i materiali di consumo usati (badge prestampati al posto di badge bianchi). Era solo una proposta btw. Per il resto concordo con te che il problema non sia di Gaia.

**Comment by yakky** [comment]
@AlfioEmanueleFresta @luca-dex . Viste le conclusioni, questa segnalazione va chiusa o spostata fuori dal perimetro della manutenzione?
