### ISSUE TITLE
[permessi] amministratore - super amministrazione

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#365]
Attraverso la pagina utenza è possibile delegare ad una persona permessi da amministratore o super amministratore, attualmente chiunque abbia permessi in modifica su quella pagina può effettuare tale nomina.

Bisognerebbe modificare quanto indicato consentendo l'assegnazione di questi permessi unicamente a chi ha permessi di super amministratore.

**Comment by yakky** [comment]
Fixed by #394

**Comment by PaoloGiustiniani** [comment]
Ciao @yakky,
ho verificato: risulta che un utente non super-amministratore possa comunque gestire i permessi di un utente come "Gruppi" & "Privilegi utente". Anche ciò dev'essere inibito.

**Comment by yakky** [comment]
#365 aggiunge anche quelli
