### ISSUE TITLE
[contatori soci] elenchi differiscono da totale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#366]
generando l'elenco dei soci del comitato essi non corrispondono al contatore presente nel menù cosi, etichetta "soci attivi". entrambi questi numeri differiscono anche dall'elenco dei volontari (inclusi gli estesi) quindi non è un mero problema di etichette del campo ma di qualche condizione di conteggio.

es: comitato 225

**Comment by AlfioEmanueleFresta** [comment]
Guardando il codice (https://github.com/CroceRossaItaliana/jorvik/blob/master/ufficio_soci/elenchi.py#L138) mi pare di capire gli elenchi siano questi:

* Elenco Soci: Chiede un giorno e ritorna tutti i soggetti che, per almeno un secondo del giorno selezionato, sono stati registrati come volontari o soci ordinari (N/A), **questo non include i volontari estesi in ingresso**,
* Elenco 'Volontari Attivi': Ritorna tutti i soggetti che, per almeno un secondo del giorno attuale, sono stati registrati come volontari, oppure volontari o estesi in ingresso (se scelto in modulo), **questo include i volontari estesi in ingresso**.

Come dovrebbero essere invece processati gli elenchi, a tuo avviso, @matthewmazzoleni?

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta il problema non è il filtro di estrazione, ma il fatto che quanto indicato dal contatore non corrisponde ai record estratti dalla lista generata (e di conseguenza l'excel). quindi, a fronte di condizione corretta di conteggio, la domanda è "perché non vi sono un numero corrispondente di righe nella generazione lista/excel?"

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni avevo male interpretato la tua segnalazione, perdomani. Sembra che il problema sia in una differenza tra:

* https://github.com/CroceRossaItaliana/jorvik/blob/master/ufficio_soci/elenchi.py#L180
* https://github.com/CroceRossaItaliana/jorvik/blob/master/ufficio_soci/viste.py#L43

Credo che la differenza possa essere una delle due:

* (Probabile?) L'elenco dei volontari usa `distinct` sulla persona nel caso di piu' appartenenze attive. Questo e' strano e potrebbe essere causato da errori nel database, ma spiegherebbe perche' l'elenco ha un numero inferiore rispetto alla home dell'US,
* Il metodo di risoluzione che porta le sedi con permesso come `args[0]` nell'elenco volontari potrebbe differire. Ne dubito perche' avrebbe sintomi molto piu' visibili (sia in unit test, che in segnalazioni, ovvero mancherebbero sedi negli elenchi).

**Comment by yakky** [comment]
Siamo riusciti a riprodurre il problema creando più appartenenze come volontario, a causa dell'assenza del distinct. 
Che ne dite se aggiungiamo i distinct nella home US? Peraltro anche -e sopratutto- il contatore delle persone ha lo stesso problema (solo che in questo caso conteggia tutte le appartenenze, multiple, ovviamente)

**Comment by yakky** [comment]
Ping @AlfioEmanueleFresta

**Comment by yakky** [comment]
Ping @AlfioEmanueleFresta :)

**Comment by luca-dex** [comment]
Ping @AlfioEmanueleFresta :)

**Comment by AlfioEmanueleFresta** [comment]
Siete due scassaca... 🏓 

@yakky si, mi sembra ottimo

**Comment by yakky** [comment]
PR Aperta e disponibile su luke

@AlfioEmanueleFresta :bowtie:
