### ISSUE TITLE
[corsi base] Impossibile iscrivere sostenitori a corso base di altro comitato

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#368]
Attualmente Gaia consente l'iscrizione dei sostenitori di un comitato solo ed esclusivamente ai corsi base di quel comitato. Non essendo possibile in nessun modo "dimettere" o "eliminare" un sostenitore dall'elenco sostenitori di un comitato, non c'è possibilità che quella persona venga iscritta ad un corso base presso un'altra sede.

Sarebbe necessario:
- permettere ai sostenitori che sono anche utenti abilitati di potersi iscrivere ad un corso base
- permettere a chi organizza corsi base di iscrivere sostenitori che non sono del suo comitato, in alternativa questa seconda richiesta potrebbe essere gestista consentendo la cancellazione della persona dall'elenco dei sostenitori di un comitato, per permettere che venga inserita in un altro

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex non ricordo di aver pensato tale restrizione, ne' di averla mai implementata. Non dovrebbe esserci alcun problema per un sostenitore di divenire sostenitore presso un altro comitato, ne' di iscriversi in autonomia ad un corso base presso un altro comitato.

La problematica semplicemente puo' nascere se il sostenitore e' gia' iscritto ad un corso che e' in corso, che attualmente e' da gestire con il verbalizzare, con la non presenza dell'aspirante al corso (che va di pari passo con le mille promesse fatte fare al direttore una volta che iscrive il discente).

Chiaramente se il tizio vuol fare un altro corso attualmente bisogna passare dal supporto, che immagino sia la cosa che vuoi migliorare?

**Comment by luca-dex** [comment]
Se provi ad iscrivere come sostenitore la persona in un altro comitato, ottieni il messaggio di errore del codice fiscale già presente. 

Se provi ad isciverlo dal pannello del corso base non lo trovi perché non è tra i tuoi sostenitori. 

Non c'è modo di chiudere l'appartenenza di un sostenitori a livello di ufficio soci, quindi questa problematica non sembra sia gestibile in autonomia dagli utenti di gaia. 

Mi sto perdendo io qualche passaggio?

**Comment by AlfioEmanueleFresta** [comment]
No, no, cioe'. Al meglio della mia conoscenza l'essere sostenitore non ha niente a che vedere con l'essere un discente per il corso base. Ma attualmente in ogni caso bisogna passare dal supporto, quindi bisogna sistemare.

**Comment by luca-dex** [comment]
@yakky questo è l'altro di quelli urgenti relativo ai corsi base

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta ho aumentato corrispondentemente il livello di priorità

**Comment by yakky** [comment]
@AlfioEmanueleFresta la restrizione deriva da https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/autocomplete_light_registry.py#L39-L41
Nel caso dei sostenitori quindi deve essere saltato il filtro sulle sedi attuali? Oppure solo nel caso dell'iscrizione ai corsi?

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta non mi risulta attualmente possibile ad un sostenitore iscriversi autonomamente ad alcun corso base. E' corretto?

**Comment by AlfioEmanueleFresta** [comment]
> @luca-dex @AlfioEmanueleFresta non mi risulta attualmente possibile ad un sostenitore iscriversi autonomamente ad alcun corso base. E' corretto?

Non a meno che sia anche un aspirante, e non c'e' modo una volta iscritto d'ufficio come sostenitore di iscriverti come aspirante, attualmente, e' infatti solo possibile al momento di iscrizione autonoma.
