### ISSUE TITLE
[email] email recapitate più volte

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#370]
abbiamo segnalazioni da vari utenti di email ricevute più volte a fronte di unico invio. 
email inviata il 20 set 2016, alle ore 13:19 con oggetto "Centro di Temporanea Accoglienza"

**Comment by luca-dex** [comment]
Confermo che mi è capitato in diverse situazioni, l'ultima: 31 agosto, oggetto "Aggiornamento su impiego volontari per sisma centro Italia" delle 12.38

**Comment by capste** [comment]
Ciao Matthew,
TI confermo che la mail di Maristella l’ho ricevuta tre volte sullo stesso indirizzo alle 15:33, alle 19:54 e alle 20:04.


Cappello Stefano
Via Karl Marx 20
20068 Peschiera Borromeo (MI)
cell: 338.5838059
mail: steph@steph.it
Skype: capste66

**Comment by AlfioEmanueleFresta** [comment]
Grazie per la segnalazione @matthewmazzoleni  -- questo va indagato come caso in #345, che ha gia' priorita' urgente.
