### ISSUE TITLE
elenchi: non mostrati volontari trasferiti

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#38]
aprendo elenco trasferiti del comitato non vengono mostrati risultati (verificato che su ex gaia erano estratti 16 risultati)

**Comment by AlfioEmanueleFresta** [comment]
Attualmente l'elenco mostra correttamente i volontari che:
- **non** sono attualmente membri del CL,
- hanno una o piu' appartenenze passate nel CL con terminazione per trasferimento impostata

Quindi ad esempio trasferimenti intra-CL non vengono mostrati. E' questo il problema?

**Comment by matthewmazzoleni** [comment]
non direi, io nel mio CP non vedo alcun trasferimento nonostante gente si sia trasferita fuori provincia. puoi vedere su vecchio gaia con mio utente

**Comment by luca-dex** [comment]
Confermo che non vedo nessuno dei miei vecchi volontari che si sono trasferiti in altro comitato (abbiamo una sola sede, quindi non ci sono problemi relativi a trasferimenti interni).

Confermo che sulla vecchia versione di gaia questi volontari venivano mostrati.

**Comment by dan-it** [comment]
Vedi ad esempio utente 169558, il suo storico appartenenze è corretto ma non compare tra i trasferiti del comitato precedente.

**Comment by AlfioEmanueleFresta** [comment]
Grazie per il feedback. @luca-dex e @dan-it potete confermarmi la risoluzione del problema qui?
http://chewbacca.staging.sviluppo-gaia.ovh/us/elenchi/trasferiti/

Se mi date conferma mando la modifica in produzione.

**Comment by dan-it** [comment]
Sembra meglio, vedo ex-soci del mio comitato, poi trasferiti. Sembrano tutti ma vado a memoria.

**Comment by luca-dex** [comment]
Anche a me a occhio sembra ok

**Comment by AlfioEmanueleFresta** [comment]
Grazie mille. In produzione.
