### ISSUE TITLE
[sedi] errore apertura dettaglio e visualizzazione mappa

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#381]
Accedendo all'elenco Sedi, selezionando Comitato di Castelnuovo Don Bosco e Piovà Massaia (AT), compare "errore server 500". link: https://gaia.cri.it/informazioni/sedi/italia-piemonte-asti-castelnuovo-don-bosco-e-piova/?embed=False
Inoltre non compare la bandierina della Sede di Piovà Massaia (AT) afferente al Comitato sopraindicato, localizzata in " Piazza Guglielmo Marconi, 2, 14026 Piovà Massaia AT, Italia"

**Comment by romolox** [comment]
Purtroppo non posso riprodurre l'errore senza dati reali @AlfioEmanueleFresta @PaoloGiustiniani

**Comment by PaoloGiustiniani** [comment]
@AlfioEmanueleFresta puoi allineare l'ambiente di test e fornire un' utenza a @romolox

**Comment by AlfioEmanueleFresta** [comment]
@romolox @yakky la pagina cerca di ottenere con `.get` via lo `slug` (parte dell'URL) del Comitato, ma lo `slug` e' generato in modo non univoco, come segue: lo slug di un Comitato e' uguale allo slug del genitore, piu' il suo nome slugifizzato (sic.). Esempio, il Comitato di Catania, ha slug, `italia-sicilia-catania`. 

Il problema giace nel fatto che ci sono combinazioni di (regione, comitato) che sono particolarmente lunghe di perse', quindi gia' lo slug del Comitato e' troncato, e di conseguenza lo slug di tutte le sedi territoriali sottostanti e' uguale a quello del Comitato (perche' appeso il nome della sede territoriale e troncato e' uguale a quello del genitore).

Questo causa che il `.get` ottiene piu' di un Comitato, e quindi lancia una eccezione (come e' giusto che faccia).

Bisogna:

1) Rivedere la logica generazione degli slug, in modo tale che gli slug siano univoci. In particolare, ho sempre odiato i numeri casuali o univoci a fondo di ogni singolo slug, ma sarebbe ottimo aggiungere un numero progressivo **nel solo caso di slug gia' presente**;
2) Preparare una migrazione che ottenga tutti gli slug doppioni e rigeneri gli slug. E' importante che la migrazione non abbia effetto sugli slug gia' univoci, perche' romperebbe Google, ma le pagine dei Comitati che hanno slug doppione hanno sempre dato 500 quindi non sono importanti e possiamo rigenerarli.

Spero che quello che ho scritto sia in italiano e abbia senso, fatemi sapere altrimenti

**Comment by AlfioEmanueleFresta** [comment]
Il trace conferma il mio sospetto:

```
Exception:
 anagrafica.models:MultipleObjectsReturned: get() returned more than one Sede -- it returned 5!

Stack trace
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/clickjacking.py", line 58, in wrapped_view
File "./autenticazione/funzioni.py", line 43, in _pagina_pubblica
File "./base/viste.py", line 250, in informazioni_sede
File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py", line 155, in get_object_or_404
File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 391, in get
```

**Comment by AlfioEmanueleFresta** [comment]
Aggiungo infine un riferimento alla funzione di generazione dello slug, [`Sede.sorgente_slug`](https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/models.py#L1337).

**Comment by AlfioEmanueleFresta** [comment]
C'e' da alzare la priorita' a mio avviso.

**Comment by AlfioEmanueleFresta** [comment]
Leggasi https://github.com/CroceRossaItaliana/jorvik/pull/512#issuecomment-275683198

**Comment by yakky** [comment]
Qui è sufficiente procede in questo modo:
* allungare il campo slug (e fare migrazione)
* creare una data migration che rigenera lo slug solo per quei comitati in cui la get restituisce errore
* impostare il campo slug come unique

Fatto questo, per valori del campo slug sufficientemente lunghi non ci dovrebbero mai essere conflitti e quindi non dovrebbe essere mai necessario applicare il suffisso numerale.
Ti torna @AlfioEmanueleFresta  ?

**Comment by yakky** [comment]
@AlfioEmanueleFresta ho aperto la PR secondo i punti sopra. E' deployato su luke
