### ISSUE TITLE
[corsi] richiesta possibilità di iscrizione dopo prima lezione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#384]
viene richiesto che gli aspiranti possano pre-iscriversi ad un corso anche successivamente alla data di partenza dello stesso. al momento gli aspiranti non vedono più il corso dal giorno in cui esso parte. questo si lega al fatto che lato US non si possa iscrivere una persona al corso senza inserirlo come sostenitore. i corsisti che si presentano al corso e non si iscrivono preventivamente su GAIA non possono quindi nemmeno essere iscritti postumi.

**Comment by luca-dex** [comment]
Forse una possibile soluzione potrebbe essere quella di poter pescare un aspirante volontario per codice fiscale, come si fa con i vecchi ordinari finiti sotto i comitati regionali, così da poter recuperare la persona ed agganciarla al corso base

**Comment by matthewmazzoleni** [comment]
@luca-dex il problema è più ampio, anche laddove la persone si volesse iscrivere autonomamente da GAIA al corso esso non è più visibile tra quelli disponibili a partire dalla data di partenza dello stesso.

**Comment by luca-dex** [comment]
La mia idea di come potrebbero andare le cose è la seguente:
1. Sei iscritto a gaia come aspirante ma non ti sei iscritto al corso e quindi non lo vedi più (oppure sei sostenitore in un altro comitato)
2. Il corso parte e il direttore del corso non può in nessun modo iscriverti perchè il tuo codice fiscale è già presente in gaia.
3. Siccome risulti tra gli aspiranti o tra i sostenitori, il direttore ti trova tramite codice fiscale e ti iscrive al corso
4. Al limite per sicurezza si può fare che ti arriva una email del tipo "Ciao tizio, mister x sta provando ad iscriverti al corso base del comitato xyz, clicca qui per confermare la tua iscrizione"

Questa possibilità secondo me potrebbe anche essere una forma di soluzione per #368

**Comment by luca-dex** [comment]
A occhio una cosa del genere potrebbe essere utile anche per quelle situazioni in cui c'è un ex volontario, già registrato su gaia ma dimesso, che deve rifare il corso da un'altra parte.

**Comment by matthewmazzoleni** [comment]
credo la cosa sia fattibile modificando la voce "iscrivi sostenitore" con un "iscrivi persona" generico che escluda dal selettore solo i già volontari o persone già iscritte ad altri corsi (magari indicando l'errore in modo esplicito). che ne dici @AlfioEmanueleFresta ?

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni @luca-dex 

(a) Iscrizioni autonome. Questa cosa e' gestita dalla proprieta' `CorsoBase.troppo_tardi_per_iscriverti` che attualmente ritorna `False` 7 giorni dopo la data di inizio del corso. Come soluzione, possiamo permettere la modifica di questo parametro, per ogni corso, tra valori predefiniti (0 giorni, 7 giorni, 14 giorni, 1 mese, ...)? Vedo anche che il calendario pero' non mostra i corsi a 0 giorni, come indicato da @matthewmazzoleni, come minimo questo e' da rendere uguale al tempo di 7 giorni o come diversamente indicato dal direttore.

(b) Iscrizioni dall'alto. Mi risulta che sia possibile aggiungere sostenitori ad un corso fino a che il corso e' attivo. E' possibile reclamare sostenitori tutto l'anno, fino a che non siano gia' sostenitori presso un altro comitato.

Ho sbagliato qualcosa? Opinioni?

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta quello che hai scritto non risolve nessuno dei problemi riportati. 

I problemi sono legati agli aspiranti volontari che non si iscrivono per tempo al corso (magari fisicamente stanno venendo, ma a livello informatico non si sono iscritti al corso su gaia e la segreteria corsi non li può tirare dentro) e alle situazioni in cui un sostenitore (creatura mitica che non può essere dimessa o similari) non si può iscrivere e non può essere iscritto al corso di un altro comitato

**Comment by AlfioEmanueleFresta** [comment]
Hai ragione, probabilmente mi sono concentrato sul dettaglio sbagliato.

> agli aspiranti volontari che non si iscrivono per tempo al corso (magari fisicamente stanno venendo, ma a livello informatico non si sono iscritti al corso su gaia e la segreteria corsi non li può tirare dentro)

Intendi senza reclamarli prima come sostenitori? Sono d'accordo che non e' necessariamente formalmente corretto, ma al momento questa procedura dovrebbe funzionare.

> e alle situazioni in cui un sostenitore (creatura mitica che non può essere dimessa o similari) non si può iscrivere e non può essere iscritto al corso di un altro comitato

OK -- anche in questo caso concordo con @matthewmazzoleni, bisogna permettere l'iscrizione dei non-sostenitori, anche perche l'essere sostenitori non ha davvero niente a che vedere con l'iscrizione al corso.

Pero' bisogna implementare qualcosa come quanto proposto da @luca-dex, una conferma da parte dell'aspirante, per evitare che la gente possa tirarsi interi fascicoli di dati personali inserendo codici fiscali 'per sbaglio'.

Allo stesso tempo, siete d'accordo col fatto che gli aspiranti dovrebbero vedere in calendario i corsi appena iniziati a cui possono ancora fare richiesta di partecipazione (fino a una settimana dall'inizio)?

**Comment by luca-dex** [comment]
> Allo stesso tempo, siete d'accordo col fatto che gli aspiranti dovrebbero vedere in calendario i corsi appena iniziati a cui possono ancora fare richiesta di partecipazione (fino a una settimana dall'inizio)?

Sì, sempre però col vincolo che è il direttore di corsi a doverti accettare (suppongo la situazione che un aspirante si accorge del corso dopo che è iniziato da qualche giorno e ha perso ormai troppe lezioni). Al contempo credo sia invece più comune la situazione in cui uno che si è iscritto a gaia non si è iscritto al corso e il direttore, inserendo il codice fiscale, lo ripesca.

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta la possiamo mettere in lista con le cose da fare? Abbiamo i corsi base in tutta Italia che sono iniziati e le lamentele aumentano!

**Comment by luca-dex** [comment]
@yakky questo è uno di quelli urgenti relativo ai corsi base

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta ho aumentato corrispondentemente il livello di priorità

**Comment by AlfioEmanueleFresta** [comment]
Concordo, e' uno di quelli piu' richiesti dal supporto.
