### ISSUE TITLE
[documenti]

### ISSUE THREAD

**Issue by galamarco** [CroceRossaItaliana/jorvik#387]
Nel momento in cui vado a rinominare una cartella creata, non visualizzo i comandi per salvare la modifica
![image 2](https://cloud.githubusercontent.com/assets/5132398/18886795/bd2bd1b4-84f1-11e6-8f1e-726214a1adba.png)

**Comment by yakky** [comment]
@galamarco @PaoloGiustiniani @AlfioEmanueleFresta dipende da qualche assegnazione di gruppo all'utente. A quale gruppo appartiene l'utente admin con cui entri?

**Comment by AlfioEmanueleFresta** [comment]
@yakky, ho verificato che @galamarco fa parte del gruppo redattori, che ha tutti i permessi disponibili, incluso `change`, sia sulle cartelle che sui file.

**Comment by yakky** [comment]
@galamarco la modifica è già caricata su luke se vuoi provare prima del deploy in produzione
