### ISSUE TITLE
[autoparco] notifiche di revisione mezzo non corrette

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#389]
utenti segnalano che vengono notificate nella pagina della gestione mezzi delle revisioni in scadenza da effettuare nonostante le stesse siano state correttamente già registrate nel sistema.

**Comment by yakky** [comment]
Non riusciamo a riprodurre il problema con i dati di esempio.
Passaggi:
* creazione veicolo con immatricolazione 1/1/2010
* viene segnalata la necessità di revisione
* creazione di una revisione al 10/5/2015
* viene segnalata la necessità di revisione
* creazione di una revisione al 10/5/2016
* nessun avviso di revisione

**Comment by PaoloGiustiniani** [comment]
@yakky ho reperito un caso.

![image](https://cloud.githubusercontent.com/assets/5071623/23120064/2771ea3c-f75b-11e6-8ad1-e546a88803db.png)

![image](https://cloud.githubusercontent.com/assets/5071623/23120049/11094614-f75b-11e6-85bb-ba60be732fe3.png)

![image](https://cloud.githubusercontent.com/assets/5071623/23120082/3d44e238-f75b-11e6-87cb-54728e5a8834.png)

**Comment by yakky** [comment]
@PaoloGiustiniani credo che attualmente manutenzione e revisione siano gestite come attività indipendenti. infatti in questo caso l'ultima "manutenzione ordinaria" risale al 2015 e segnala quella.
Quindi bisogna modificare in modo che anche le revisioni "contino" come manutenzioni?

**Comment by PaoloGiustiniani** [comment]
@luca-dex tu cosa dici?

In caso contrario bisognerà distinguerle.

**Comment by luca-dex** [comment]
Come viene valutato quale veicolo richiede manutenzione? Non capisco perchè ci sia questa segnalazione. Al limite dovrebbe essere segnalato quali veicoli richiedono una revisione, ma le manutenzioni non hanno vincoli (insomma, se non si rompe niente, la manutenzione non serve di base)

**Comment by yakky** [comment]
il codice dice ogni anno https://github.com/CroceRossaItaliana/jorvik/blob/master/veicoli/viste.py#L40

Quindi si toglie questo controllo periodico?

**Comment by AlfioEmanueleFresta** [comment]
Hmm, no. Il regolamento della motorizzazione CRI prevede che un controllo di affidabilita' venga effettuato, mi pare, ogni sei mesi o un tot di km (earliest of the two). Questo termine da utilizzare su Gaia era stato concordato con chi si occupa della motorizzazione a livello nazionale.

**Comment by luca-dex** [comment]
Ok,mi ero perso questa cosa. Allora forse basterebbe solo utilizzare anche la revisione come controllo tecnico, no?

**Comment by AlfioEmanueleFresta** [comment]
E' gia' cosi'. L'avviso per le revisioni tiene in conto solo le manutenzioni di tipo revisione; l'avviso per le manutenzioni tiene in conto entrambi i tipi di manutenzione.

**Comment by fmarco** [comment]
@luca-dex possiamo chiudere questa issue?

**Comment by PaoloGiustiniani** [comment]
@fmarco prima di chiuderlo bisogna specificare nella pagina quanto riportato sopra.

**Comment by romolox** [comment]
Aggiungiamo quindi un messaggio che avvisi l'utente? Dove mettiamo questo messaggio?

**Comment by AlfioEmanueleFresta** [comment]
@romolox Si. Nella pagina che mostra i veicoli da manutenere?

**Comment by romolox** [comment]
@AlfioEmanueleFresta perfetto. Come testo comprensibile dall'utente che mettiamo?

**Comment by romolox** [comment]
Qualcosa tipo: Nota:  la revisione di un veicolo viene considerata anche come manutenzione ordinaria. Un veicolo che ha effettuato una manutenzione ordinaria ma non è stato revisionato sarà mostrato comunque in questa lista.

**Comment by romolox** [comment]
@AlfioEmanueleFresta @PaoloGiustiniani 
Come risulta da codice https://github.com/CroceRossaItaliana/jorvik/blob/master/veicoli/models.py#L169

Possiamo scrivere qualcosa del tipo:
Le notifiche di revisione e manutenzione ordinaria dei veicoli sono indipendenti. Pertanto la data della revisione non viene conteggiata ai fini degli intervalli di manutenzione programmata.

**Comment by yakky** [comment]
@PaoloGiustiniani up

**Comment by PaoloGiustiniani** [comment]
@luca-dex sei tu l'uomo motorizzazione, quindi è tua.

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta per riepilogare

Attualmente il codice gestisce i due avvisi (revisione e manutenzione) in modo completamente separato https://github.com/CroceRossaItaliana/jorvik/blob/master/veicoli/models.py#L169 diversamente da https://github.com/CroceRossaItaliana/jorvik/issues/389#issuecomment-281124834

A seconda di quale dei due è vero implementiamo i messaggi del caso

**Comment by AlfioEmanueleFresta** [comment]
> Quindi bisogna modificare in modo che anche le revisioni "contino" come manutenzioni?

Hmm, mi scuso per l'errore. Noto anche che nel vecchio Gaia era implementato per come e' implementato ora. L'unico dubbio e' che quando ho scritto quel commento avevo recentemente scritto i requisiti per il 'nuovo' modulo motorizzazione -- non vorrei aver confuso i due. E nel caso io l'abbia fatto, non so quale delle due implementazioni sia piu' corretta.

Sfortunatamente il regolamento attuale motorizzazione (vedi allegato) non aiuta, in quanto non include per niente quanto scrivevo nel commento sopra -- i requisiti del nuovo modulo sono stati scritti sulle conoscenze di colui che ha partecipato alla scrittura del nuovo regolamento veicoli, non ancora rilasciato.

[TU_definitivo_versione_1_04_aggiornato_25_8_2010___DEFINITIVO_2010 (1).pdf](https://github.com/CroceRossaItaliana/jorvik/files/1050250/TU_definitivo_versione_1_04_aggiornato_25_8_2010___DEFINITIVO_2010.1.pdf)

**Comment by AlfioEmanueleFresta** [comment]
In definitiva -- direi che l'importante non e' qualche dei due comportamenti scegliamo, bensi' che lo rendiamo esplicito. Se gli altri sono d'accordo, manteniamo il comportamento attuale (i.e. revisioni non contano come manutenzione) e scriviamolo esplicitamente. 

La cosa peggiore che puo' accadere e' che i Comitati che fanno revisioni molto accurate, useranno il workaround di registrare lo stesso intervento sia come manutenzione che come revisione.

@luca-dex @PaoloGiustiniani @matthewmazzoleni

**Comment by romolox** [comment]
Nel frattempo ho creato la merge request con la notifica:
https://github.com/CroceRossaItaliana/jorvik/pull/604

@AlfioEmanueleFresta
