### ISSUE TITLE
[attività] apertura della modifica attività mostra campi vuoti

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#391]
modificando l'attività 9215 l'utente riceve la pagina di modifica della stessa ma senza precaricamento dei dati. di fatto viene mostrata la form vuota.

**Comment by yakky** [comment]
Non possiamo fare attività di debug ulteriore senza accesso ai dati o a dei log dettagliati dell'errore risultante

**Comment by PaoloGiustiniani** [comment]
@matthewmazzoleni ho simulato tale condizione e non rilevo la problematica, inoltre nessun errore viene registrato.

Hai altre info o uno screenshot dal quale si evince la problematica?

/cc @AlfioEmanueleFresta

**Comment by luca-dex** [comment]
Tutte le volte che apro in modifica un'attività esistente (aperta, con descrizione compilata, visibile) ottengo questa schermata:

![screenshot at 2016-12-02 17-33-26](https://cloud.githubusercontent.com/assets/3315913/20841832/8c0a8a9c-b8b5-11e6-9233-3623dad545c0.png)

Sto facendo riferimento all'attività https://gaia.cri.it/attivita/scheda/8248/modifica/ ma questo succede per qualsiasi attività io vado ad aprire. Se salvo e torno in modifica i campi risultano sempre vuoti.

**Comment by AlfioEmanueleFresta** [comment]
Il commit 8c98a4bc6ac450ac1f5b71b92113ac91dba73eb0 introduce questa riga https://github.com/CroceRossaItaliana/jorvik/blame/master/attivita/viste.py#L625 che fa in modo che il dizionario `request.POST` sia sempre popolato, con un solo elemento (chiave `centrale_operativa`).

Questo fa a cazzotti col controllo che faccio io nella riga https://github.com/CroceRossaItaliana/jorvik/blame/master/attivita/viste.py#L627. Se nessuna richiesta e' stata fatta, `request.POST` era un dizionario vuoto, quindi si passava `None`. `None` sta per tirati tutti i dati dalla istanza dell'attivita'. Passando invece un dizionario parziale, Django crede che sia appena stato fatto il post e tutti i campi siano stati lasciati vuoti, a sola eccezione del campo di centrale operativa.
