### ISSUE TITLE
[soci] Ufficio soci vede persone di comitati in cui è esteso

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#397]
Sto facendo dei test su luke e andando a simulare il pagamento di una quota mi sono accorto che oltre a vedere i volontari di Lainate (mio comitato, in cui ho la delega di ufficio soci) il selettore mi mostra anche i volontari del comitato di bordighera, sui cui ho un'estensione, ma nessuna delega.

Riporto screen:
![screenshot at 2016 10 04 21 09 27](https://cloud.githubusercontent.com/assets/3315913/19088633/388305d2-8a77-11e6-9664-217f67aa4a69.png)

EDIT:
la cosa succede in tutti i selettori

**Comment by AlfioEmanueleFresta** [comment]
Non do priorita' alta semplicemente perche' non c'e' fuoriuscita di dati (da esteso hai accesso alla rubrica volontari del comitato presso cui sei esteso), e il form non parte con un volontario su cui non hai poteri. Comunque migliorabile (da specializzare il selettore volontari).

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta concordo, a meno che @luca-dex confermi anche la possibilità di operare come US sui soci del comitato in cui sono esteso.

**Comment by luca-dex** [comment]
Posso assegnare ruoli alle persone non del mio comitato, ad esempio quello di direttore del corso base.

![seleziona direttore i corso base il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/19148055/44335892-8bbb-11e6-90a5-b1d47ec08705.png)

**Comment by AlfioEmanueleFresta** [comment]
I permessi sui volontari sono quelli di `ELENCO`, quindi puoi solo elencare, non vedere la scheda anagrafica (solo nome e avatar, se presente, insomma). Questo include la disponibilita' per l'aggiunta come direttore e altre deleghe che tu puoi fare, ma non credo che sia davvero un problema (specie per i direttori dei corsi base).

**Comment by yakky** [comment]
@AlfioEmanueleFresta @luca-dex allo stato della discussione non riesco a capire qual è l'azione da intraprendere

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta direi a questo punto che coincide con quanto trattato in #556 (anche se la PR gestisce molti più casi rispetto a questa specifica issue)

**Comment by luca-dex** [comment]
Sì, il problema generale è sempre lo stesso e cioè quale tipo di permessi devono avere presidenti/us dei comitati dove un volontario è esteso.
