### ISSUE TITLE
autoparco: visibilità autoparchi

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#40]
- [x] nella funzione autoparco, nella voce collocazione, nel menu a tendina vengono fuori tutti gli autoparchi d'italia e non solo quelli del comitato.

- [x] se presidente colloca il mezzo presso una sede territoriale non lo vede più come presidente del comitato (tenuto conto che in un comitato con sedi territoriali i mezzi sono assegnati al comitato e non alla singola sede che non ha autonomia amministrativa, sarebbe necessario collocare correttamente il mezzo presso la sede, ma poter vedere tutto dal pannello del presidente e del responsabile provinciale autoparco se esistente)

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo per favore usa `fix #num` per chiudere i commit.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo come hai risolto la pt. (1) di questo issue? Se hai risolto con commit non referenziato, per favore scrivi qui il numero del commit.

**Comment by AngeloLupo** [comment]
pt. 1 sistemata con cb134f10df67afe9d5b1222141285c4cae4004dd

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo ma l'hai testato? Non funziona. Per favore sistema urgentemente
