### ISSUE TITLE
Inserimento codice per live chat

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#402]
Ciao, 
avrei necessità di inserire il codice che ho appena inviato via email a @yakky 

Di default si allinea a sinistra, dev'essere presente in tutte le pagine.

Grazie.

**Comment by yakky** [comment]
@PaoloGiustiniani fixed in #403

**Comment by luca-dex** [comment]
Ciao,
nella pagina dei tesserini -> richiesta effettuata il pulsante della live chat compare due volte come da screen

In da  richiedere e senza fototessera non compare.

![richieste tesserini il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/19211894/887117c8-8d47-11e6-94b8-e09f9d40a756.png)

**Comment by yakky** [comment]
@luca-dex modifica caricata su luke. Purtroppo gli embed sono fatti in 2~3 modi diversi e non mi ero accorto di questo caso. Farei comunque il merge su master appena passano i test
