### ISSUE TITLE
[aspirante] inibire accesso a funzionalità

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#404]
1) Nel profilo visibile all'aspirante risultano due pagine in alto "Utente" e "Aspirante"

_Segue screenshot_

Tutto ciò che è in comune con il volontario "Cambio password, privacy, ecc" dev'essere spostato nel tab "aspirante". Dovrà rimanere solo il tab "Aspirante".

![aspiranti](https://cloud.githubusercontent.com/assets/5071623/19190610/d96bb65a-8c9e-11e6-876a-7524edda9a8b.png)

2) Nella pagina "Utente" > "Fotografie" vi è la possibilità di cliccare su "Fototessera (formale)", funzione non utile per un aspirante (cliccando, questo, infatti, ottiene il messaggio "Necessaria appartenenza"). 

Bisogna rimuovere tale funzionalità.

4) Cliccando su "Fotografie", il suddetto nome non viene evidenziato in blu come invece succede alle altre voci sulle quali si clicca

![fotografie](https://cloud.githubusercontent.com/assets/5071623/19190493/1135a3d0-8c9e-11e6-91a4-86aa2b2307be.png)

5) Nella pagina "Utente", in elenco (a sinistra), vi sono le sezioni: 
Volontario > Estensione
Volontario > Trasferimento
Volontario > Riserva
Rubrica > Referenti
Rubrica > Volontari 
Curriculum > Patenti CRI 
Curriculum > Titoli CRI 

Bisogna rimuoverle (come da screenshot)

4) La pagina "Attività" non è utile all'aspirante (Calendario, Turni, Gruppi di Lavoro, Reperibilità). 

Bisogna rimuoverla.

L'aspirante che si recherà su una pagina dedicata ai volontari dovrà avere apposita informativa che tale sezione è riservata ai volontari.

**Comment by AlfioEmanueleFresta** [comment]
@yakky per favore come concordato affrontate gli issue in ordine di priorita', abbiamo issue bloccanti al momento, questo non e' prioritario.

**Comment by yakky** [comment]
@AlfioEmanueleFresta ok. Dal colloquio di ieri con marco sembrava che avesse una certa priorità

**Comment by yakky** [comment]
@PaoloGiustiniani 
Abbiamo bloccato le voci dettagliate nelle varie issue, ma alcune specifiche erano un po' generiche, potete verificare su luke?

**Comment by luca-dex** [comment]
@yakky in linea di massima, ricollegandomi anche a tutte le altre linkate a questa, solo i Volontari possono compiere azioni come richieste di estensione, trasferimento, riserva. Nessun altro. Quindi dipendenti, soci ordinari, sostenitori, aspiranti, ecc non possono fare nessuna di queste cose. Se una persona è Volontario e dipendente/ordinario, tutte le azioni sono legate alla sua appartenenza come Volontario e non alle altre. In conseguenza a ciò tutte le voci di menù (e tutte le operazioni relative a quelle voci) devono essere bloccate a chi non è almeno Volontario.

Dimmi se ti servono maggiori dettagli.

**Comment by AlfioEmanueleFresta** [comment]
@yakky tra le sezioni mi sembra che 'Curriculum' sia l'unica che ha voci miste (presenti alcune, altre no). La motivazione e' che alcune tipologie di titolo (tutti quelli CRI, come patenti e qualifiche CRI), richiedono che il Presidente o l'US approvino l'inserimento. 

I tipi di titoli vengono tirati da un dizionario (o qualche altra struttura) che se non sbaglio contiene una tupla per titolo, che include anche un flag che rispecchia la necessita' di fare approvare il titolo o meno. 

Tale flag e' il punto migliore per innescare la condizione (i.e. mostra *if me.volontario or not tipo.richiede_approvazione*), mantenendo inoltre la lista piu' dinamica possibile.

**Comment by yakky** [comment]
@AlfioEmanueleFresta purtroppo direi di no. C'è un campo "inseribile in autonomia" nel model del titolo specifico (cioè non del tipo di titolo) ma può essere recuperato solo dopo che l'utente ha riempito il form
