### ISSUE TITLE
discrepanze oggetto / contenuto delle email di notifica

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#406]
Abbiamo diversi casi in cui le email inviate alle persone da GAIA contengono informazioni in conflitto tra loro.

esempio:
titolo mail: Richiesta di Estensione APPROVATA
corpo mail: Ricevi questo messaggio perché una tua richiesta è stata RESPINTA.

**Comment by AlfioEmanueleFresta** [comment]
Qualcosa e' successo tra [prima](https://github.com/CroceRossaItaliana/jorvik/blob/dc55325c48eefcc6ecf638bfa01869b572c36233/base/models.py#L206) e [dopo](https://github.com/CroceRossaItaliana/jorvik/blob/7da3e3acbf58a9d0b0c185ae9e81091835a99315/base/models.py#L257) che ha scambiato i modelli usati per le e-mail di notifica.

Bisogna correggere i nomi dei modelli.

**Comment by yakky** [comment]
Corretto. E' su luke ma farei comunque il merge su master vista l'urgenza
