### ISSUE TITLE
[storico] deleghe terminate risultano attive in storico

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#407]
l'utente 1666 risulta terminato nella delega "delegato area 5" ma nel suo storico (dal suo profilo) risulta in carica per tale titolo

**Comment by yakky** [comment]
VErificata.
In generale i trasferimenti non terminano le deleghe

**Comment by yakky** [comment]
@matthewmazzoleni scusa, un aggiornamento: la persona in questione la delega è **effettivamente** terminata anche su gaia, ma nello storico non risulta tale?
Altrimenti se è il problema che le deleghe non sono chiuse su gaia in caso di trasferimenti / dimissioni /etc , ricade nei casi della #511

**Comment by luca-dex** [comment]
Concordo con @yakky la PR della terminazione delle cose aperte dovrebbe risolvere anche questa. Penso lasci un po' di pregresso in giro per gaia da gestire però

**Comment by yakky** [comment]
@luca-dex @matthewmazzoleni temo che sul pregresso non ci siano molte opzioni "automatiche"
L'unica potrebbe essere terminare le deleghe per i comitati in cui non si risulta volontari?

**Comment by matthewmazzoleni** [comment]
@yakky non è così semplice, abbiamo dei commissari che fanno parte di un comitato ma sono delegati come presidenti in un altro, ad esempio..

@luca-dex

**Comment by luca-dex** [comment]
no no, facciamo tutto manuale per sistemare il pregresso, niente di
automatico: rischio troppo alto

2017-06-22 16:14 GMT+02:00 Matthew Mazzoleni <notifications@github.com>:

**Comment by yakky** [comment]
@luca-dex @matthewmazzoleni ok, allora la #511 dovrebbe risolvere anche questi casi per il futuro, la collego a questa
