### ISSUE TITLE
elenchi: non mostrati sostenitori

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#41]
il presidente 72877 riferisce di non visionare alcun sostenitore nell'elenco, nonostante ne avesse circa 50.

dettagli: ZQL-607-54262

**Comment by AlfioEmanueleFresta** [comment]
Come faceva ad avere 50 sostenitori se li abbiamo introdotti ieri?

Alfio Emanuele Fresta

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni chiudo .
