### ISSUE TITLE
[aggiornamento] pagina /informazioni/aggiornamenti/

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#410]
@AlfioEmanueleFresta 

puoi aggiornare i riferimenti di questa pagina con quelli del nuovo repo?

**Comment by AlfioEmanueleFresta** [comment]
Risolto con 8c65ff6bdab112bc7bd7d6e4fc094865a1792253

**Comment by PaoloGiustiniani** [comment]
Non ci sono i contenuti 📟

**Comment by AlfioEmanueleFresta** [comment]
@PaoloGiustiniani dove l'hai provata? E' solo su master

**Comment by PaoloGiustiniani** [comment]
allineato, funziona.
