### ISSUE TITLE
[appartenenze] modifica arbitraria date di appartenenza

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#413]
nelle appartenenze è possibile, per P e US, modificare la data di partenza dell'associazione di un volontario al comitato in un dato ruolo. Questo permette di fatto di generare appartenenze accavallate in quanto un presidente, potendo modificare la data di partenza, può anticiparla rispetto alla data di termine di una appartenenza precedente. questo non dovrebbe essere possibile.

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta @PaoloGiustiniani questa cosa è abbastanza importante perchè rischia di compromettere i libri soci, in particolare è possibile spostare le date di inizio delle appartenenze ad una data successiva al pagamento della quota, oltre al problema degli accavallamenti.

**Comment by yakky** [comment]
@matthewmazzoleni @luca-dex priorità?

**Comment by yakky** [comment]
@luca-dex @matthewmazzoleni qual è la soluzione migliore in questo caso? Fare solo un controllo per evitare accavallamenti e incongruità con la data di pagamento della quota?
In quest'ultimo caso qual è il comportamento corretto?
Ovvero: 
Socio A:
* appartenenza comitato B da 1/1/2016 a 31/10/2016, pagamento quota al 3/3/2016
* appartenenza comitato C da 1/11/2016 senza fine

Socio D
* appartenenza comitato C il 2/11/2016 per nuova iscrizione con contestuale pagamento della quota

Quali sono i vincoli in questi due casi? (sicuramente voi ne avrete di più complessi da segnalare e mappare)

**Comment by luca-dex** [comment]
In linea generale aggiungo a quanto detto che l'unica appartenenza che è possibile modificare è l'appartenenza attuale della persone rispetto al comitato di cui è socio o presso cui è in estensione. Non deve essere possibile modificare (lato ufficio soci) appartenenze passate.

Gli esempi mi sembrano sensati, ma riporto di seguito le situazioni che esemplificano i vincolo che devono sempre essere rispettati in qualsiasi situazione. ( @CroceRossaItaliana/sviluppo ovviamente aggiungete o correggete se notate qualcosa) 

Situazioni possibili: 

- **INGRESSO** Volontario che si iscrive in Croce Rossa a seguito di corso base. In questa situazione l'operazione di modifica avviene sulla prima appartenenza di un Volontario, che ancora non ha fatto un trasferimento verso nessun comitato. Sono possibili le seguenti due situazioni: 
  - se il corso base è stato gestito su gaia l'appartenenza deve per forza coincidere con la data di esame del corso base e non può comunque essere successiva a quella di pagamento della quota socio;
  - se il corso base non è stato gestito su gaia l'appartenenza deve per forza essere precedente alla prima quota socio registrata per quel Volontario su quel Comitato.
- **TRASFERIMENTO** Volontario che ha un'appartenenza chiusa sul comitato A e una nuova appartenenza sul comitato B. In questa situazione la modifica avviene sulla data di inizio di B e sulla data di fine su A. Sono possibili le seguenti situazioni:
  - se esiste un trasferimento gestito su gaia, la chiusura su A e l'apertura su B devono coincidere con la data di approvazione del trasferimento. Se la quota è pagata prima del trasferimento, deve essere pagata in A, se pagata dopo deve essere in B.
  - se non esiste un trasferimento gestito su gaia, la chiusura su A deve coincidere con l'apertura su B e deve essere successiva la pagamento  della quota su A o precedente al pagamento della quota su B
- **ESTENSIONE** Volontario che ha un'appartenenza aperta sul Comitato A e un'estensione sul comitato B: non ci sono Vincoli e le due cose possono avvenire in contemporanea, ma se il volontario chiude la sua appartenenza su A (dimissioni o trasferimento), allora anche la sua appartenenza su B deve terminare.

In sostanza l'aspetto essenziale di tutta questa descrizione è il fatto che si possono andare a modificare solo appartenenze che non sono vincolate da altre azioni svolte su gaia.

@yakky se servono più dettagli chiedi pure

**Comment by yakky** [comment]
@luca-dex attualmente l'unica appartenenza che è possibile modificare è comunque quella attuale. visti i vincoli, in realtà, potrebbe essere sufficiente restringere la possibilità di modifica solo per i seguenti casi di appartenenze:

* Prima appartenenza come volontario senza corso base precedente (inserendo controllo di congruità con versamento quota)
* Tutte le appartenenze come estensioni (la terminazione automatica delle estensioni su dimissioni o trasferimenti è già implementata)
* Tutte le appartenenze come volontario precedute da appartenenze per dimissioni (ovvero se uno rientra in croce rossa dopo dimissioni)

In tutti gli altri casi di appartenenze attuali, abbiamo comunque appartenenze precedenti che vincolano la data di inizio alla data di termine della precedente e possiamo quindi impedire la modifica della data

**Comment by AlfioEmanueleFresta** [comment]
> * Prima appartenenza come volontario senza corso base precedente (inserendo controllo di congruità con versamento quota)

Suggerisco di usare l'esistenza del `formazione.PartecipazioneCorsoBase`. Join su (persona, destinazione) filtrato per esito e data <= a inizio dell'appartenenza.

**Comment by yakky** [comment]
@AlfioEmanueleFresta il primo caso riguarda i volontari **senza** corso base.
I miei punti sopra sono solo quei casi in cui **non** esiste un'appartenenza precedente diretta (ovvero un passaggio diretto da A a B)
Per tutti gli altri la data di fine di un appartenenza determina necessariamente l'inizio della successiva (ovvero appunto i volontari che diventano tali dopo un corso e quindi come "genitore logico" -passami il termine- della prima appartenenza hanno appunto un corso base con relativo verbale etc

**Comment by yakky** [comment]
@AlfioEmanueleFresta ma il campo "precedente" nelle appartenenze è usato solo per la trasformazione in sostenitore? non anche per i trasferimenti?

**Comment by AlfioEmanueleFresta** [comment]
@yakky dovrebbe, ma guardando il codice ho paura che cosi' non sia. Una cosa certa pero' e' che la motivazione di terminazione e' sempre 'trasferimento', e che fine e nuovo inizio dovrebbero coincidere.

**Comment by yakky** [comment]
Sì. Infatti ne ho tenuto conto nella seconda condizione: https://github.com/CroceRossaItaliana/jorvik/pull/483/files#diff-1bb484c635d322f5a4983e42076450faR1279

Il codice fa la cosa giusta quando viene approvato un trasferimento. Quindi si tratta di recuperare le "precedenze" effettive.
Apro una issue separata per correggere il comportamento nei trasferimenti?

**Comment by luca-dex** [comment]
> Apro una issue separata per correggere il comportamento nei trasferimenti?

@AlfioEmanueleFresta puoi dare risposta tu su questa cosa?

**Comment by AlfioEmanueleFresta** [comment]
@yakky si, per favore con una migrazione. Deve essere presente una la terminazione per trasferimento, e la pratica di trasferimento `anagrafica.Trasferimento`, oltre alla corrispondenza di fine e inizio tra le due appartenenze.

**Comment by yakky** [comment]
@AlfioEmanueleFresta aperta segnalazione. Il codice per risolvere questa comunque riesce ad "arrangiarsi" comunque, perché la condizione sui trasferimenti fa sì che anche senza precedenza sia possibile ricostruire i dati corretti

**Comment by luca-dex** [comment]
Quindi la PR è buona e la posso testare?

**Comment by yakky** [comment]
@luca-dex direi di sì
@AlfioEmanueleFresta preferisci correggere i trasferimenti prima di fare il merge definitivo della PR collegata a questa segnalazione?

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta dacci un parere

**Comment by AlfioEmanueleFresta** [comment]
@luca-dex @yakky 
> ESTENSIONE Volontario che ha un'appartenenza aperta sul Comitato A e un'estensione sul comitato B: non ci sono Vincoli e le due cose possono avvenire in contemporanea, ma se il volontario chiude la sua appartenenza su A (dimissioni o trasferimento), allora anche la sua appartenenza su B deve terminare.

Per le estensioni non dobbiamo prevedere, in modo simile al trasferimento, che se la pratica e' stata gestita da Gaia, la data di inizio dell'estensione deve coincidere con l'approvazione della richiesta?

**Comment by yakky** [comment]
@AlfioEmanueleFresta la correzione del campo ``precedente`` per i trasferimenti la gestiamo come caso separato per tenere compatta questa PR?

**Comment by AlfioEmanueleFresta** [comment]
Va bene

Alfio

2017-01-20 13:11 GMT+00:00 Iacopo Spalletti <notifications@github.com>:

**Comment by luca-dex** [comment]
@AlfioEmanueleFresta la mia indicazione era relativa all'interazione di un'estensione con l'appartenenza come Volontario di una persona, non stavo considerando la problematica dell'estensione in sè (perchè questa issue era relativa solo alle variazione e quindi ai vincoli di inizio appartenenza)

**Comment by AlfioEmanueleFresta** [comment]
La PR permetteva la modifica della data di inizio estensione in modo indiscriminato

**Comment by luca-dex** [comment]
Ah ok, le estensioni non dovrebbero essere proprio modificabili.

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta sì, perché era solo un abbozzo di lavorazione, appena ho visto l'anomalia sui trasferimenti non ho implementato il resto del codice

@luca-dex quindi le estensioni non sono comunque modificabili?

**Comment by luca-dex** [comment]
Allora, la cosa più semplice è non permetterne la modifica, perché in ogni
caso le estensioni sono associate ad un'approvazione, sia che siano
richieste dall'utente, sia che siano inserite tramite ufficio soci.

Permettiamo la modifica della data di inizio dell'appartenenza attuale solo
perché ci possono essere state situazioni di inserimenti di Volontari con
date errate (a seguito dei vecchi caricamenti massivi).

**Comment by yakky** [comment]
@luca-dex puoi guardare i test aggiornati?
Ho inserito nche il controllo sul corso base

**Comment by luca-dex** [comment]
Ho risposo nella PR

**Comment by yakky** [comment]
ho risposto alla tua risposta :trollface:
