### ISSUE TITLE
[approvazioni] approvazioni automatiche da regolamento non funzionano

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#419]
giungono segnalazioni (ad esempio trasferimenti) di approvazione che non vengono processate automaticamente a seguito del trascorso periodo di "silenzio assenso".

**Comment by matthewmazzoleni** [comment]
aggiungo che anche approvazioni processate manualmente non avanzano di stato. cd "in carico a gestore trasferimenti". es: richiesta trasferimento 6785

**Comment by matthewmazzoleni** [comment]
up. serve gestire correttamente il pregresso anche a fronte delle implementazioni fatte in #237

**Comment by PaoloGiustiniani** [comment]
@AlfioEmanueleFresta pri3 in quanto non stanno funzionando le approvazioni automatiche.

Bisogna progettare bene come gestire il passato.

**Comment by yakky** [comment]
@PaoloGiustiniani @matthewmazzoleni attualmente le approvazioni automatiche sono **esclusivamente** sulle attività

**Comment by PaoloGiustiniani** [comment]
@yakky yes, in questa issue si fa riferimento a trasferimenti ed estensioni.

**Comment by yakky** [comment]
@PaoloGiustiniani @matthewmazzoleni 
Potete fornire la lista complete delle autorizzazioni da processare in automatico, dopo quanto tempo e qual deve essere l'azione automatica (ovvero: negazione  o approvazione)

**Comment by luca-dex** [comment]
@yakky ecco a te:

* **trasferimenti** tempo: _30 giorni_ azione automatica: _approvazione_
* **estensioni** tempo: _30 giorni_ azione automatica: _approvazione_

**Comment by yakky** [comment]
@matthewmazzoleni @luca-dex @PaoloGiustiniani in caso di approvazione automatica data e numero di protocollo come devono essere valorizzati?

**Comment by luca-dex** [comment]
come data la data di approvazione automatica e nessun numero di protocollo @CroceRossaItaliana/sviluppo date un parere anche voi.

**Comment by PaoloGiustiniani** [comment]
@luca-dex concordo, registrerei solo che si tratta di un' approvazione per termini di scadenza come da regolamento

**Comment by matthewmazzoleni** [comment]
concordo con quanto espresso da @PaoloGiustiniani e @luca-dex

**Comment by yakky** [comment]
@matthewmazzoleni @PaoloGiustiniani @luca-dex quindi imposto qualcosa come "approvata automaticamente a termini di regolamento"?

**Comment by PaoloGiustiniani** [comment]
@yakky il testo esatto è il seguente:

**Trasferimenti**
Il trasferimento è stato automaticamente approvato essendo decorsi trenta giorni, ai sensi dell'articolo 9.5 del "Regolamento sull'organizzazione, le attività. la formazione e l'ordinamento dei volontari"

@luca-dex le estensioni, da regolamento, non includono un' approvazione automatica. Ti risulta?

**Comment by yakky** [comment]
@PaoloGiustiniani attualmente il campo "protocollo" ha lunghezza 16 caratteri ...
Posso mettere la descrizione nel motivo, ma se non vado errato viene usato solo in caso di negazione (giusto @AlfioEmanueleFresta ?)

**Comment by matthewmazzoleni** [comment]
@yakky il nome di chi abbia effettuato fisicamente l'approvazione immagino sia salvato, corretto? in tal caso viene registrato che sia l'utente di sistema ad aver effettuato l'operazione?

**Comment by luca-dex** [comment]
@PaoloGiustiniani non è espressamente scritto che vengono automaticamente approvate, ma c'è comunque scritto che non possono essere rigettate, quindi io le tratterei come i trasferimenti, perchè appunto è indicato:

> La richiesta di estensione di servizio non può essere rigettata, salvo che la motivazione sia assente o incongrua. Il rigetto è impugnabile dinanzi al Presidente Regionale.

C'è il rischio di avere richieste pendenti mai approvate, così che non siano negate nè concesse.

**Comment by yakky** [comment]
@matthewmazzoleni essendo un'approvazione automatica non è stata approvata da nessuno :) Nel senso che risulta approvata in automatico da ``None``; non c'è un utente "collegato" all'approvazione

**Comment by luca-dex** [comment]
bhe.. la cosa non si risolve considerando che quando l'approvatore è `None` allora è stata approvata da Gaia?

**Comment by yakky** [comment]
@luca-dex certamente. E' solo per puntualizzare che non ci saranno utenti effetivi associati

**Comment by matthewmazzoleni** [comment]
@luca-dex infatti la mia domanda era appunto per capire se si potesse automaticamente desumere l'approvazione automatica da qualcosa di già presente. in questo caso non è quindi necessario scrivere esplicitamente una nota ma verificare chi abbia effettuato l'operazione e mostrare all'utente un messaggio sulla linea di quanto scritto da @PaoloGiustiniani nel caso in cui non vi fosse una "persona fisica" dietro all'approvazione

**Comment by yakky** [comment]
@matthewmazzoleni c'è un flag apposito "automatica" che dice che è stata approvata automaticamente

**Comment by AlfioEmanueleFresta** [comment]
@yakky 

> con le autorizzazioni automatiche l'unico problema è che "scompaiono" dallo storico perché non sono state firmate da nessun utente. Come possiamo ovviare @AlfioEmanueleFresta ?

Non sono sicuro che ci sia una soluzione semplice per lo storico, e comunque mandiamo e-mail di notifica quindi non credo sia un problema. Allo stesso tempo manterrei traccia di tutte le richieste inoltrate: una nuova sezione in richieste, visto che questa appare anche ai volontari, 'in uscita'. Il possibile firmatario generalmente non lo abbiamo, ma possiamo dire che la richiesta e' stata affidata in carico 'agli incaricati alla Gestione dei Soci del Comitato di Tizio', 'agli Incaricati per la gestione dell'attivita' X', ... (risolvendo quindi le costanti e le stringhe per gli incarichi associati), e nel caso sia stata firmata, 'ed e' stata approvata/respinta da Caio'/'ed e' stata approvata/respinta automaticamente da Gaia dopo Xgg Yhh.'.

> @matthewmazzoleni @PaoloGiustiniani @luca-dex quindi imposto qualcosa come "approvata automaticamente a termini di regolamento"?

> @PaoloGiustiniani attualmente il campo "protocollo" ha lunghezza 16 caratteri ...
Posso mettere la descrizione nel motivo, ma se non vado errato viene usato solo in caso di negazione (giusto @AlfioEmanueleFresta ?)

Il motivo viene riempito dal volontario che fa richiesta di trasferimento, con la motivazione per la quale chiede il trasferimento. E' sempre presente. Invece data e numero di protocollo vengono riempiti da chi registra la richiesta di trasferimento e quindi l'accetta o la rifiuta (@matthewmazzoleni vige ancora 'obbligo' di protocollo per APS?). 

A questo punto credo che non sia necessario salvare in database tale dicitura, piuttosto sarebbe necessario inviare una e-mail di notifica di approvazione automatica al volontario, ma soprattutto ai referenti del Comitato di origine, notificando l'approvazione automatica, includendo tale dicitura (**che ne pensate?**).

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo Per il messaggio l'avevo intanto implementato nel PDF https://github.com/CroceRossaItaliana/jorvik/pull/442/commits/ce551eba8c5c120b98a3ad0f5de58e6ebfb93a9a#diff-9f50590740c0e8d369c9bc53a760eaa8R33

@AlfioEmanueleFresta quindi apriamo segnalazione separata per la sezione "in uscita" delle richieste, mentre implementiamo / verifichiamo le notifiche email nella PR associata, è corretto?

**Comment by AlfioEmanueleFresta** [comment]
@yakky si', sentiti libero di crearla, magari chippo in per aggiungere dei dettagli, finira' in 'Adeguamento'
