### ISSUE TITLE
[utente] accesso genera Proibito (403) Verifica CSRF fallita. Richiesta interrotta.

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#420]
l'utente 1061 riceve i seguenti problemi in fase di uso di gaia:
- errore: Proibito (403) Verifica CSRF fallita. Richiesta interrotta.
- necessità di minuti per apertura attività (ne ha aperte molte)

**Comment by AlfioEmanueleFresta** [comment]
Per quanto riguarda il 403, quello che mi viene in mente e' che ha scaricato la pagina di login (file > salva con nome), magari nel tentativo di metterla come segnalibro. Possibile?

**Comment by yakky** [comment]
@matthewmazzoleni non riesco a riprodurre il problema. Potrebbe aver usato una pagina in cache ... è un caso isolato?

**Comment by luca-dex** [comment]
Possiamo chiudere?

**Comment by yakky** [comment]
Per me sì. Si può sempre riaprire qualora ci fossero più dati
