### ISSUE TITLE
[bug] trasferimenti ed estensioni: (1) verso comitati regionali / nazionali e - (2) di soci ordinari

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#422]
Riunisco in questa issue le segnalazioni precedentemente riportate nella giornata di oggi riferite al mesesimo problema. Sui trasferimenti e sulle estensioni ho verificato le seguenti problematiche:

Un Volontario di un Comitato territoriale può chiedere un'estensione verso un Comitatato Regionale o verso il Comitato Nazionale.

![richiesta estensione il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/19401982/a74785f8-925e-11e6-921b-7a14246f3259.png)

Un Volontario di un Comitato territoriale può chiedere un trasferimento verso un Comitato Regionale o verso il Comitato Nazionale. Questa situazione è **estremamente critica** in quanto si vanno a corrompere i libri soci dei comitati.

![richiesta trasferimento il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/19402000/ced97a18-925e-11e6-863c-80c61f6846e8.png)

Un Socio ordinario di un Comitato Regionale dotati di credenziali di accesso a Gaia può chiedere il trasferimento o l'estensione verso un Comitato Territoriale, verso un altro Regionale o verso il Comitato Nazionale. Qualora questo socio si trasferisca su un Comitato territoriale. 

Credo che la problematica sia molto grave, soprattutto per i trasferimenti di Volontari verso il Nazionale e verso i regionali. Bisogna verificare se ci sono molte situazioni di questo tipo in essere. Guardando su luke (ma non so a quando è aggiornato il db), sono presenti 15 estensioni verso comitati regionali e 1 estensioni verso il nazionale e sono presenti 1 trasferimenti verso comitati regionali e 0 trasferimenti verso il nazionale.

**Comment by yakky** [comment]
@luca-dex quindi riasumendo:

* Non è possibile richiedere un trasferimento/estensione verso regionale / nazionale per un volontario
* I soci ordinari non possono chiedere trasferimenti o estensioni

E' corretto?

**Comment by luca-dex** [comment]
@yakky 

>Non è possibile richiedere un trasferimento/estensione verso regionale / nazionale per un volontario

Esatto. Neanche l'ufficio soci deve poterli trasferire / estendere verso questo tipo di strutture.

> I soci ordinari non possono chiedere trasferimenti o estensioni

Sì, a completamento di ciò tieni conto che quelli che al momento sono registrati come soci ordinari a breve (penso tra pochi mesi) dovranno essere tutti dimessi. Al momento non devono poter fare nessuna azione: no trasferimenti, no estensioni, no riserve. Non devono poterle fare né loro né l'ufficio soci del regionale di cui fanno.

**Comment by yakky** [comment]
@luca-dex ok

**Comment by yakky** [comment]
@luca-dex aperta PR e deployment su luke. Il caso degli ordinari è già risolto da #540

**Comment by yakky** [comment]
@luca-dex per il pregresso cosa si fa? Sono richieste aperte o approvate e attive?

**Comment by fmarco** [comment]
@luca-dex ping

**Comment by luca-dex** [comment]
@fmarco il pregresso è stato gestito a mano dal supporto
