### ISSUE TITLE
dimissioni: "mancato svolgimento turno" non possibili

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#43]
"nella schermata dove sono scritti i casi per cui questo viene dimesso, scelgo come opzione "dimissione per mancato svolgimento del turno", integro con la motivazione e clicco su registra. A quel punto mi viene chiesto di flaggare la casella di passaggio a socio sostenitore, specificando però che soltanto con le dimissioni volontarie si deve flaggare detta casella. A quel punto il volontario non viene dimesso."

**Comment by AngeloLupo** [comment]
Clone di #16, gia' risolta.
