### ISSUE TITLE
Soci: reintrodurre possibilità di modifica data inizio appartenenza attuale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#44]
da "soci" non è più possibile variare la data di inizio appartenenza al comitato, è una scelta da considerarsi voluta?

**Comment by AlfioEmanueleFresta** [comment]
Ricordo questa discussione tempo fa dovuta in particolare alle modifiche pre-elezioni - se reputi che l'incidenza sia alta, possiamo ripristinare la funzione (magari limitarla all'appartenenza **attuale**?)

**Comment by matthewmazzoleni** [comment]
l'elenco soci viene generato e firmato dal presidente, quindi di fatto una volta che la generazione rispetta le regole di anzianità quale sia la data non compete a noi saperlo con certezza, e non avremmo comunque modo di saperlo se non attraverso il presidente o US.

concordo sulla modifica solamente dell'appartenenza attuale, lo storico rimane bloccato.

**Comment by matthewmazzoleni** [comment]
abbiamo molti ticket che richiedono modifiche riguardanti le date in vista delle elezioni

**Comment by matthewmazzoleni** [comment]
necessitiamo urgentemente di questa modifica, le richieste in vista delle elezioni stanno intasando il supporto.

**Comment by AlfioEmanueleFresta** [comment]
Risolto con bffb2d42195de8ec5b26968f83a65b6906cc12c5.
