### ISSUE TITLE
[attivita] chiusura automatica

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#443]
Un significativo rallentamento di Gaia viene riscontrato da coloro che sono stati registrati come referenti di attivita per un significativo numero di attivita'. Si parla di referenti che usano Gaia da anni e sono referenti di 60+ attivita'. 

Per come funziona Gaia, e' spesso necessario risolvere e ricercare le attivita' per risolvere i permessi, parlo in particolare di questa query: https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/permessi/funzioni.py#L261. Questo causa un grande ammontare di query inutili **AD OGNI VISTA**, perche' la maggior parte delle attivita' sono nel passato e non verranno mai piu' utilizzate.

Inoltre la delega di referente, attraverso i poteri sull'attivita', da accesso alla lettura delle schede dei volontari che vi partecipano, che non dovrebbe rimanere attiva 2 anni dopo che l'attivita si e', di fatto, conclusa.

Abbiamo gia' uno stato sull'attivita che permette la chiusura manuale delle attivita'. Questo pero' attualmente non ha alcun altro scopo se non farle scomparire dalla listona delle attivita' aperte.
- [ ] Definire `timedelta` `CHIUSURA_AUTOMATICA_ATTIVITA` in `settings.py`, a qualcosa come 30gg. (@matthewmazzoleni?)
- [ ] Le attivita' che non hanno turni da almeno `CHIUSURA_AUTOMATICA_ATTIVITA` devono essere processate giornalmente da un cron. Questo si deve occupare di:
  - Cambiare lo stato dell'attivita' a chiuso;
  - Notificare l'azione a tutti i delegati dell'attivita';
  - Terminare (o sospendere?) tutte le deleghe per l'attivita'. Questo include i referenti di attivita'. Qui potrebbe essere opportuno avere un flag _sospeso_ per le 'Deleghe'. Questo deve essere controllato dal risolutore dei permessi e nel caso una delega sia 'sospesa', deve essere ignorata (con un bel `if` [qui](https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/permessi/delega.py#L12)?);
  - [ ] La notifica deve spiegare che l'archiviazione e' automatica, non e' niente di male e che nel caso si voglia aggiungere nuovi turni all'attivita', questa puo' essere facilmente riaperta.
- [ ] Per quanto e' possibile vedere i dettagli dell'attivita' in lettura, tutti i pannelli di modifica devono essere nascosti. Questo viene automaticamente dal fatto che le deleghe sono sospese e non hanno effetto, quindi il referente attivita' non viene riconosciuto per far comparire i tasti 'Modifica info', 'Modifica turni', ecc.
- [ ] In testa all'attivita', se colui che guarda ha dei permessi sospesi sull'attivita' (creare qui una funzione efficiente che sia riutilizzabile per ogni oggetto ConDeleghe), dare la possibilita' di riaprire l'attivita'. In particolare questo deve, oltre che 'de-sospendere' le deleghe, impostare lo stato dell'attivita' ad aperto.
- [ ] La lista delle attivita' chiuse (attualmente `/attivita/gestisci/chiuse/`, sicche' conterra' centinaia o migliaia di attivita' per i grandi comitati, deve essere paginata. Visto che sono due facce della stessa medaglia (aperte e chiuse usano la stessa vista), punti bonus se la soluzione automaticamente pagina anche le attivita' aperte.
- [ ] Mi piacerebbe che la funzionalita' venga realizzata separando in due parti:
  - [x] La 'sospensione' delle deleghe deve essere realizzata in modo indipendente e agnostico, sul modello 'Delega' e sul Mixin 'ConDeleghe';
  - [ ] Il Mixin deve permettere la sovrascrittura delle funzioni callback per gli eventi di sospensione e de-sospensione. Ad esempio, il modello Attivita' deve implementare tali callback per cambiare lo stato dell'attivita' da aperto a chiuso e viceversa.
  - [ ] L'invio delle e-mail di notifica deve essere fatto in modo 'generico' da parte del Mixin, **non** dentro il modello Attivita.
- [ ] Nell'elenco delle deleghe attuali, passate, deve essere possibile vedere le deleghe 'sospese'.
- [ ] La funzione `me.oggetti_permesso` deve includere di default tutti gli oggetti con delega sospesa. Ad esempio, la funzione deve includere in firma `def oggetti_permesso(permesso, ..., usa_deleghe_sospese=True, ...)`. Questo permette ai delegati correnti di continuare a vedere le attivita' nella lista, anche mentre l'attivita' e' sospesa. (/cc @luca-dex)
- [ ] Le attivita' gia' chiuse devono avere i referenti con deleghe sospese (migrazione)
- [ ] Ricerca di attivita' per nome dal calendario 
## 

@CroceRossaItaliana/supporto @CroceRossaItaliana/sviluppo @CroceRossaItaliana/sviluppo-collaboratori @luca-dex  pensieri?

**Comment by AlfioEmanueleFresta** [comment]
Ragazzi, questa e' veramente urgente. Proprio coloro che usano di piu' Gaia hanno ora problemi nell'usarlo perche' i tempi di caricamento sono ridicoli. I tempi aumentati si vedono pure da New Relic.

**Comment by AlfioEmanueleFresta** [comment]
@yakky @luca-dex @PaoloGiustiniani

**Comment by luca-dex** [comment]
Sono disperso in mezzo alla Bielorussia, quando arrivo a casa verifico.

Ciao

**Comment by luca-dex** [comment]
Ho riletto tutto e l'analisi che hai fatto già tiene conto di tutte le questioni di cui avevamo discusso a voce sia con te sia con @PaoloGiustiniani quando abbiamo pensato a come gestire la chiusura delle attività, quindi per me la proposta è buona e può essere implementata.

**Comment by AlfioEmanueleFresta** [comment]
@fmarco @yakky possiamo risolverla?
