### ISSUE TITLE
[corsi] bloccare accettazione aspiranti prima della data di inizio corso

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#446]
laddove il corso non fosse formalmente iniziato è opportuno bloccare la possibilità di approvare le richieste. questa operazione apparentemente banale eviterà di fatto la possibilità di commettere """errori in buona fede""".

**Comment by fmarco** [comment]
@matthewmazzoleni se non ho capito male bisogna bloccare le richieste che arrivano al direttore di corso e co. nel caso in cui il corso sia già iniziato?
Se è giusto quanto ho scritto come volete strutturare il flusso? ( la richiesta viene nascosta? o si fa una cernita prima?)

**Comment by matthewmazzoleni** [comment]
@fmarco il direttore e co. devono poter accettare una richiesta di partecipazione solo laddove il corso fosse iniziato (quindi la data del corso fosse >= oggi)

**Comment by fmarco** [comment]
@matthewmazzoleni Ah, scusa, pensavo ci fosse una negazione non voluta !
Quindi se la data di inizio del corso è < oggi non faccio processare alcuna richiesta relativa al corso, giusto? Se >= oggi rimane la solita gestione, giusto?

**Comment by fmarco** [comment]
@matthewmazzoleni ci sono novità su questa? se è corretto quanto ho scritto nell'ultimo commento come dovrà essere strutturato il flusso ?

**Comment by PaoloGiustiniani** [comment]
@fmarco qualora la data del corso sia < oggi NON è possibile processare alcuna richiesta.

Le iscrizioni potranno essere approvate a partire dalla data di inizio corso.

@matthewmazzoleni @luca-dex

**Comment by fmarco** [comment]
@PaoloGiustiniani Va bene. Per quanto riguarda l'interfaccia, le nascondiamo oppure le mostriamo ma bloccandole lato backend e frontend?

**Comment by romolox** [comment]
@PaoloGiustiniani ping

**Comment by PaoloGiustiniani** [comment]
@luca-dex

**Comment by luca-dex** [comment]
le mostriamo senza pulsante di accettazione, magari scrivendo da qualche parte (dovrebbe già esserci un box azzurro in quella pagina) che potranno accettare richieste dal giorno di inizio del corso.

**Comment by fmarco** [comment]
@luca-dex d'accordo

**Comment by matthewmazzoleni** [comment]
concordo con @luca-dex visto che altrimenti l'utente medio non avrebbe percezione dell'arrivo delle stesse e lamenterebbe assenza di richieste. credo che almeno il nominativo di chi fa la richiesta sia bene lasciarlo, senza possibilità di confermare.

**Comment by yakky** [comment]
PR Aperta, appena è pronto l'ambiente lo linko

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani Ambiente disponibile su http://pr-607.sviluppo-gaia.ovh

**Comment by luca-dex** [comment]
Ora che il sistema di deploy è su wonderbot non so più come fare a registrarmi come aspirante. Dove recupero il link con il token di conferma?

**Comment by yakky** [comment]
@luca-dex bella domanda ... @AlfioEmanueleFresta ?

**Comment by luca-dex** [comment]
Ho aperto la issue #610 per poter testare questa (e quelle che in futuro avranno lo stesso problema).

**Comment by luca-dex** [comment]
Ricordiamoci che questa senza #610 non può essere risolta
