### ISSUE TITLE
delegati d'area: mancanza delegati d'area su sedi

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#45]
non è possibile creare delegati d'area sulle sedi territoriali, ma solo sul comitato.

viene chiesto:
- di ripristinare la possibilità (stabilita da regolamento) di poter avere delegati d'area nelle sedi. (giocando di querystring direi che la pagina funziona già, basta far apparire il link nel dettaglio sede, come per gli altri referenti)
- di ripristinare le deleghe dei volontari che erano presenti (già presenti nel db)

**Comment by AlfioEmanueleFresta** [comment]
Risolto tempo addietro, perso commit sorry.
