### ISSUE TITLE
[corsi base] specificare ricerca persone per CF

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#457]
Nella schermata di ricerca persona si deve specificare che la ricerca va fatta per codice fiscale, perchè non essendi indicato gli utenti cercano per nome / cognome e ottengono risultati che non sono quelli aspettati.

![aggiungi iscritti corso base 458 2016 comitato di lainate comitato di lainate corso base il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/20182229/5e1e9304-a761-11e6-92ff-e1862bb669a1.png)

**Comment by yakky** [comment]
@luca-dex una soluzione del genere va bene?
![screenshot_20170114_215505](https://cloud.githubusercontent.com/assets/714711/21958015/2218bfbc-daa4-11e6-9223-5e596795ba27.png)

**Comment by PaoloGiustiniani** [comment]
Sarebbe meglio sostituire "Inizia a scrivere.." con "Inserisci il codice fiscale"

**Comment by yakky** [comment]
@PaoloGiustiniani modificata.
Già che c'ero ho anche allungato il numero di caratteri per l'autocompletamento a 8, per limitare ulteriormente il potenziale discovery di anagrafiche

**Comment by PaoloGiustiniani** [comment]
@yakky ok, grazie.

@luca-dex i test procedono?

**Comment by luca-dex** [comment]
Qual è la PR associata?

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani nessuna PR aperta, al momento, in attesa di conferma sulla schermata sopra.
In giornata apro PR e deployo su luke

**Comment by luca-dex** [comment]
La schermata è ok, ho controllato su luke. Per me va bene
