### ISSUE TITLE
[corsi base] direzione di un corso

### ISSUE THREAD

**Issue by galamarco** [CroceRossaItaliana/jorvik#458]
Considerata la nomina di direttori di corso fittizzi, che di fatto non portano a chiusura i corsi, si rende necessario impedire la nomina di un direttore qualora questo sia già nominato in un altro corso non ancora chiuso e aperto nel medesimo Comitato ricordando con appositi alert al presidente competente che un corso non è stato chiuso sebbene sia terminato.

**Comment by matthewmazzoleni** [comment]
@galamarco credo ti sia sfuggito #388 :)

**Comment by luca-dex** [comment]
Chiudo perchè duplicato di #388 come segnalato da @matthewmazzoleni. @galamarco scrivi pure in coda a #388 eventuali indicazioni aggiuntive così abbiamo tutto in un posto unico. :+1:
