### ISSUE TITLE
[sostenitori] Chiudere le appartenenze dei sostenitori

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#459]
Ci sono diverse situazioni in cui sarebbe necessario chiudere le appartenenze dei sostenitori:
- quando si effettua la procedura di recupero di una persona che risulta già essere sostentore di un Comitato, è impossibile reclamarla come Volontario sul Comitato stesso perchè la persona ha già un'appartenenza aperta;
- quando una persona iscritta ad un corso base come sostenitore diventa Volontario, se non si chiude l'appartenenza come sostenitore nei selettori continuerà a comparire la dicitura `Mario Rossi (Sostenitore del Comitato di XYZ)` che crea problemi soprattutto in fase di pagamento delle quote.

Sarebbe necessario poter chiudere le appartenenze come sostenitore di una persona, mantenendole in uno storico come per i volontari dimessi. Qualcosa tipo sostenitori passati o similari.

**Comment by luca-dex** [comment]
@yakky quando hai tempo guardi questa se non ci sono issue con priorità superiore?

**Comment by yakky** [comment]
@AlfioEmanueleFresta da quanto emerso con @galamarco qui sarebbe sufficiente permettere l'appartenenza come sostenitore a fianco di quella come volontario, che a quanto ho capito è una possibilità permessa dal regolamento. Confermate?

**Comment by yakky** [comment]
Ovvero: qui https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/models.py#L937 sostituire i filtri restituendo False solo se ci sono appartenenze attuali come volontario. Tutte le altre appartenenze sono ortogonali e non dovrebbero influire sullo status di reclamabile

**Comment by galamarco** [comment]
per "sostenitore" cosa intendiamo tra le seguenti?
a) Volontario CRI che paga di più per quell'anno ed è anche sostenitore (socio sostenitore)
b) Cittadino che versa una somma e prima si chiamava socio ordinario (ora donatore)

Nel primo caso sarebbe utile verificare con @luca-dex se quest'anno è previsto o meno...

**Comment by luca-dex** [comment]
Fermi tutti, penso ci sia delle confusione. Cerco di fare chiarezza che penso ci sia un po' di confusione sulle varie tipologie di persone che abbiamo da gestire.

Gli unici soci che esistono in Croce Rossa sono i Soci dei comitati, che chiamiamo Volontari. I Soci Sostenitori non esistono più, ma si sono trasformati in quelli che attualmente chiamiamo Sostenitori, ossia delle persone che hanno fatto una o più donazioni economiche a Croce Rossa.

Fatta questa premessa l'obiettivo è quello di permettere ai Comitati di avere un elenco di Sostenitori a cui poter mandare, ad esempio, una email per spingerli a fare una donazione o per aggiornarli sulle attività del Comitato. Spesso capita che persone che sono Sostenitori di un Comitato decidano di diventare Volontari facendo il corso per Volontari, questo causa, a fine corso, la situazione in cui le persone hanno una doppia appartenenza. Per quanto possa non essere un problema questa situazione, in realtà si vengono a creare le due problematiche che ho descritto in apertura della issue.

Quindi le richieste sono:

1. Poter chiudere le appartenenze dei sostenitori (allo stesso modo in cui avvengono le dimissioni). È lecito che una persona ci chieda di non ricevere più comunicazioni dal Comitato, attualmente, non potendo chiudere le appartenenze, chiunque sia stato registrato in quell'elenco vi permarrà per sempre.

2. Fare in modo che se un Volontario ha anche un'appartenenza come sostenitore, questa non compaia quando lo si cerca tramite i selettori: deve comparire la sua appartenenza attuale come Volontario e non quella da sostenitore.

3. Se tramite la procedura di Reclama Persona reclamo un sostenitore, il sistema mi deve avvisare che non posso proseguire perchè la parsona ha già un'appartenenza sul comitato (cosa che avviene) e mi deve suggerire di chiudere l'appartenenza come Sostenitore per completare l'azione.

A disposizione

**Comment by yakky** [comment]
@luca-dex ok, grazie dei chiarimenti

**Comment by luca-dex** [comment]
@yakky ci segnalano che prenderlo la URL di dimissione di un Volontario e passando l'ID di un sostenitore questo viene dimesso. Questa cosa genera grossi problemi, perchè penso che a questo punto la persona finisca nei volontari dimessi, cosa che non deve capitare.

**Comment by yakky** [comment]
@luca-dex prima bisogna passare il form di conferma delle dimissioni ed è tutto sotto controllo dei permessi. Ti risulta che sia possibile dimettere qualcuno senza averne i permessi?

**Comment by yakky** [comment]
@luca-dex per un sostenitore la chiusura dell'appartenenza come si chiama? immagino non "dimissione"

**Comment by yakky** [comment]
ovvero: Dobbiamo fare una vera dimissione (usando l'oggetto ``Dimissione``) o si chiude l'appartenenza e basta?

**Comment by luca-dex** [comment]
Se sono ufficio soci posso dimettere dei sostenitori come fossero dei volontari. Se sono US ho i permessi sui sostenitori e gaia esegue l'azione che uscirebbe su dei sostenitori. Ora, tenendo conto che l'operazione di dimissione dei sostenitori non è implementata, e che i sostenitori non diventano volontari dimessi, questa operazione non è lecita.

Dobbiamo fare una vera dimissione, in quanto dobbiamo tracciare il tutto. Che ci sia un motivo non è importante, possiamo decidere noi un default per questa situazione. ma che arrivi una notifica alla persona si e deve essere tracciato l'autore dell'operazione. Oltre a ciò, tenendo conto che i sostenitori sono persone che hanno donato del denaro a Croce Rossa, non possiamo semplicemente chiudere l'appartenenza e basta ma dobbiamo poi visualizzarli dentro ad un qualche elenco di ex sostenitori. Può essere che non sia usare l'oggetto `Dimissione` per fare ciò che ho detto, ma questo è legato al fatto che io non ho la minima idea di come questo oggetto sia strutturato :dancer: .

Dimmi se sono stato chiaro

**Comment by yakky** [comment]
@luca-dex chiaro
@AlfioEmanueleFresta a questo punto userei l'oggetto ``Dimissione`` come per i volontari, eventualmente con un motivo specifico e un allegato elenco di ex-sostenitori (cioè persone con appartenenza Sostenitore chiusa e senza altre appartenenze aperte, altrimenti ci finirebbero i sostenitori che diventano volontari)

**Comment by luca-dex** [comment]
In realtà ad occhio ti direi che è corretto che i sostenitori che sono diventati volontari compaiano nell'elenco degli ex-sostenitori. Pareri? @AlfioEmanueleFresta @PaoloGiustiniani @matthewmazzoleni

**Comment by yakky** [comment]
Nella PR ho messo dei punti elenco con le modifiche da effettuare @luca-dex potresti ricontrollarle per verificare che abbia riassunto correttamente?

**Comment by yakky** [comment]
@luca-dex su luke ho fatto il deploy della PR che dovrebbe essere completa secondo i sei punti indicati nella descrizione della PR
