### ISSUE TITLE
migrazione: verifica utenti non migrati

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#46]
giungono alcune segnalazioni di utenti non presenti nella nuova gaia, elenco alcuni casi così da permettere indagine su casistica allargata

**CASI:**

**1)**
prima: utente 74312 (appartenenza valida + estensione)
ora: non è presente in Gaia

**2)**
prima: 10742
ora: non presente presso comitato (né cercando da interfaccia admin). viene segnalato come presente se il comitato cerca di inserirlo.

**3)**
prima: 121843 correttamente associata a Comitato
ora: presente come entità persona 108224 ma non associata

**Comment by matthewmazzoleni** [comment]
aggiungo caso AD OGGI presente: persona 155959 presente ma mancata appartenenza

**Comment by matthewmazzoleni** [comment]
aumentano segnalazioni di volontari mancanti (anche non aventi in precedenza il CF)

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
up

**Comment by matthewmazzoleni** [comment]
altro ticket: EGO-722-78827

**Comment by AlfioEmanueleFresta** [comment]
Come discusso con @matthewmazzoleni, in seguito a delle importazioni massive che dovrebbero aver rimosso gran parte del pregresso, e all'analisi fatta dei dati, sembra che siamo rimasti un numero esiguo di casi.

Per questa ragione, l'operazione non giustificherebbe lo sforzo di sviluppo. Piuttosto, raccoglieremo tutti i casi in un documento ad uso interno e utilizzeremo il tempo del personale di supporto unito a del tempo del personale di sviluppo per ripristinare manualmente le casistiche che verranno segnalate.

Per ogni scheda anagrafica segnalata ci occuperemo di importare:
1. I dettagli anagrafici (`anagrafica.Persona`),
2. L'Utenza (`autenticazione.Utenza`),
3. Le appartenenze (`anagrafica.Appartenenza`),
4. Le quote pagate (`ufficio_soci.Quota`).
