### ISSUE TITLE
[corsi base] Possibilità di eliminazione degli iscritti

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#461]
Si presentano spesso situazioni come la seguente:
- una persona si è iscritta ad un base, è stato confermato, ma segnala di non voler più partecipare a seguito dell'inizio di un base in altra località a lui più comoda in cui non può però essere iscritto (o per qualsiasi altra motivazione)
- un sostenitore del comitato è stato inserito nel corso base per errore e deve essere rimosso (non c'è la proceduradi conferma dell'iscrizione)
- è stata per errore accettata al base una persona che non doveva essere accettata

Attualmente per tutte queste situazioni deve intervenire il supporto, queste a volte pregiudica il corretto iter di svolgimento di un base o non permette ad una persona di iscriversi ad un altro base per le tempistiche di gestione della pratica.

Sarebbe sufficiente permettere la cancellazione, da parte del direttore del corso, di un iscritto, così da svincolarlo da quel base. La cancellazione potrebbe essere tracciata senza problemi allo stesso modo in cui si traccia un corso base non superato, lo si registra come cancellato da quel corso base.

**Comment by luca-dex** [comment]
@yakky quando hai tempo guardi questa se non ci sono issue con priorità superiore?

**Comment by yakky** [comment]
@AlfioEmanueleFresta  ha senso modellare la cancellazione ritirando la ``PartecipazioneCorsoBase`` relativa?

**Comment by AlfioEmanueleFresta** [comment]
@yakky, si, ma prima vorrei che @matthewmazzoleni si esprimersi in merito al ritirarsi dal corso base

**Comment by matthewmazzoleni** [comment]
@AlfioEmanueleFresta sai che sono contrario alla "cancellazione" da un corso base, detto questo il problema è reale e va affrontato. per me è accettabile solo laddove venga mantenuta traccia e sia gestito uno stato di "ritirato" che mantenga traccia dell'operazione avvenuta, della persona che l'ha effettuato e notifichi all'aspirante la cosa. metterei anche un box rosso che indichi chiaramente al direttore o chi per esso che la cosa è tracciata e l'aspirante ne verrà informato, così da prevenire abusi.

**Comment by yakky** [comment]
@luca-dex @matthewmazzoleni modifica caricata su luke secondo quanto espresso sopra.

* La partecipazione (o l'invito) dell'utente viene ritirata
* L'utente riceve una notifica dell'avvenuto ritiro
* Chi cancella l'iscrizione riceve appropriato messaggio come sopra

**Comment by luca-dex** [comment]
Ok, devo fare tante prove. Come recupero i link di autorizzazione degli aspiranti? Possiamo disabilitare questo check su luke?

**Comment by luca-dex** [comment]
Stasera provo

**Comment by yakky** [comment]
@luca-dex tu hai accesso console a luke?

**Comment by luca-dex** [comment]
Ho iniziato a revisionare la cancellazione, in linea di massima mi sembra che la procedura sia sensata. La schermata che ci si trova davanti alla pressione del tasto cancella è la seguente:

![iscritti corso base 128 2017 comitato di lainate comitato di lainate corso base il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/22599944/f01ff0bc-ea38-11e6-9206-debe1e9da9b5.png)

Per evitare che la gente giochi modificherei il testo nel seguente modo:

Cancellazione iscritto <nome_cognome>

Questa operazione non deve essere eseguita nel caso di persone assenti alle lezioni del Corso. Le assenze possono essere annotate nella sezione dedicata e la persona potrà non essere ammessa all'esame finale, qualora non abbia frequentato un numero sufficiente di lezioni.

La cancellazione di un iscritto da un Corso Base è una procedura da utilizzare solamente nelle seguenti situazioni:
* la persona ha comunicato di non poter seguire il corso
* la persona è stata ammessa per errore
* la persona è stata ammessa al corso, ma vuole seguire il Corso Base presso un'altra sede CRI
A seguito di questa operazione verrà inviata una notifica via email alla persona che si sta cancellando per informarla di questa azione e contenente informazioni su come contattare chi ha effettuato la cancellazione. Ti verrà trasmessa copia del messaggio.

L'operazione non è in nessun modo reversibile.

Pareri su questa cosa? @AlfioEmanueleFresta @matthewmazzoleni 


@yakky cliccando sul pulsante "Inviti Corsi Base", che punta a `/aspirante/corsi-base/inviti/` ottengo 404

**Comment by luca-dex** [comment]
Ho controllato il testo dell'email che viene mandata alla persona e che dice:

>Ciao Luca,
ti scriviamo per informarti dell'annullamento della tua iscrizione al "corso base" per Volontari CRI
    organizzato dal Comitato di Lainate con inizio il
    15/02/2017 09:42, presso:
    Via Marche, 62, 20020 Lainate MI, Italia (vedi in mappa).
Qualora tu ritenga che la disiscrizione sia un errore ti invitiamo a rivolgerti al Comitato di Lainate per maggiori informazioni

Secondo me dovremmo inserire il nominativo della persona che ha fatto la cancellazione, così che la persona cancellata sappia chi ha effettuato l'operazione.

Non trovo invice traccia dell'email che dovrebbe essere stata mandata alla persona che ha effettuato la cancellazione.

**Comment by AlfioEmanueleFresta** [comment]
👍 . Oltre al,

`Ti scriviamo per informarti che Mario Rossi ha annullato la tua iscrizione...`

Il mittente del messaggio dovrebbe essere colui che effettua l'annullamento, cosi' se l'aspirante risponde incazzato, se la vedono tra di loro.

**Comment by luca-dex** [comment]
Scusate, sono io che non ho guardato bene, il mittente è già colui che effettua l'annullamento.

**Comment by matthewmazzoleni** [comment]
@luca-dex purtroppo l'abuso con questa funzione è di fatto non controllabile. mi assicurerei che non fosse possibile cancellare qualcuno una volta concluso il corso, altro non credo sia possibile fare..

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta aggiornati i testi e aggiunta l'email a chi effettua la cancellazione
Deployato su luke
