### ISSUE TITLE
[login] errore 500 per taluni utenti

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#462]
taluni utenti segnalano che, dopo aver inserito le credenziali e premuto il pulsante di accesso ,ricevono errore 500.

verificabile per utenza 4957

**Comment by yakky** [comment]
@PaoloGiustiniani @AlfioEmanueleFresta è disponibile un traceback dell'errore?

**Comment by PaoloGiustiniani** [comment]
@matthewmazzoleni simulando una sessione il problema non lo riscontro, hai ulteriori dati?

**Comment by matthewmazzoleni** [comment]
@PaoloGiustiniani io l'ho riprodotto semplicemente facendo il "login as user" di 4957

**Comment by PaoloGiustiniani** [comment]
@yakky

**Comment by AlfioEmanueleFresta** [comment]
Questo e' un errore di database. Alla delega di tipo Delegato d'area della persona era presente un oggetto Sede. Ho eliminato la delega incriminata. Credo questo provenga da un vecchio bug ormai risolto.

**Comment by AlfioEmanueleFresta** [comment]
@CroceRossaItaliana/supporto possiamo avvertire l'utente?
