### ISSUE TITLE
reclama persona: errore 500 in taluni casi

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#47]
inseriti tutti i dati della seconda pagina (data di ingresso, data pagamento quota, ecc..), quando clicco sul pulsante per reclamare il volontario si apre una pagina con scritto errore 500. Questo è successo diverse volte in diversi momenti della giornata.

utente esecutore: 8135

**Comment by AlfioEmanueleFresta** [comment]
Il problema e' relativo all'inserimento della quota, come segnalato da alcuni di questi utenti. In questo momento il tesseramento 2015 e' chiuso e il 2016 e' ancora da definire in termini di quota, quindi ho disattivato la possibilita' di inserire la quota, forzando la scelta a "No, inserirò più tardi la quota").

Dopo il 2 febbraio, successivo alla data del 30 gennaio quando dovrebbero essere decisi gli importi per la quota, riattivero' la funzione (e mi assicurero' che fallisca con un errore piu' amichevole)
