### ISSUE TITLE
[notizie interne] segmenti non funzionanti

### ISSUE THREAD

**Issue by galamarco** [CroceRossaItaliana/jorvik#471]
Ho pubblicato una news con segmento "Volontari **da più** di un anno" e non appare a chi ha più di un anno di anzianità. Al contrario, seleziono il segmento "Volontari **da meno** di un anno" appare a quelli con **più** di un anno di anzianità.

La verifica che appaia o meno è avvenuta con la mia utenza e con quella di Ilaria Forte che entrambi dovremmo risultare da più di un anno nell'associazione.

Url articolo lato admin: ..../admin/articoli/articolo/49/change/

**Comment by yakky** [comment]
@galamarco caricata su luke la correzione del problema

**Comment by PaoloGiustiniani** [comment]
@galamarco qui per testarlo: http://luke.staging.sviluppo-gaia.ovh/

In alternativa girami via email come replicare il problema.

**Comment by galamarco** [comment]
Dal test fatto sembra funzionare correttamente su Luke.

**Comment by PaoloGiustiniani** [comment]
@galamarco ok la mando in produzione a breve.
