### ISSUE TITLE
[supporto] Volontario/Aspirante per il quale si richiede assistenza

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#479]
Come in passato, nella pagina dedicata al supporto, bisogna ripristinare la possibilità di selezionare il volontario per il quale si sta richiedendo supporto.

Apparirà questa funzionalità ad US e Presidente.

Lato ticket sarà incluso nella richiesta il dettaglio del volontario (come per chi apre la richiesta di supporto).

**Comment by luca-dex** [comment]
Penso che questa issue sia un duplicato di #214

**Comment by PaoloGiustiniani** [comment]
hai ragione.
