### ISSUE TITLE
deleghe formazione: problemi post migrazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#48]
**situazione precedente:**
utente 639.
delega alla formazione attiva + (una deleghe alla formazione conclusa precedentemente)

**situazione attuale:**
l'utente non vedeva il tab "formazione", il presidente ha provato a terminare la delega per poi ri-delegarlo. non risulta possibile dare nuovamente la delega all'utente.

**segnalo quindi:**
[] - delega non mostrava tab "formazione"
[] - delega una volta terminata non permette nuova delega alla persona

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni puoi gentilmente confermarmi che questa questione si e' risolta?
