### ISSUE TITLE
[riserva] Utenti possono di aprire riserve nel passato

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#484]
Mentre per l'ufficio soci mi sembra sia senzato permettere di inserire riserve con data di inizio precedente a quella attuale (per registrare riserve gestite a mano o da volontari che non riescono ad utilizzare Gaia), non vedo perchè un utente dovrebbe richiedere una riserva nel passato (vedi immagine)

Penso possa essere sensato non permettere all'utente di richiedere riserve nel passato, anche per evitare problemi di persone che non si presentano ad attività giustificandolo col chiedere oggi una riserva per un mese fa.

![-5 richieste il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/21954854/dab481f6-da5d-11e6-9b99-9d738409005e.png)

**Comment by yakky** [comment]
@luca-dex l'ho presa al volo perché comunque era banale

**Comment by luca-dex** [comment]
Si si, nessun problema, roba da 2 minuti.
