### ISSUE TITLE
Importazione da Gaia (import.py)

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#5]
Importare le seguenti entita' da Gaia - in ordine di [gaia.sql](https://github.com/CroceRossaCatania/gaia/blob/master/upload/setup/gaia.sql):

- [x] Persona -> anagrafica.Persona
- [x] ~~Annuncio -> cms.Annuncio?~~
- [x] ~~APIKey -> api.APIKey?~~
- [x] Appartenenza -> anagrafica.Appartenenza
- [x] Area -> attivita.Area
- [x] Aspirante -> anagrafica.Aspirante?
- [x] Autoparco -> anagrafica.Sede?
- [x] Autorizzazione -> base.Autorizzazione
- [x] Avatar -> anagrafica.Persona:avatar
- [x] CollocazioneVeicolo -> veicoli.Collocazione
- [x] Comitati -> anagrafica.Sede
  - [x] Rimozione Comitati principali 
- [x] Commenti -> social.Commento
- [x] CorsoBase -> formazione.Corso?
- [ ] CoTurno -> co.Turno
- [x] Dimissione -> anagrafica.Dimissione/us.Dimissione?
- [x] Documento -> anagrafica.Documento
- [x] Donazione -> sangue.Donazione
- [x] DonazioneAnagrafica -> sangue.Donatore
- [x] DonazioneMerito -> sangue.Merito
- [x] DonazionePersonale -> sangue.Donazione
- [x] DonazioneSede -> sangue.Sede
- [x] ~~Email -> posta.Messaggio?~~
- [x] ~~Allegato -> posta.Allegato?~~
- [x] ~~Destinatario* -> posta.Destinatario?~~
- [x] Estensione -> anagrafica.Estensione/us.Estensione?
- [x] FermoTecnico -> veicoli.Fermo?
- [x] ~~File -> base.File~~
- [x] Fototessera -> anagrafica.Fototessera?
- [x] Gruppo -> attivita.Gruppo
- [x] GruppoPersonale -> attivita.Appartenenza
- [x] Lezione -> formazione.Lezione
- [x] AssenzaLezione -> formazione.Assenza?
- [x] Comitato -> anagrafica.Sede
- [x] Locale -> anagrafica.Sede
- [x] Provinciale -> anagrafica.Sede
- [x] Regionale -> anagrafica.Sede
- [x] Nazionale -> anagrafica.Sede
- [x] Manutenzione -> veicoli.Manutenzione?
- [x] ~~Like -> social.Giudizio?~~
- [x] Partecipazione -> attivita.Partecipazione
- [x] PartecipazioneBase -> formazione.Partecipazione
- [x] Privacy -> anagrafica.Policy?
- [x] Provvedimento -> anagrafica.Provvedimento/us.Provvedimento?
- [x] Quota -> anagrafica.Quota/us.Quota?
- [ ] Reperibilita -> co.Reperibilita?
- [x] Rifornimento -> veicoli.Rifornimento?
- [ ] Riserva -> anagrafica.Riserva/us.Riserva?
- [x] Tesseramento - > anagrafica.Tesseramento/us.Tesseramento?
- [x]  TesserinoRichiesta -> us.Tesserino
- [x] Titolo -> curriculum.Titolo?
- [x] TitoloPersonale -> curriculum.Qualifica?
- [x] Trasferimento -> anagrafica.Trasferimento/us.Trasferimento
- [x] Turno -> attivita.Turno
- [x] ~~Validazione -> base.Token?~~
- [x] Veicolo -> veicoli.Veicolo

**Comment by PaoloGiustiniani** [comment]
(+1)

**Comment by ico88** [comment]
@AlfioEmanueleFresta quando verrà reinserito il sistema di reperibilità ?
