### ISSUE TITLE
attività: richiesta di attività non mostrata ne "i miei turni"

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#50]
71173 segnala che una richiesta effettuata per la partecipazione ad una attività già approvata da referente (prima della migrazione) è presente nel foglio di servizio ma non nella pagina "miei turni".

info partecipazione: per sabato 23.01.2016, turno 7-14.00

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni il turno era presente in elenco. I due elenchi ottengono gli stessi turni, solo il foglio di servizio in excel esclude quelli con conferma negata. 

Credo il problema fosse che l'ordinamento era fatto per data di richiesta, che non essendo presente nel vecchio db era stata impostata in ordine casuale, quindi non riusciva a trovare il turno nella lista. Sistemato: ora i turni sono ordinati per data di inizio turno decrescente.
