### ISSUE TITLE
[trasferimenti] Vengono segnalati come da approvare anche trasferimenti annullati dall'utente

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#502]
Sono ufficio soci del mio comitato e mi è arrivata la segnalazione che una mia richiesta di trasferimento (che avevo fatto a scopo di test e poi revocato) è in attesa di essere approvata. 
![screenshot at 2017-01-18 17-50-01](https://cloud.githubusercontent.com/assets/3315913/22073847/c9364a6c-dda6-11e6-9ebe-4406f22c2e80.png)

**Comment by PaoloGiustiniani** [comment]
la data in formato Italiano, per favore

**Comment by yakky** [comment]
@PaoloGiustiniani devo indagare il perché della data formattata in quel modo visto che è stato usato il solito code style. Intanto ho aperto una PR per il problema originario

**Comment by yakky** [comment]
Per la data faccio un deployment su luke, perché in locale viene formattata correttamente
