### ISSUE TITLE
[articoli] Errore 500 se esiste un altro articolo con lo stesso titolo (anche scaduto)

### ISSUE THREAD

**Issue by galamarco** [CroceRossaItaliana/jorvik#509]
Salvando un nuovo articolo con titolo uguale ad un precedente appare il messaggio "Server Error (500)".
Forse sarebbe opportuno far apparire un messaggio di errore del tipo "scegli un altro titolo, questo esiste già"

Questo succede anche se il vecchio articolo è ormai scaduto.

URL:
https://gaia.cri.it/admin/articoli/articolo/add/

**Print prima di salvare**
![image](https://cloud.githubusercontent.com/assets/5132398/22157680/f3d2807c-df38-11e6-9111-cd2fb82a4527.png)

**Print cliccando su "salva"**
![image](https://cloud.githubusercontent.com/assets/5132398/22157535/5de103ae-df38-11e6-88a8-761280c592df.png)

**Comment by AlfioEmanueleFresta** [comment]
@yakky, la butto lì, slug?

**Comment by yakky** [comment]
@galamarco il fix è caricato su luke (avevo commentato nella PR, non qui, scusate)
