### ISSUE TITLE
[quote] Estensione sistema di tesseramento a donatori sangue e volontari con status di rifugiato

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#514]
A breve verranno pubblicate le indicazioni per il tesseramento 2017. A livello di gaia è necessario introdurre in maniera estremamente rapida la gestione di due situazioni molto simili:
* soci Volontari che sono anche donatori di sangue e che hanno meno di 25 anni, che quindi hanno la possibilità di pagare una quota ad importo agevolato (1,00 €)
* soci Volontari che sono anche rifugiati e che quindi hanno la possibilità di pagare una quota socio ad importo agevolato (1,00 €)

Le caratteristiche precise delle categorie da prevedere chiedo a @PaoloGiustiniani e @galamarco di dettagliarle meglio.

La schermata attuale di inserimento delle quote è la seguente:

![nuova quota volontario il progetto gaia croce rossa italiana](https://cloud.githubusercontent.com/assets/3315913/22178284/446e4256-e032-11e6-8b7c-df114e2bbd73.png)

Quello che propongo è di inserire due radio button con le due opzioni, mutualmente esclusive, nel punto che ho indicato con la freccia che deve essere gestito nel seguente modo:
* testo dei due flag, che devono sicuramente essere riveduti e corretti: 
  * "Agevolazione per Rifugiati - Come previsto dal regolamento XYZ i Volontari CRI che godono dello status di Rifugiati hanno la possibilità di pagare una quota di importo agevolato di 1,00 €"
  * Agevolazione per Donatori di Sangue con meno di 25 anni - Come previsto dal regolamento XYZ i Volontari CRI che si impegnano anche ad effettuare almeno una donazione di sangue a favore di Croce Rossa nell'anno solare hanno la possibilità di pagare una quota di importo agevolato di 1,00 €"
* variazione del prezzo minimo della quota (lato js per la parte di visualizzazione della pagina e lato controlli in fase di registrazione della quota) sulla base delle indicazioni e verifica dell'età per le quote con vincolo di donazione sangue
* registrazione da qualche parte (dettagli associati alla quota) del fatto che si è pagata una quota speciale, ad esempio segnando "Agevolazione donatori sangue" e "Agevolazione Rifugiati"
* eventuali eccedenze rispetto all'importo minimo devo essere registrate, come già avviene ora, come donazione

Chiedo ad @AlfioEmanueleFresta di valutare se a livello di architettura di gaia questa soluzione può avere senso.
Questa issue ha carattere di estrema urgenza.

**Comment by yakky** [comment]
@luca-dex @AlfioEmanueleFresta @galamarco @PaoloGiustiniani assegnatemi pure quando tutti i dettagli sono chiari e definiti (compresi i testi) così la mettiamo subito in lavorazione

**Comment by luca-dex** [comment]
Siamo in attesa di info

**Comment by galamarco** [comment]
@luca-dex purtroppo non ho visto nemmeno la bozza di questo regolamento, temo di non essere di grande aiuto fino a quando non è uscito e potrebbe essere tardi. Non possiamo recuperare queste info tramite Rosario?

**Comment by luca-dex** [comment]
Provvedo

**Comment by luca-dex** [comment]
Rosario dice di attendere la pubblicazione della delibra, quindi al momento rimaniamo in attesa di maggiori delucidazioni.

**Comment by luca-dex** [comment]
Abbiamo ricevuto comunicazione da Rosario circa il tesseramento. Le cose sono come ho riportato in apertura della issue, quindi si può procedere senza problemi l'implementazione.

Appena possibile indico i testi da inserire definitivi, in attesa dei quali queste sono le indicazioni:
* testo informativo nella pagina http://luke.staging.sviluppo-gaia.ovh/us/quote/nuova/ che spiega le indicazioni per il tesseramento
* testo dei due radio button "agevolazione richiedenti asilo o rifugiati" e "agevolazione per donatori sangue con meno di 25 anni"
* le due diciture riportate sopra sono da utilizzare anche all'interno della ricevuta che verrà registrata e nelle note relative alla quota nei dettagli della quota

**Comment by luca-dex** [comment]
Ecco il testo da usare in testa alla pagina:

_L'importo stabilito per la quota dei Soci CRI per il 2017 è di € 10,00. A seguito delle decisioni Assemblea Nazionale è stata introdotta una quota con importo agevolato ad € 1,00 per le seguenti categorie di Soci:_

- _Soci CRI con meno di 25 anni e che accedono all'iniziativa Club25 legata alla donazione di sangue_
- _Soci CRI che si trovano nella condizione di Richiedenti Asilo oppure per i quali è stata concessa la Protezione Internazionale (Asilo/Status di Rifugiato o Protezione Umanitaria) oppure per i quali è stata concessa la Protezione Sussidiaria._

_Eventuali importi eccedenti quello fissato per la quota verranno registrati come donazione al Comitato._

**Comment by AlfioEmanueleFresta** [comment]
Aggiungo a quanto sopra, che la soluzione dovrebbe rispettare i seguenti criteri,:
* La validazione deve avvenire sia a livello di Javascript sul browser (modificando opportunamente il parametro `min` del campo, secondo standard HTML5, per garantire accessibilita'), che a livello di server,
* La modifica dei minimi deve essere centralizzata da qualche parte nel codice. Per intenderci, se le categorie speciali variano, o il minimo cambia, deve essere possibile modificare il codice in un singolo punto di innesto, che andra' a modificare sia la validazione in Django, che nel template,
* Il codice Javascript dovrebbe, al click su una opzione particolare, oltre che modificare il minimo per la validazione del campo del valore, *se e solo se* il valore manuale non e' stato cambiato, cambiarlo col nuovo minimo. Per intenderci, il campo del valore della quota versata dovrebbe automaticamente contenere sempre il minimo per il tipo di quota (8 euro normalmente, o 1 euro in caso speciale), ma deve essere possibile modificarlo manualmente. Nel caso l'utente inserisca prima l'importo di 10 euro, e poi selezioni che la il volontario ha stato di richiedente asilo, il valore maggiorato gia' inserito non deve essere sostituito dal minimo per la classe scelta,
* Sicche' stiamo parlando di una parte cruciale della vita associativa, e' fondamentale aggiornare i test funzionali relativi al pagamento della quota, in modo che includano i casi speciali presentati sopra.

**Comment by PaoloGiustiniani** [comment]
@yakky ho una richiesta cattiva: domani è pronta in serata?

**Comment by PaoloGiustiniani** [comment]
@yakky avrei bisogno di un feedback

**Comment by yakky** [comment]
@PaoloGiustiniani oggi non ci si fa. Domani potremmo avere una versione 1.0 senza alcuni automatismi lato frontend, ma sufficiente comunque per poter procedere con il tesseramento

**Comment by luca-dex** [comment]
Di base però iniziamo almeno con l'importo a 10€

**Comment by yakky** [comment]
Il cambio dell'importo viene gestito nell'admin configurando il tesseramento

**Comment by yakky** [comment]
@luca-dex dal momento che i radio non sono deselzionabili pensavamo di inserire una voce "Volontario" (default) che conserva il comportamento attuale. Altrimenti se per errore viene selezionata una delle due voci agevolate è poi necessario ricaricare la pagina per annullare la selezione.
Cosa ne pensi?

**Comment by yakky** [comment]
@luca-dex da un'analisi del codice non mi risulta che ci sia attualmente lo split tra quota socio e donazione se il totale eccede la quota standard

**Comment by luca-dex** [comment]
Non è definita dalla quota minima del tesseramento?

**Comment by AlfioEmanueleFresta** [comment]
@yakky si, vedi https://github.com/CroceRossaItaliana/jorvik/blob/master/ufficio_soci/models.py#L416

**Comment by yakky** [comment]
@AlfioEmanueleFresta pensavamo di gestirlo estendendo il tipo di quote disponibili (però questo significa che le interrogazioni non vanno più fatte con ``Quota.objects.filter(tipo=Quota.QUOTA_SOCIO)`` ma ``Quota.objects.filter(tipo__in=Quota.QUOTE_SOCI)`` (dove quote soci è l'insieme delle 3 tipologie) e inserendo sul tesseramento un campo "quota_agevolata"

**Comment by yakky** [comment]
@AlfioEmanueleFresta stavo cercando nella view. Tks per il pointer

**Comment by yakky** [comment]
@luca-dex per la ricevuta andrebbe bene modifcare la causale in qualcosa del tipo "Rinnovo Quota Associativa 2017 - Agevolazione richiedenti asilo o rifugiati" (e uguale per under 25)

**Comment by yakky** [comment]
@luca-dex immagino sia da modificare anche il "reclama persona" con le stesse caratteristiche, è corretto?

**Comment by AlfioEmanueleFresta** [comment]
@yakky hmm, la quota e' di fatto la stessa identica quota di un socio non rifugiato. Hanno lo stesso significato e non e' necessario pescarle in modo diverso, o in elenchi diversi. E' una quota socio. 

Ho paura che aggiungendo un tipo di quota, aggiungiamo complessita' senza migliorare la rappresentazione della realta'. E' necessario registrare la riduzione solo alla registrazione. La chiamerei proprio cosi', `riduzione`, con un default `None`. 

E' anche importante scrivere qualcosa, come indicato da @luca-dex, nella causale della quota. Piuttosto che scrivere direttamente dentro il campo `causale` dell'oggetto quota, si puo' decidere di avere la descrizione full-text della riduzione come una (opzionale) riga aggiuntiva alla causale della quota.

Per intenderci, qualcosa come,
```html
<p>{{ quota.causale }}</p>
{% if quota.riduzione %}
  <p style="font-style: italic;">{{ quota.get_riduzione_display }}</p>
{% endif %}
```
(Qui notare che il paragrafo opzionale e' aperto dentro l'if, perche' non dobbiamo mutare in alcun modo le quote gia' rilasciate.)


> @yakky: @luca-dex immagino sia da modificare anche il "reclama persona" con le stesse caratteristiche, è corretto?

Si. Idealmente dovrebbe tirarsi automaticamente, in qualche modo, lo stesso form (duplicazione e' male).

**Comment by AlfioEmanueleFresta** [comment]
Una cosa importante in merito a quanto ho descritto prima: Nel caso in cui l'anno prossimo ci sono agevolazioni diverse, o cambia il totale ridotto, come ci comportiamo? Possiamo introdurre nuove costanti, lasciare quelle vecchie nel modello cosi' che vengano ripescate correttamente per le vecchie quote, ma non farle comparire nei moduli per la registrazione delle nuove quote?

**Comment by yakky** [comment]
@AlfioEmanueleFresta attualmente reclama persona usa un form diverso e una logica della view già duplicata. Vuoi che rifattorizziamo? Vista l'urgenza forse non ci sono tempi adatti per farlo.
Analogamente per una gestione completa delle riduzioni. Per renderle generiche vanno gestite come opzioni su ciascun tesseramento (per averle annualizzate), potenzialmente ciascuna con quote di riduzione specifiche ed è da decidere se gestirle come model separati, per avere una gestione completamente lato admin, o se mantenerle nel codice

**Comment by AlfioEmanueleFresta** [comment]
Sono assolutamente pro a una gestione completamente dinamica delle quote,
come già avviene infatti per i tesseramenti dalla introduzione di Jorvik. È
normale amministrazione, non dovrebbe essere necessario modificare codice
ogni anno per questo.

Per quanto riguarda il doppio modulo va bene per il rilascio immediato, ma
è importante fare del refactoring appena possibile (prima che capita
un'altra urgenza e ci ritroviamo nella stessa situazione).


Alfio

**Comment by yakky** [comment]
@luca-dex intanto faccio un deployment preliminare per validare la parte di interfaccia, selezione delle tipologie etc. Poi vediamo il refactoring e la riorganizzazione delle quote

**Comment by yakky** [comment]
@luca-dex @PaoloGiustiniani la versione preliminare con l'interfaccia di inserimento quote è a posto
Manca ancora:

* Gestione dinamica quote / riduzioni
* Gestione in reclama persona

Intanto però potete validare la parte "standard?

**Comment by luca-dex** [comment]
Stasera ci gioco
