### ISSUE TITLE
[anagrafica] raw_id_fields rotto per le sedi

### ISSUE THREAD

**Issue by yakky** [CroceRossaItaliana/jorvik#522]
mptt 0.8.6 ha rotto il selettore dei related fields to raw_id_fields  (django-mptt/django-mptt#536 )

@AlfioEmanueleFresta faccio un downgrade alla 0.8.5 per risolvere il problema mentre si sistema upstream, che ne dici? la 0.8.6 introduce solo compatibilità con Django 1.10 che non ci serve

**Comment by AlfioEmanueleFresta** [comment]
@yakky per me va bene scendere alla 0.8.6, basta che ci assicuriamo che non si rompa niente in staging prima.

Mi viene in mente che il processo automatico usa qualcosa come `pip install -r requirements.txt --upgrade`. Ora mi viene il dubbio, `--upgrade` forza la reinstallazione in caso di downgrade del pacchetto, o dobbiamo aggiungere `--force-reinstall` o simile?

**Comment by yakky** [comment]
se pinniamo la versione specifica di mptt pip obbedisce senza dare "interpretazioni sue"
Ovviamente va prima provato in staging. Preparo una PR

**Comment by AlfioEmanueleFresta** [comment]
OK

**Comment by yakky** [comment]
@CroceRossaItaliana/sviluppo caricato su luke la vecchia versione. Se fate due prove con l'albero delle sedi si fa il merge.
Dal compare delle due versioni di mptt non esce nessuna modifica sostanziale da far temere la reintroduzione di bug

**Comment by yakky** [comment]
@AlfioEmanueleFresta ritiro quanto ho detto. Ho fatto il revert del commit. Tanto per cambiare mptt ha fatto casino ... la 0.8.5 non serializza correttamente i queryset in sessione (bloccando gli elenchi).
Posso preparare un fork di mptt con la correzione e integriamo quello, in attesa di un rilascio ufficiale. Che ne dici?
