### ISSUE TITLE
roadmap: richiesta date rilascio moduli

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#53]
viene richiesta la tempistica di rilascio dei vari moduli mancanti, in quanto attualmente i comitati sono impossibilitati a gestire i corsi attualmente in svolgimento, i turni e le approvazioni degli stessi

**Comment by AlfioEmanueleFresta** [comment]
Come comunicato ieri, ti prego di comunicare **il link** con la roadmap:
https://docs.google.com/document/d/1W47WbJ7NBrRJrJV1zgYBDSDlQJQqk-Tiy38x_OmPVyo/edit
