### ISSUE TITLE
[quote] eliminare "soci ordinari"

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#536]
nella pagina /us/quote è presente:

![image](https://cloud.githubusercontent.com/assets/5826472/22603504/f7d067ba-ea47-11e6-9afb-24a633b8d4de.png)

va rimossa la voce "soci ordinari", non credo sia più necessaria nemmeno per i regionali

**Comment by luca-dex** [comment]
Mmm... non sono sicuro di questa cosa. Sono registrate le quote dei soci ordinari presso i comitati fino al 2015 su gaia. Non credo sia sensato farle svanire. Si potrebbe pensare a suddividere meglio la cosa, ma non possiamo farle amministrativamente scomparire.

**Comment by matthewmazzoleni** [comment]
@luca-dex avevo il dubbio sui regionali, ma forse hai più ragione tu dicendo che comunque (a prescindere da regionale o locale) deve essere possibile generarne l'elenco quote per motivi amministrativi..

**Comment by yakky** [comment]
@luca-dex @matthewmazzoleni quindi come procediamo?

**Comment by luca-dex** [comment]
Non procediamo, chiudiamo pure.
