### ISSUE TITLE
[trasferimenti] email di auto-approvazione con data richiesta del giorno stesso

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#537]
![image](https://cloud.githubusercontent.com/assets/5826472/22619829/53c72080-eafd-11e6-8f50-f1ad3e466912.png)

risulta questo:
![image](https://cloud.githubusercontent.com/assets/5826472/22619856/e0a8b54a-eafd-11e6-9cce-7f86c85c4e1c.png)

sembra (essendoci il firmatario) che in realtà l'approvazione sia manuale, ma nel campo "tipo gestione" essa è associata alla approvazione automatica.

**Comment by yakky** [comment]
Il testo nell'email è effettivamente una svista
Il tipo gestione riguarda in realtà non la modalità effettiva di approvazione, quanto la possibilità che sia gestito in automatico.
Comunque ho aperto #538 che corregge il template e imposta il trasferimento come gestito manualmente.
L'autorizzazione la lascerei però invariata visto il significato del campo, ma è solo una questione "cosmetica" per cui si può anche decidere di impostare il campo a gestione manuale

**Comment by PaoloGiustiniani** [comment]
Sembra essere corretto.

Ho un dubbio sul template, è stato variato? Manca il comitato verso il quale è stato richiesto il trasferimento.

![gaia](https://cloud.githubusercontent.com/assets/5071623/22625693/af208fe8-eb9d-11e6-8d46-fcf8073228bb.png)

**Comment by yakky** [comment]
@PaoloGiustiniani no. e gli altri dati del trasferimento ci sono quindi non capisco. Indago :)

**Comment by yakky** [comment]
@PaoloGiustiniani corretto l'errore (non era legato a queste modifiche, temo fosse così da diverso tempo)
