### ISSUE TITLE
estensioni: richiesta non possibile per sede in cui si era già estesi in passato

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#54]
come da oggetto 15040 cerca di estendersi su un comitato per cui era già esteso, con scadenza 8 gennaio. il sistema gli impedisce di procedere in quanto risulta già presente un'estensione su quel comitato.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo 

La definizione di `estensioni_attuali` non va bene,
```python
    def estensioni_attuali(self):
        return self.estensioni.all().filter(
            Q(pk__in=Estensione.con_esito_ok())
        )
```
Deve includere il fatto che l'appartenenza deve essere attuale, es.
```python
    def estensioni_attuali(self):
        return self.estensioni.all().filter(
            Q(pk__in=Estensione.con_esito_ok()),
            Appartenenza.query_attuale().via("appartenenza"),
        )
```

O simile. Per favore fai una prova a richiedere estensione dopo terminazione prima di pushare.

**Comment by AngeloLupo** [comment]
Fixato via bfd6d0a5b2afc1cb2ec910d9680b54594ba6148f
Il problema era quello indicato da @AlfioEmanueleFresta
