### ISSUE TITLE
Problemi/Controlli trasferimenti/dimissioni

### ISSUE THREAD

**Issue by yakky** [CroceRossaItaliana/jorvik#547]
### Volontario

Chiudere i seguenti oggetti

* [x] Deleghe
* [x] Estensioni
* [x] Trasferimenti aperti
* [x] Riserve
* [x] Nel caso di trasferimenti inserire l'appartenenza chiusa come precedente di quella nuova
* [x] partecipazioni: cancellare quelle con fine >= `poco_fa`
* [ ] notificare la chiusura di eventuali deleghe, come discusso sotto

### Dipendenti / Sostenitori

* [ ] Controllare che l'appartenenza volontario rimanga inalterata

**Comment by yakky** [comment]
@AlfioEmanueleFresta @luca-dex @PaoloGiustiniani verificate se quanto sopra è corretto?

**Comment by luca-dex** [comment]
> Cosa fare nel caso di attività, corsi & C?

@yakky parli di partecipazione ad attività / corsi o di gestione?

**Comment by yakky** [comment]
@luca-dex gestione (direttori corsi, responsabili attività etc), ma anche per i turni. Ovviamente la partecipazione ai corsi è ininfluente perché da aspirante non hai trasferimenti etc

**Comment by luca-dex** [comment]
Nella vecchia gaia le partecipazioni non ancora svolte venivano eliminate (se ti sei segnato per un turno che successivo alla data di trasferimento, non è più tuo) e gli incarichi passavano a chi stava sopra di te. Se sei referente di un'attività e ce ne sono anche altri non è un problema, se eri l'unico passa al delegato di area sopra di te e così via. Pareri @AlfioEmanueleFresta @PaoloGiustiniani @matthewmazzoleni

**Comment by PaoloGiustiniani** [comment]
Confermo con quanto detto da @luca-dex , sarebbe utile implementare questo meccanismo.

**Comment by AlfioEmanueleFresta** [comment]
> @luca-dex: Se sei referente di un'attività e ce ne sono anche altri non è un problema, se eri l'unico passa al delegato di area sopra di te e così via.

Avrebbe senso, secondo voi, una pagina di conferma del trasferimento al presidente/US del vecchio Comitato dove vengono presentate tutte le deleghe dell'utente e viene chiesto, per ognuna, di confermare se:

1. Rimuovere la delega (default)
2. Rimuovere la delega e nominare [SCEGLI PERSONA v] al suo posto
3. Mantenere la delega

So che pochi o nessuno potrebbe voler mantenere la delega per un referente di una attivita' ma il sistema sarebbe generico e si applicherebbe facilmente a ogni tipo di responsabilita' in Gaia.

La possibilita' di nominare un sostituto impedirebbe di lasciare attivita' o, in genere deleghe, scoperte o assegnarle automaticamente a gente che non gestisce di fatto niente su Gaia.

Poi il volontario che fa autoparco in una sede territoriale, solo perche' si sposta di sede in sede potrebbe poter continuare a gestire quell'autoparco.

Infine potrebbe non essere necessario modificare il sistema in futuro per nuove deleghe. Il sistema attuale di permessi e deleghe permette di sviluppare questo in modo facile per qualunque tipo di delega/responsabilita' su Gaia, lasciando pieno controllo a chi registra il trasferimento.

Per quanto riguarda invece la partecipazione a attivita', questa va comunque gestita (a parte). Solo magari ritiriamo la richiesta di partecipazione, piuttosto che cancellarla (abbiamo lo stato ritirata, che mi sembra piu' opportuno).

**Comment by luca-dex** [comment]
Quesito: con le deleghe di livello superiore come si fa ad integrare il sistema che hai proposto? Tipo il delegato area 1 regionale va a vivere in un'altra regione.

**Comment by AlfioEmanueleFresta** [comment]
Il Presidente regionale dovrebbe comunicare cosa fare della delega Area 1 Regionale. Poi magari potrebbe non farlo immediatamente (immaginare che la cosa possa essere gestita post-trasferimento in 15gg?).

**Comment by luca-dex** [comment]
Allora menderei solo un alert, se la vedono poi loro. Non implementerei troppa soprastruttura su gaia. "Ciao, il tuo delegato area 1 regionale ha cambiato comitato, se la cosa ti crea problema toglielo, altrimenti lascialo lì". Invece mi sembra più interessante capire cosa succede se un presidente cambia comitato..

**Comment by PaoloGiustiniani** [comment]
up

**Comment by yakky** [comment]
@luca-dex #511 implementa una chiusura di tutte gli oggetti aperti (necessariamente sileziosa, visto che si tratta  di un trasferimento massivo).
Nella stessa PR la chiusura completa è implementata anche per dimissioni, espulsioni, trasferimenti "manuali"
Potete verificare la logica implementata lì per il momento?

**Comment by luca-dex** [comment]
Cosa succede quando va a chiudere le deleghe da `RESPONSABILE_AREA` o `REFERENTE`  e non trova nessuno al livello superiore a cui appioppare la delega?

**Comment by yakky** [comment]
Nell'implementazione attuale rimangono senza delegati

**Comment by luca-dex** [comment]
Mmm... Ok, la logica è sicuramente corretta per quanto riguarda #511, ed è corretto che le operazioni avvengano in maniera silenziosa. Poi per questa issue dovremo attenerci a quello che avevamo discusso mesi fa e aggiungere gli alert che avvisano che la tale delega è rimasta vuota.

**Comment by yakky** [comment]
@luca-dex si gestisce tutto dentro la #511 ?

**Comment by yakky** [comment]
Anche l'assegnazione della catena di appartenenenze è gestita in #511 https://github.com/CroceRossaItaliana/jorvik/pull/511/files#diff-1bb484c635d322f5a4983e42076450faR2113

**Comment by luca-dex** [comment]
perfetto
