### ISSUE TITLE
elenchi: richieste modifiche in estrazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#55]
Elenchi "per fogli":
- mostrare campo "tipo socio"

Elenchi "monofoglio" (da implementare)
- mostrare campo "tipo socio"
- mostrare campo "Comitato : Sede"

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni gli elenchi mono foglio sono implementati
