### ISSUE TITLE
Notifiche per estensioni, trasferimenti, riserve

### ISSUE THREAD

**Issue by yakky** [CroceRossaItaliana/jorvik#558]
Le notifiche di approvazione delle richieste devono essere gestite come segue:

# Trasferimenti

* [x] richiedente
* [x] sede origine
* [x] sede destinazione

# Estensioni

* [x] richiedente
* [x] sede origine
* [x] sede destinazione

# Riserve

* [x] richiedente
* [x] sede riferimento

Deriva da #229

**Comment by luca-dex** [comment]
Il senso è che la sede di destinzione deve essere aggiunta, ma che al momento ancora non c'è, corretto? Se si ok

**Comment by yakky** [comment]
@luca-dex esatto

**Comment by luca-dex** [comment]
Ok si, è quel che serve.
