### ISSUE TITLE
descrizione coerente contatori

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#57]
riporto considerazioni espresse in un ticket:

1) scritta che vede il presidente: " ... ha all'attivo 607 Persone e 560 Soci attivi,"
2) quando effettuo la generazione Volontari ottengo un elenco di 607 nominativi ed invece con la generazione di Soci il numero è di 560
3) Questo sta a significare che Persone=Volontari e Soci Attivi= Soci, non sarebbe meglio una descrittiva univoca nelle due pagine?

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni 
- numero di persone include sostenitori, dipendenti, volontari, estesi in ingresso
- numero di soci include solo volontari attivi, non include "soci sostenitori" e "volontari estesi"

Riapri se reputi necessario
