### ISSUE TITLE
[cron] elimina posta obsoleta

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#570]
È necessario prevedere un cron che cancelli in automatico i messaggi più vecchi di sei mesi.

**Comment by AlfioEmanueleFresta** [comment]
Sareste d'accordo nel cancellare il corpo della e-mail (che compone il 99% dello spazio occupato dai messaggi) ma mantenere oggetto e metadati? Lato utente, vedrebbero un messaggio simile a "*Questo messaggio e' piu' vecchio di sei mesi ed e' stato cancellato. Controlla la tua casella di posta elettronica.*"

@CroceRossaItaliana/sviluppo @CroceRossaItaliana/supporto

**Comment by luca-dex** [comment]
Col principio sì. Riusciamo a tenere 1 anno? (non so se il periodo era già
stato discusso)

**Comment by AlfioEmanueleFresta** [comment]
Abbiamo un totale di 1,3M messaggi, dimensione complessiva del corpo testo (stimato come 1 byte per carattere in campo `corpo`), 5,50GB.

- Eliminando dagli ultimi 6 mesi, ci libereremmo di 787k messaggi, per un totale approssimativo di 3,48GB
- Eliminando dagli ultimi 9 mesi, ci libereremmo di 430k messaggi, per un totale approssimativo di 2,02GB
- Eliminando dagli ultimi 12 mesi, ci libereremmo di 286k messaggi, per un totale approssimativo di 0,86GB

Mi preme precisare che non abbiamo davvero pressanti motivazioni per liberarci della posta, in quanto il rallentamento al database non e' dovuto a questi dati (il corpo del messaggio non viene infatti usato per le ricerche dei messaggi di posta, e tutto il resto dei campi e' correttamente indicizzato). Piuttosto, #443 e' la piu' probabile causa dei rallentamenti di Gaia.

**Comment by PaoloGiustiniani** [comment]
6 mesi, please.

**Comment by AlfioEmanueleFresta** [comment]
Ok. Paolo ti puoi occupare di mettere un backup al sicuro (dall'essere
rollato sopra), giusto in caso?

**Comment by PaoloGiustiniani** [comment]
Certamente
