### ISSUE TITLE
[menu] volontari visualizzano quello di aspiranti

### ISSUE THREAD

**Issue by PaoloGiustiniani** [CroceRossaItaliana/jorvik#571]
Abbiamo numerosissime segnalazioni inerenti la casistica in oggetto.

La casistica comune è la seguente:
Appartenenza da volontario 
Pagamento quota anno 2017

FKW-478-70000

Riproducibile anche in luke con persona 102397

**Comment by yakky** [comment]
@PaoloGiustiniani l'utente in questione ha *sia* l'appartenenza come volontario che l'oggetto aspirante collegato?

**Comment by PaoloGiustiniani** [comment]
@yakky si, presumo sia stata reclamata.

**Comment by yakky** [comment]
faccio un supplemento di analisi sul reclamo volontari, e comunque allora la soluzione è condivisa con #356

**Comment by PaoloGiustiniani** [comment]
@yakky @CroceRossaItaliana/sviluppo-collaboratori 

Novità?

**Comment by PaoloGiustiniani** [comment]
Possibile risoluzione in #588

**Comment by luca-dex** [comment]
risolta con #588
