### ISSUE TITLE
[sostenitori] Miglioramento gestione quote dei sostenitori

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#575]
Alla luce di quanto discusso con Rosario, per la gestione delle quote dei sostenitori devono essere rispettate le seguenti condizioni:
* qualsiasi persona che non è già Socio Volontario può diventare sostenitore della CRI pagando una quota di almeno 20€
* l'importo minimo è fisso ed è definito anche per i prossimi anni (a meno di variazioni che avverranno)
* la quota può essere pagata in qualsiasi momento dell'anno ed ha valore esclusivo solo per quell'anno. Questo significa che se una persona ha pagato la quota sostenitore 2017 il 5 ottobre 2017, fino al 31 dicembre 2017 rimane sostenitore. Sarà cura del Comitato rimuovere dagli elenchi la persona il giorno 1 gennaio 2018
* la quota deve essere rinnovata annualmente. La verifica degli avvenuti rinnovi è in carico ai Comitati a cui i sostenitori afferiscono
* i comitati provvedono a rimuovere dall'elenco dei sostenitori chi non ha versato la quota annua
una persona può essere sostenitore contemporaneamente su più Comitati (in ognuno devo pagare la quota annua)
* se un sostenitore diviene Volontario a seguito di un Corso Base, fino a che permangono i requisiti, continua ad essere un sostenitore
* l'albo dei sostenitori non è un libro soci, nè una sua sezione: è l'elenco di quelli che sostengono il comitato in quell'anno solare

A seguito dei punti sopra citati, per quel che riguarda gaia, secondo me l'unico intervento da fare è quello di portare l'importo minimo per la quota da 1 a 20€. Tutto il resto è in capo ai comitato. Gaia già provvede a fornire gli elenchi di chi ha pagato la quota sostenitore in un determinato anno.

Cosa ne pensate? @AlfioEmanueleFresta @PaoloGiustiniani @matthewmazzoleni

**Comment by AlfioEmanueleFresta** [comment]
Concordo. Come discusso pero', dobbiamo esplicitare il fatto che il mantenimento e l'aggiornamento dell'albo sostenitori e' a capo del singolo Comitato. Per questo Gaia non automatizza la rimozione da suddetto libro, ne ora ne in futuro.

**Comment by luca-dex** [comment]
Potremmo fare questa cosa che suggerisci aggiungendo dei testi informativi, magari che riportino le condizioni che ho inserito in testa alla issue

**Comment by yakky** [comment]
@luca-dex se ciu fornisci i testi informativi gestiamo tutto in un'unica PR
Proporrei di impostare la quota minima come campo del tesseramento, così è più semplice da gestire in futuro

**Comment by luca-dex** [comment]
Ok per la quota minima come campo del tesseramento.

La pagina di registrazione delle quote sostenitore attualmente è questa:

![sostenitori](https://user-images.githubusercontent.com/3315913/27358934-4073b4a8-5619-11e7-8039-bc17a34b9b2e.png)

Cosa da verificare:
* la quota sostenitore può essere versata per tutto l'anno del tesseramente corrente
* i testi li metterei sotto alla prima frase, ma prima della seconda
* sotto l'importo metterei qualcosa tipo "Il totale versato in euro, partendo da un minimo di XX €"

Per il testo scriverei una cosa del genere:

*Ricordati che:*
* *Un sostenitore è una persona che decide di versare una quota, a partire da XX €, ad un Comitato CRI. Può anche essere un Volontario. Un Sostenitore non è un Socio CRI e pertanto il pagamento della quota da Sostenitore non dà diritto a nessun beneficio aggiuntivo alla persona in questione. Una persona può essere Sostenitore in più Comitati.*
* *L'albo dei Sostenitori non è un libro Soci, nè una sua sezione: è l'elenco delle persone che sostengono economicamente il Comitato in quell'anno solare*
* *La quota da Sostenitore deve essere versata annualmente e la verifica del versamento è in capo ai Comitati CRI che si impegnano a rimuovere dall'elenco dei Sostenitori le persone che non hanno versato entro l'anno la quota prevista.*
* *Se un Sostenitore diviene Volontario a seguito di un Corso Base, fino a che permangono i requisiti, continua ad essere un sostenitore*

**Comment by luca-dex** [comment]
@yakky possiamo modificare due punti di quelli che ti ho mandato in questo modo? (mi sono confrontato con altre persone per migliorarne la comprensibilità)

> Un sostenitore è una persona che decide di versare una quota, a partire da XX €, ad un Comitato CRI. Può anche essere un Volontario. Un Sostenitore non è un Socio CRI e pertanto il pagamento della quota da Sostenitore non dà diritto a nessun beneficio aggiuntivo alla persona in questione. Una persona può essere Sostenitore in più Comitati.

in

> Può diventare Sostenitore ogni persona che già non sia Volontario CRI e che decide di versare una quota, a partire da XX €, ad un Comitato CRI. Un Sostenitore non è un Volontario e quindi non è un Socio CRI: il pagamento della quota da Sostenitore non dà diritto a nessun beneficio aggiuntivo alla persona in questione. Una persona può essere Sostenitore in più Comitati.

e poi modifica:

> Se un Sostenitore diviene Volontario a seguito di un Corso Base, fino a che permangono i requisiti, continua ad essere un sostenitore

in 

> Se un Sostenitore diviene Volontario a seguito di un Corso Base, mantiene la qualifica fino al termine dell'anno solare per il quale ha versato la quota. Sarà cura del Comitato rimuovere la persona dall'elenco dei Sostenitori a fine anno

Grazie
