### ISSUE TITLE
[dimissioni] errore 500 su dimissione volontario

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#579]
su dimissione del volontario con id_persona = 65370

si ottiene errore 500 e lo stacktrace riporta:

builtins:AttributeError: 'TitoloPersonale' object has no attribute 'ritira'
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1228, in _nr_wsgi_application_wrapper_
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 177, in __call__
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
File "/usr/local/lib/python3.4/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "./autenticazione/funzioni.py", line 117, in _pagina_privata
File "./ufficio_soci/viste.py", line 257, in us_dimissioni
File "./anagrafica/models.py", line 2298, in applica
File "./anagrafica/models.py", line 2298, in <listcomp>
File "./anagrafica/models.py", line 2297, in <listcomp>

**Comment by luca-dex** [comment]
@matthewmazzoleni poteva essere un problema provvisorio? A me la persona in questione risulta correttamente dimessa. Chiudiamo?

![modifica persona amministrazione sito django](https://cloud.githubusercontent.com/assets/3315913/26551104/3225093c-4481-11e7-8a15-d8c30e512381.png)

**Comment by PaoloGiustiniani** [comment]
No, non chiudiamo. Abbiamo tanti casi simili e l'errore è sempre quello presente nello strace.

Eleonora ha più casi.

**Comment by luca-dex** [comment]
Ok, allora mi servirebbe un altra situazione da poter testare se possibile.

**Comment by PaoloGiustiniani** [comment]
@Ele81

**Comment by Ele81** [comment]
Da dimettere ID=37577
Dimissione effettuata da ID=6443 o ID=628
Server error 500
Atti di dimissioni presenti per ogni tentativo effettuato
Se serve lo strace lo inviamo @PaoloGiustiniani

**Comment by luca-dex** [comment]
Ok, ho riprodotto il problema con questi ultimi dati.

![attributeerror at us dimissioni 37577](https://cloud.githubusercontent.com/assets/3315913/26552944/9ffb10c0-4489-11e7-91bb-9054741eda3a.png)

**Comment by matthewmazzoleni** [comment]
@luca-dex ho avuto direttamente esperienza di quell'errore 500 anche a fronte di corretta dimissione della persona

**Comment by PaoloGiustiniani** [comment]
Ultimi 7 giorni (un disastro).

![dimissioni1](https://cloud.githubusercontent.com/assets/5071623/26554839/92fbcad2-4492-11e7-8a01-fd3c79f0e07d.png)
![screenshot from 2017-05-29 17-16-17](https://cloud.githubusercontent.com/assets/5071623/26554842/95cb9e40-4492-11e7-9a76-fddceec37a06.png)

**Comment by luca-dex** [comment]
Ok, a questo punto direi che #591 fa parte di questa issue, vista la schermata che ha allegato paolo

**Comment by luca-dex** [comment]
Mi chiedo se con #547 non si riesca a risolvere il tutto?

**Comment by yakky** [comment]
Il problema è qui https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/models.py#L2349
Viene invocato un metodo ``ritira`` che non esiste.
@AlfioEmanueleFresta cosa dovrebbe fare quel metodo? Richiamare ``self.autorizzazioni_ritira()`` come in https://github.com/CroceRossaItaliana/jorvik/blob/master/formazione/models.py#L557 ?

**Comment by luca-dex** [comment]
Dovrebbe ritirare le richieste fatte di estensione, trasferimento, partecipazione a cose e di richiesta di convalida di titoli.

Sono sicuro che le richieste di trasferimento si possano ritirare (perchè nella vista è presente il tasto ritira) mentre non è presente il tasto ritira per le estensioni.

**Comment by luca-dex** [comment]
Qui #547 c'era una discussione in merito alla verifica di cosa fare quando si dimette una persona

**Comment by yakky** [comment]
@luca-dex secondo me è un typo, dovrebbe essere ``autorizzazioni_ritira`` anziché ``ritira``

**Comment by luca-dex** [comment]
Sì, effettivamente hai ragione. Se riusciamo a spuntare nell'altra issue tutte le cose che siamo sicuri che vengano correttamente chiuse ci portiamo già avanti

**Comment by yakky** [comment]
@luca-dex la logica che genera questo errore è il ritiro delle richieste pendenti, non di quelle già autorizzate. Probabilmente conviene gestire questo e #547 in modo separato intanto per sbloccare questa situazione di errore

**Comment by luca-dex** [comment]
ok, perfetto
