### ISSUE TITLE
[ufficio soci/estensioni] accettazione estensione non memorizza protocollo data e numero

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#58]
La funzione `autorizzazione_concessa` riceve il modulo di accettazione e si deve occupare di memorizzare i campi ricevuto nel modulo. Nel caso di `Estensione` questo non accade.

```python
    def autorizzazione_concessa(self, modulo=None):
        # ...
        self.protocollo_numero = modulo.cleaned_data['protocollo_numero']
        # ...
        self.save()

```

E' inoltre opportuno verificare che questo accada, nel caso sia applicabile, anche con
- Trasferimento
- Riserva

**Importante**: Nota che anche il metodo `autorizzazione_negata` riceve un modulo. Anche in caso di estensione negata e' necessario salvare numero e data protocollo della richiesta!

**Comment by AngeloLupo** [comment]
Trasferimenti ok

**Comment by AlfioEmanueleFresta** [comment]
Thanks @AngeloLupo
