### ISSUE TITLE
[popup admin] errore 500 su lookup lato admin

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#580]
questo link, aperto lato admin su selezione id comitato da inserire su una appartenenza, da errore 500:

https://gaia.cri.it/admin/anagrafica/sede/?_to_field=id&_popup=1

**Comment by luca-dex** [comment]
Non ho ben capito cosa fare per riprodurre questa cosa.. qual è il comportamento atteso?

**Comment by PaoloGiustiniani** [comment]
Il comportamento atteso è quello di listare le utenze.

L'errore è questo ma non ho uno strace

/django.contrib.admin.options:ModelAdmin.changelist_view
builtins:NameError

**Comment by luca-dex** [comment]
Ok, l'errore è questo

![nameerror at admin anagrafica sede](https://cloud.githubusercontent.com/assets/3315913/26551765/526076e8-4484-11e7-9eff-4c906ad037d1.png)

**Comment by yakky** [comment]
Pull request aperta, ma wonderbot non collabora nella creazione dell'ambiente

**Comment by yakky** [comment]
ambiente disponibile su http://pr-594.sviluppo-gaia.ovh/
