### ISSUE TITLE
[Richieste] Cartella richieste vuota 

### ISSUE THREAD

**Issue by Ele81** [CroceRossaItaliana/jorvik#606]
La domanda (est/trasf/ris) viene comunicata tramite il servizio "posta" ma non si trova nella cartella richieste senza dare l'opportunità di conferma o negazione. Dopo alcuni giorni la richiesta è attiva.
La richiesta di estensione proviene dall'utente 65280
La cartella RICHIESTE vuota è dell' ID 8092
Numero cronologico della richiesta 20093

**Comment by PaoloGiustiniani** [comment]
@luca-dex puoi fare review?

**Comment by luca-dex** [comment]
Penso stiate facendo un po' di confusione. L'utente 8092 è ufficio soci del comitato di destinazione dell'estensione. Riceve una notifica che il volontario 65280 vuole fare estensione verso il suo comitato, ma non è lui a doverla approvare, bensì il presidente/us del comitato di cui è volontario 65280. Una volta che il presidente/us di 65280 avranno approvato la sua richiesta di estensione, allora arriverà una notifica anche a 8092 che gli dirà che il volontario è esteso e lo troveranno nell'elenco dei soci.

Le cose stanno funzionando in maniera corretta.
