### ISSUE TITLE
[Appartenenza] Impossibilità modifica data inizio

### ISSUE THREAD

**Issue by Ele81** [CroceRossaItaliana/jorvik#608]
Non per tutti gli utenti è possibile modificare la data inizio appartenenza da parte dell' US o Presidente.
ID che apporta la modifica: 41723
ID dove è possibile la modifica: 67484
ID dove non c'è l'icona per modificare la data: 67474

**Comment by PaoloGiustiniani** [comment]
Vi erano due appartenenze con la stessa data di cui una negata.

Chiudo.
