### ISSUE TITLE
[Appartenenza] Impossibilità modifica data inizio

### ISSUE THREAD

**Issue by Ele81** [CroceRossaItaliana/jorvik#609]
Non per tutti gli utenti è possibile modificare la data inizio appartenenza da parte dell' US o Presidente.
ID che apporta la modifica: 5765
ID dove non c'è l'icona per modificare la data inizio: 236894

**Comment by luca-dex** [comment]
Ci sono delle regole stringenti sulle situazioni in cui è possibile modificare una data di inizio appartenenza. In particolare può essere modificata solo ed esclusivamente la prima appartenenza di una persona che non sia collegata a qualche altro evento registrato su gaia (corso base o rientro dove essere precedentemente stati volontari dimessi per qualsiasi motivo). Non è nemmeno possibile spostare appartenenze vincolate da date di pagamento di quote.

La issue che gestisce tutto ciò è stata rilasciata in tempi abbastanza recenti, quindi è molto probabile che gaia non faccia modificare la data perchè quella data non deve essere modificata. Fai prima un controllo, poi nel caso fammi sapere che verifico anche io.
