### ISSUE TITLE
sedi: nascondere le sedi disattivate

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#61]
arrivano diverse segnalazioni da parte di presidenti che segnalano la presenza delle sedi chiuse nelle loro pagine di amministrazione, sarebbe opportuno nasconderle direttamente così da evitare disguidi

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni 
- Le deleghe direttamente relative a sedi chiuse vengono terminate automaticamente dalla migrazione
- I permessi non vengono piu' espansi per sedi disattive, quindi ad esempio il presidente locale non ha piu' poteri su una unita territoriale disattiva, e non la vedra' neanche nell'elenco
