### ISSUE TITLE
[nuovo utente] saltare verifica token di registrazione in fase di debug

### ISSUE THREAD

**Issue by luca-dex** [CroceRossaItaliana/jorvik#610]
Prevedere che negli ambienti di debug, a fini di sviluppo, non sia necessaria la verifica del token per la registrazione di un aspirante con qualcosa del tipo
```
if DEBUG:
  continue
```

**Comment by AlfioEmanueleFresta** [comment]
Dove con "in fase di debug" @luca-dex intende qualora la variabile `settings.DEBUG` sia impostata a vero, ovvero negli ambienti di staging e ambienti di sviluppo locale, dove e' spesso oneroso andare a recuperare il messaggio di posta col token inviato (e.g. andare a recuperare il file di log creato dal backend fittizio di posta django)

**Comment by AlfioEmanueleFresta** [comment]
Aumentato di priorita' perche' e' una easy-fix che sblocca QA

**Comment by yakky** [comment]
il problema è che token (e sessione) sono informazioni indispensabili per procedere. Si potrebbe in alternativa stamparli nella pagina di risposta (https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/viste.py#L236) mettendoli nel contest, eventualmente mettendo direttamente il link per procedere alla fase successiva. Sempre ovviamente con ``DEBUG`` attivo

**Comment by luca-dex** [comment]
Essendo in ambiente di debug / sviluppo non penso sia problematico avere il link nella pagina. Se @AlfioEmanueleFresta è d'accordo, per me va bene

**Comment by AlfioEmanueleFresta** [comment]
Y

Alfio

**Comment by yakky** [comment]
@luca-dex il tempo del deployment di wonderbot e la modifica è su
