### ISSUE TITLE
[Verifica Tesserino] Correzione messaggio Gaia

### ISSUE THREAD

**Issue by Ele81** [CroceRossaItaliana/jorvik#618]
In fase di verifica di un tesserino è errata viene mostrato il seguente messaggio:
--------------------------------------
Il tesserino di cui hai richiesto la verifica risulta non valido. La causa può essere una delle seguenti:

Hai inserito in modo errato il numero di tessera;
Il tesserino appartiene ad una persona non più in Croce Rossa Italiana;
Il Volontario è in regola con la quota associativa.
--------------------------------------
L'indicazione dell'ultima delle cause penso sia errata:
"Il Volontario è in regola con la quota associativa"
e dovrebbe essere integrata nel seguente modo
"Il Volontario **NON** è in regola con la quota associativa"

**Comment by PaoloGiustiniani** [comment]
Typo.

**Comment by luca-dex** [comment]
faccio io
