### ISSUE TITLE
riserva: inserimento riserva non chiede protocollo e approvazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#62]
come da oggetto, l'inserimento da parte di US di una riserva non mostra richiesta protocollo e autorizzazione della stessa.

**Comment by AngeloLupo** [comment]
@AlfioEmanueleFresta ha gia' risolto, commit in arrivo

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo ?

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo can you follow up on this soon?

**Comment by matthewmazzoleni** [comment]
up

**Comment by AngeloLupo** [comment]
Non sto riuscendo a capire il motivo. Ne parlo in serata con Alfio

**Comment by AngeloLupo** [comment]
Non replicabile da US e da volontario

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta questo è ancora valido?
Da test preliminari non vedo una condizione in cui il form non presenti

**Comment by PaoloGiustiniani** [comment]
@matthewmazzoleni puoi dettagliare la richiesta?

Il numero del protocollo è necessario inserirlo come campo facoltativo?

L'autorizzazione della stessa è presente nella pagina "Richieste" che richiede conferma di approvazione.

Questa è la pagina che si presenta dopo aver inserito una riserva:

![test](https://cloud.githubusercontent.com/assets/5071623/22625913/6181e792-eba1-11e6-92ab-eaae52ea03ce.png)

Possiamo ottimizzarla con "La riserva è stata registrata con successo, ti ricordiamo di approvare la richiesta inserita. 

Verifica le richieste in attesa di approvazione (Tasto verde)."

**Comment by matthewmazzoleni** [comment]
la richiesta risale a talmente tanto tempo fa che il problema puntuale ora non lo ricordo perfettamente, ricordo che principalmente non veniva mostrata la richiesta alle persone preposte, ma suppongo sia stata sistemata nel tempo in altro ticket. direi che possiamo lasciare facoltativamente il protocollo laddove ci sia già la predisposizione, altrimenti chiudiamo.
