### ISSUE TITLE
estensioni: comportamento anomalo

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#63]
- L'US  ha accettato/protocollato la richiesta entrante di estension. La stessa richiesta ora risulta in attesa di approvazione, nella scheda del Volontario, ma da Ufficio Soci non possiamo autorizzarla e, cosa ancor più strana, accedendo come Presidente questa non compare tra le richieste in attesa.

- nell'assegnare il protocollo alla richiesta accetta solo numeri, mentre il nostro protocollo è costruito con formato 1234/AB/2016

**Comment by AngeloLupo** [comment]
https://github.com/CroceRossaItaliana/jorvik/blob/master/anagrafica/forms.py#L205 Dovrebbe essere un CharField e non un IntegerField

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni @AngeloLupo un errore nel codice causava un secondo step di troppo, ovvero che per la appartenenza creata di estensione veniva richiesta conferma al presidente del commitato di destinazione.

Ho corretto il problema. @matthewmazzoleni puoi correggere questo caso a mano (identificandoti come il presidente credo sia il metodo piu' rapido), non accadra' piu'.
