### ISSUE TITLE
rubrica e servizi: visualizzazione limitata alla unità territoriale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#65]
non si vedono più ne la rubrica dei Volontari del Comitato nè i servizi ma solo quelli relativi alla sede di appartenenza. Sarebbe opportuno che i Volontari di un Comitato LOcale potessero vedere tutto quello che concerne il loro Comitato Locale e non solo la loro sede (in particolare recapiti telefonici e servizi organizzati dalla sede)

**Comment by AlfioEmanueleFresta** [comment]
Risolto tempo addietro.
