### ISSUE TITLE
Estensione: mostrata al presidente come richiesta di appartenenza

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#67]
Al presidente del Comitato è comparsa la richiesta (per utente https://gaia.cri.it/profilo/145669/ ) di confermare l'APPARTENENZA alla Sede di Tarcento, come se l'utente si fosse appena registrato al sistema. In realtà il volontario già figura  presso altra Sede del Comitato, ovvero Moggio.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni questo e' stato causato dal bug risolto in #63. Il presidente puo' semplicemente accettare la richiesta?
