### ISSUE TITLE
unità territoriali: spostamento volontari

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#70]
precedentemente era possibile trasferire Volontari tra unità territoriali del medesimo comitato, cosa formalmente non corretta ma che otteneva il risultato. Al momento è impossibile procedere allo spostamento. sarebbe opportuno ci fosse una maschera dedicata che permettesse a US di spostare il Volontario/Socio su unità territoriale del medesimo Comitato.

**Comment by AngeloLupo** [comment]
Funzionavano gia', ma abbiamo rimosso la necessita' di accettare la richiesta per i trasferiementi dove il comitato e' lo stesso.

**Comment by matthewmazzoleni** [comment]
up
