### ISSUE TITLE
dati del comitato: restituisce server error

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#72]
8233 riceve server error aprendo dati del proprio comitato (è presidente)

**Comment by AlfioEmanueleFresta** [comment]
Non riesco a riprodurre in produzione. Non ne trovo nuove istanze negli ultimi 3 giorni su New Relic. 

Temo che questo sia stato un errore causato dalla vecchia procedura di messa in produzione (che terminava in malo modo le connessioni in corso).
