### ISSUE TITLE
titolo di studio: viene richiesta data scadenza

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#73]
inserimento di titolo di studio chiede la data di scadenza, serve verificare la distinzione tra i vari tipi di titoli

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni dal pannello di amministrazione e' possibile selezionare su base di titolo per titolo qualora sia richiesta o meno ognuna delle informazioni.

Chiudo, a meno che ti serva che aggiorni i titoli massivamente per tipo o simile.

**Comment by matthewmazzoleni** [comment]
necessario correggere massivamente: rimozione scadenza, codice, luogo, etc.. per titoli di studio
