### ISSUE TITLE
aspirante: auto cancellazione dal portale

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#74]
sembra mancare la funzionalità di auto-cancellazione per gli aspiranti.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni ti confermo che manca. Data la relativa bassa urgenza ti prego di procedere per questo caso con l'eliminazione della **persona** dal pannello admin > anagrafica. Lascio aperto.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni gli aspiranti che **non** hanno:
- Appartenenze di alcun tipo (es. sostenitore)
- Quote
- Partecipazione a corso base
- Partecipazione a attivita' (non attualmente applicabile)

Trovano un pulsante per cancellare il proprio profilo da Gaia in fondo alla pagina Aspirante > Impostazioni.

@CroceRossaItaliana/supporto ack
