### ISSUE TITLE
[autoparco] non si vede storico collocazioni

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/jorvik#75]
Nello storico delle collocazioni di un veicolo non vengono mostrate date di inizio e, ove passata, fine collocazione.

**Comment by AngeloLupo** [comment]
Serve il merge del template. Gia' risolto su master.
https://github.com/CroceRossaItaliana/jorvik/blob/master/veicoli/templates/veicoli_collocazione.html#L31

https://github.com/CroceRossaItaliana/jorvik/blob/produzione/veicoli/templates/veicoli_collocazione.html#L31

**Comment by AlfioEmanueleFresta** [comment]
OK
