### ISSUE TITLE
richieste: filtri non mostrati correttamente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#77]
utente 1666 ha diversi tipi di richieste nell'elenco (titoli, titoli cri, patenti) ma nei filtri a lato vede solamente "titoli".

**Comment by AlfioEmanueleFresta** [comment]
I titoli scindibili sono attualmente la stessa entita' e non facilmente scindibili. Questo migliorera' con l'introduzione delle patenti nel Q3 2016 e delle qualifiche CRI con accademia (Q? 20??).
