### ISSUE TITLE
apertura scheda persona: errore 404

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#78]
quando 72877 apre il profilo di 63421 riceve error 404

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni puoi specificare da quale pagina raggiunge il link rotto?

La pagina di profilo ritorna 404 solo per oggetto non trovato.
Tutti i link ai profili dei volontari sono stati generati usando lo stesso metodo (`Persona.url`), quindi il problema deve essere nella pagina che contiene il link.
