### ISSUE TITLE
email: segnalati invii multipli a medesimo destinatario

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#81]
si segnala da diversi Comitati che le email generate dal sistema vengono recapitate "4 o 5 volte" alla medesima persona.

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni puoi per caso farti dire qual e' l'oggetto del messaggio in questione?

@PaoloGiustiniani potresti verificare che il messaggio e' effettivamente partito due volte dal log SMTP e se si' a che ora?

**Comment by matthewmazzoleni** [comment]
arrivano segnalazioni da altri comitati per lo stesso problema anche oggi

**Comment by PaoloGiustiniani** [comment]
Confermo la presenza di quanto segnalato da @matthewmazzoleni.

Nello specifico mi risulta che una mail sia stata recapitata allo stesso volontario 8 volte ed un' altra 6.

**Comment by AlfioEmanueleFresta** [comment]
A quanto pare il modulo `django_cron` che usiamo per lo smistamento dei cron, che da manuale dice di evitare le esecuzioni parallele, per qualche motivo semplicemente non funziona.

Ho provato a modificare il backend di caching, ma senza fortuna.

Per ora ho implementato un controllo (https://github.com/CroceRossaItaliana/jorvik/commit/36248ada0c363aba33c6674821cf616825cad815) che risolve il problema, anche se potrebbe rallentare leggermente gli invii.
