### ISSUE TITLE
deleghe: non funziona correttamente attivazione/terminazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#84]
- la delega di 4083 su autoparco, registrata come terminata: "Sabato 23 Gennaio 2016 11:14" risulta ancora attiva nel medesimo giorno alle 18.31.

- si segnala inoltre da parte di 5306 che assegnando la delega il volontario non visiona la funzionalità e il presidente non vede, nonostante la delega sembri registrata, il tasto termina.

- 5306 segnala che terminando delega il volontario risulta con fine incarico corretta, ma vede ancora la funzionalità. il tasto "termina" rimane però attivo e ogni volta che lo si preme viene inviata email di termine delega al volontario pur non accadendo nulla.

**Comment by AlfioEmanueleFresta** [comment]
Questo e' causato dal fatto che il sistema usa attualmente la giornata per calcolare le deleghe. 

La modifica appena effettuata rende il calcolo delle deleghe e appartenenze attuali "al momento" piuttosto che "al giorno".
