### ISSUE TITLE
estensione: pdf generato erroneamente

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#85]
un volontario segnala che il pdf generato per la sua estensione riporta i dati dell'estensione precedentemente chiusa. ha allegato i pdf in WYY-162-46253

altra segnalazione riguardo pdf:
1 - non compare il comitato di destinazione fra i destinatari della comunicazione
2 - la data di appartenenza del volontario presso il comitato di appartenenza non è corretta: riporta l'anno di entrata in CRI.

**Comment by AngeloLupo** [comment]
Ho scordato di chiudere, passando l'appartenenza corretta al pdf e sistemando un errore di battitura il pdf mostra i dati corretti.

**Comment by matthewmazzoleni** [comment]
70572 segnala che il pdf generato per l'estensione riporta come comitato di appartenenza un comitato non corretto, ossia un comitato dove il Volontario era/è esteso.

dettagli: YIO-600-10284

**Comment by matthewmazzoleni** [comment]
up @AngeloLupo 
altri casi: YTQ-352-20801

**Comment by AngeloLupo** [comment]
Si trattava di un errore diverso. Dovrebbe essere sistemato.
@AlfioEmanueleFresta puoi controllare per favore?

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo il problema e' ancora attuale. 

Fai riferimento al caso (1) nel ticket YTQ-352-20801. La sua descrizione del problema e' accurata. Puoi identificarti come la persona che ha aperto il ticket, ha ancora la richiesta in sospeso.

**Comment by AlfioEmanueleFresta** [comment]
Ho testato in produzione. Se vuoi testare il codice in `issue85` fai il merge dentro `staging-chewbacca`, fai il push e verifica in ambiente di staging.
