### ISSUE TITLE
estensione: non visionata da presidente del comitato di destinazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#86]
viene comunicato che, a fronte di richiesta effettuata da 86743, non viene visionata la richiesta nell'elenco del Comitato di destinazione.

**Comment by AlfioEmanueleFresta** [comment]
Stiamo parlando dell'elenco delle estensioni in ingresso oppure della richiesta di estensione?

**Comment by matthewmazzoleni** [comment]
allego un ticket di esempio (ve ne sono diversi):
YNT-292-62118

**Comment by matthewmazzoleni** [comment]
up, segnalano molte richieste che non vengono visionate/approvate
