### ISSUE TITLE
soci dimessi: mancata associazione al comitato post migrazione

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#87]
esempi persone:
- 74912
- 33012

questo comporta inoltre mancato conteggio nei totali quote ai comitati

**Comment by matthewmazzoleni** [comment]
up

**Comment by AlfioEmanueleFresta** [comment]
Confermo che si tratta di un caso di mancata migrazione causa utenza con e-mail duplicata, come visto precedentemente. Questo ha causato la mancata importazione dei dati associati, inclusa l'appartenenza, che ha causato lo scollegamento della quota relativa.
