### ISSUE TITLE
caricamento foto tesserino: errore 500

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#88]
volontario 137952 cerca di caricare tesserino ma riceve:

server error 500

**Comment by AlfioEmanueleFresta** [comment]
Credo stia tentando di caricare un formato che sia
* **immagine**
* **NON** jpeg o png

Questo chiaramente va comunque risolto (ie. recuperato con errore grazioso)

**Comment by AlfioEmanueleFresta** [comment]
A quanto pare da New Relic, l'errore generato e' il seguente:
```
builtins:ValueError: Il ruolo che si richiede firmi questa autorizzazione non esiste.
```

Nel commit sopra ho aggiunto supporto per memorizzazione dell'utente identificato negli stack, in modo da rendere piu' facile il debug.

Controllo il perche' di questo errore.

**Comment by AlfioEmanueleFresta** [comment]
Risolto.
