### ISSUE TITLE
invio email: numero massimo di caratteri

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#89]
il sistema impedisce l'invio in quanto riscontra un numero di caratteri eccedenti il numero consentito che è di 10.000 la nostra mail contiene un numero di 878 caratteri compresi gli spazi.

**Comment by AlfioEmanueleFresta** [comment]
Eh, ma HTML. Avranno copiato e incollato da word? Aumenteremo il limite.

Alfio Emanuele Fresta

**Comment by matthewmazzoleni** [comment]
metterei di default un filtro che rimuova le formattazioni per il copia-incolla, piuttosto..
