### ISSUE TITLE
admin: vincoli su campi

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#91]
in alcune maschere non è valorizzato il campo "firmatario" per elementi creati dal sistema in fase di migrazione. su modifica dell'anagrafica viene chiesto di valorizzare tale campo.

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo se il campo (come credo) lato utente viene popolato automaticamente dal sistema piuttosto che dal form, possiamo permetterci di aggiungere un `blank=True` per permettere agli amministratori di gestire le schede.

**Comment by AngeloLupo** [comment]
Ho modificato alcuni campi, lascio l'issue aperta in caso ne servissero altri

**Comment by matthewmazzoleni** [comment]
il CF dell'anagrafica.

**Comment by AlfioEmanueleFresta** [comment]
Non possiamo metterlo blank, purtroppo, questo renderebbe il campo
nullabile dagli utenti.

Alfio Emanuele Fresta

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni sfortunatamente questa modifica non e' semplice, perche' nelle fondamenta del modello `Persona` e' stato impedita la validazione dei codici fiscali errati. Questo e' stato fatto al fine di migliorare la qualita' della banca dati.

Comprendo le difficolta' che questo puo' causare, mi chiedo pero' se non puo' essere usata in modo tale da alleviare invece il lavoro sul supporto, permettendo di rifiutare le casistiche con CF errati, visto che questi possono essere generalmente corretti comunque da US, avendo il doppio effetto di migliorare la qualita' dei dati gia' presenti.
