### ISSUE TITLE
email: link a pdf errato nella mail

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#93]
le richieste di estensione, quando arrivano via mail al presidente, non reindirizzano al link esatto, quindi è possibile scaricare il pdf con la richiesta esclusivamente da Gaia

**Comment by AlfioEmanueleFresta** [comment]
Bisogna rendere tutti i link assoluti (prependere `https://gaia.cri.it`) prima del salvataggio del messaggio.
