### ISSUE TITLE
verifica correttezza su procedura di reclamo persona

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#94]
US 27224 segnala quanto segue:

Ho dimesso un volontario e l' ho reclamato tramutandolo in dipendente. Così risulta nell'elenco dei dipendenti e non più in quello dei volontari. Risulta comunque nell'elenco soci. è corretto?

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni l'elenco soci viene generato **al giorno**. Quindi se viene generato l'elenco soci nella stessa giornata della dimissione, il dipendente viene incluso perche' **nell'arco della giornata e' stato socio**. Generando l'elenco al giorno successivo questo non dovrebbe accadere.

L'elenco soci mi risulta correttamente includere solo 
```python
    MEMBRO_SOCIO = (VOLONTARIO, ORDINARIO,)
```
