### ISSUE TITLE
mobile: accesso non possibile

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#95]
molti utenti segnalano che accedendo da desktop non hanno problemi mentre se tentano l'accesso da dispositivi mobile hanno problemi in fase di autenticazione.

**Comment by AlfioEmanueleFresta** [comment]
Che problema hanno esattamente? E' lo stesso identico modulo...

**Comment by matthewmazzoleni** [comment]
password errata

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni devono sbagliare a inserire la e-mail o la password. Ricordagli che e' case sensitive. Se ci sono altri problemi riapri.

**Comment by alfiomusmarra** [comment]
Ho una teoria in tutto ciò, che mi deriva dall'esperienza con il
blackberry: non è che quando si spostano sul campo "email" o "password" la
tastiera passa in modalità "prima lettera maiuscola"?

**Comment by matthewmazzoleni** [comment]
confermo che il problema è dovuto alla supposizione di @alfiomusmarra, la lettera maiuscola all'inizio della mail pregiudica l'accesso a GAIA. mettiamo un insensitive sul case per la username, please
