### ISSUE TITLE
elenco soci passivi: presenza di minorenni

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#97]
segnalano la presenza di minorenni nell'elenco soci passivi, ho chiesto esempi ma per il momento vista la criticità segnalo comunque e integrerò.

**Comment by AlfioEmanueleFresta** [comment]
Questa roba ha unit test che ne verificano il funzionamento, quindi per
favore chiedi esempi

Alfio Emanuele Fresta

**Comment by AlfioEmanueleFresta** [comment]
@matthewmazzoleni se risulta valida per favore riapri.
