### ISSUE TITLE
admin: cancellazione non possibile a catena

### ISSUE THREAD

**Issue by matthewmazzoleni** [CroceRossaItaliana/jorvik#99]
Chiedo l'abilitazione della cancellazione a cascata, vista la situazione seguente:
- Cancellando appartenenza da persona ottengo: "oggetto protetto"
- Cancellando appartenenza da appartenenze ottengo:

Impossibile cancellare appartenenza
La cancellazione di appartenenza 'Appartenenza object' richiederebbe l'eliminazione dei seguenti oggetti protetti correlati:

Documento di Dimissione: Dimissione object

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo puoi cambiare in `Dimissione` sul campo `appartenenza` l'`on_delete=models.CASCADE`?

**Comment by matthewmazzoleni** [comment]
aggiungo anche eventuale cascata su "documento di dimissione"

**Comment by matthewmazzoleni** [comment]
abbiamo molte cancellazioni in coda.

**Comment by AngeloLupo** [comment]
Aggiunto ```on_delete = models.CASCADE```

**Comment by matthewmazzoleni** [comment]
"La cancellazione di appartenenza Appartenenza object richiederebbe l'eliminazione dei seguenti oggetti protetti correlati: Richiesta di trasferimento Trasferimento object"

è possibile sistemarle tutte senza che emergano una ad una?

**Comment by AlfioEmanueleFresta** [comment]
Direi di mantenere solo la protezione per l'eliminazione delle Sedi, a questo punto?

**Comment by matthewmazzoleni** [comment]
aggiungo: La cancellazione di appartenenza Appartenenza object richiederebbe l'eliminazione dei seguenti oggetti protetti correlati: Richiesta di trasferimento Trasferimento object

**Comment by AlfioEmanueleFresta** [comment]
Possiamo permettere l'eliminazione automatica di tutto, meno che delle quote-ricevute, a mio avviso.

**Comment by AngeloLupo** [comment]
Ho lasciato solo le sedi, e `sedi_sit` in https://github.com/CroceRossaItaliana/jorvik/blob/master/sangue/models.py#L76

@AlfioEmanueleFresta altro? Per le quote metto persona e sedi nullabili e uso setnull?

**Comment by AlfioEmanueleFresta** [comment]
@AngeloLupo non ha senso `sedi_sit`, come detto sopra, l'unica cosa che non deve essere cancellabile a catena sono le quote (non vogliamo che vengano eliminate erroneamente).

Se hai dubbi fai riferimento alla documentazione di django https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.on_delete

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta qual è la situazione qui? cosa manca?

**Comment by yakky** [comment]
@matthewmazzoleni @AlfioEmanueleFresta qual è la situazione? Vedo un commit che linka questa segnalazione. ripartiamo dal master attuale?

**Comment by matthewmazzoleni** [comment]
@yakky non ho seguito la struttura del repo, rimando a @AlfioEmanueleFresta

**Comment by PaoloGiustiniani** [comment]
@yakky conviene ripartire dal master attuale, da quanto ricordo non era stata portata avanti.

**Comment by AlfioEmanueleFresta** [comment]
La cancellazione a catena non dovrebbe essere piu' un problema. L'unico oggetto protetto dalle cancellazioni a cascata in database attualmente sono le ricevute, che NON devono essere eliminabili per motivi fiscali.
